import type { Metadata } from 'next';
import { organizations } from '../../lib/ecosystem';

export const metadata: Metadata = { title: 'Organizations & Standards: Robin’s Hood', description: 'Understand important standards bodies, agencies, communities, professional institutions and technology providers.' };

const preferredGroups = ['Standards body', 'Technical standards community', 'Web standards organization', 'Public technical institute', 'Public cybersecurity agency', 'Nonprofit security community', 'Professional association', 'Professional body', 'International financial institution', 'Global banking standard setter', 'Industry standards body', 'Open-source foundation', 'Commercial cybersecurity provider', 'Commercial cybersecurity and observability provider', 'Commercial identity-security provider', 'Commercial identity provider', 'Commercial data and artificial-intelligence platform provider', 'Commercial technology provider', 'Commercial enterprise-software provider', 'Commercial enterprise-platform provider'];
const allTypes = Array.from(new Set(organizations.map((item) => item.type)));
const groups = [...preferredGroups.filter((group) => allTypes.includes(group)), ...allTypes.filter((group) => !preferredGroups.includes(group)).sort()];

export default function OrganizationsPage() {
  const institutionCount = organizations.filter((item) => !item.type.startsWith('Commercial')).length;
  return <main className="inner-page organizations-page">
    <section className="page-hero organizations-hero"><p className="eyebrow dark"><span /> Authority is a role, not a popularity contest</p><div><h1>Know who shapes<br /><em>the ecosystem.</em></h1><p>Understand what important institutions publish, where their authority begins and ends, and how to find the primary source.</p></div><aside><strong>{organizations.length}</strong><span>starter profiles</span><i>{institutionCount} public / community</i></aside></section>
    <section className="authority-strip"><div><span>Regulator</span><b>May enforce legal requirements</b></div><i>→</i><div><span>Standards body</span><b>Develops agreed specifications</b></div><i>→</i><div><span>Community</span><b>Shares practice and knowledge</b></div><i>→</i><div><span>Vendor</span><b>Provides products and services</b></div></section>
    <section className="organization-groups">{groups.map((group) => { const items = organizations.filter((org) => org.type === group); if (!items.length) return null; return <div className="organization-group" key={group}><header><span>{group}</span><b>{items.length}</b></header><div className="organization-grid">{items.map((org) => <article id={`org-${org.acronym.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`} key={org.acronym}><div className="org-mark">{org.acronym}</div><div className="org-copy"><small>{org.region}</small><h2>{org.name === org.acronym ? org.name : `${org.name} (${org.acronym})`}</h2><p>{org.description}</p>{org.placement && <div className="org-placement"><b>Where it sits</b><p>{org.placement}</p></div>}{org.products && <div className="org-products"><b>Important products</b><div>{org.products.map((item) => <span key={item}>{item}</span>)}</div></div>}{org.capabilities && <div className="org-capabilities"><b>Capabilities</b><div>{org.capabilities.map((item) => <span key={item}>{item}</span>)}</div></div>}{org.practitionerUse && <div className="org-practice"><b>What to inspect</b><p>{org.practitionerUse}</p></div>}{org.competitors && <div className="org-competitors"><b>Compare with</b><span>{org.competitors.join(' · ')}</span></div>}<div className="limitation"><b>Know the limit</b>{org.limitation}</div><a href={org.url} target="_blank" rel="noreferrer">Official source ↗</a></div></article>)}</div></div>; })}</section>
    <section className="vendor-note"><span>Neutrality note</span><h2>Commercial providers belong in the map: but not in the same authority category.</h2><p>Product documentation is the right primary source for product behavior. It is not law, regulation or an independent standard. Robin’s Hood labels the difference visibly.</p></section>
  </main>;
}
