import type { Metadata } from 'next';
import Link from 'next/link';
import LinuxPermissionsLab from '../../components/LinuxPermissionsLab';

export const metadata: Metadata = {
  title: 'Linux Learning Lab | Robin’s Hood',
  description: 'A structured Linux tutorial covering the filesystem, shell, users, permissions, processes, services, networking, logs, patching and system hardening.',
};

const route = [
  { n: '01', title: 'Filesystem and shell', detail: 'Learn paths, directories, files, streams, pipes and safe navigation.', href: '/learn/linux-foundations-filesystem-and-shell' },
  { n: '02', title: 'Users and permissions', detail: 'Understand identity, ownership, rwx, octal notation, umask and special bits.', href: '/learn/linux-users-groups-and-file-permissions' },
  { n: '03', title: 'Processes and services', detail: 'Trace a running program through a process, service, socket, dependency and log.', href: '/learn/linux-processes-services-logs-and-networking' },
  { n: '04', title: 'Administration and hardening', detail: 'Patch, configure, restrict, observe, recover and verify a secure baseline.', href: '/learn/linux-administration-patching-and-hardening' },
  { n: '05', title: 'Baseline verification', detail: 'Turn hardening intent into testable configuration, drift detection and evidence.', href: '/learn/system-hardening-baselines-and-verification' },
];

const filesystem = [
  { path: '/', name: 'Root', purpose: 'The top of the filesystem tree. Every absolute path starts here.', caution: 'Do not confuse the root directory with the root administrative user.' },
  { path: '/etc', name: 'Configuration', purpose: 'System-wide configuration and service settings.', caution: 'Changes can affect the whole host. Preserve the previous value and validate syntax.' },
  { path: '/var', name: 'Variable state', purpose: 'Logs, caches, queues, databases and other state that changes during operation.', caution: 'Unexpected growth can fill a filesystem and stop services.' },
  { path: '/home', name: 'User homes', purpose: 'Personal files and configuration for ordinary human users.', caution: 'Ownership and privacy need review when accounts change or are removed.' },
  { path: '/usr', name: 'User-space programs', purpose: 'Most installed programs, libraries, documentation and shared resources.', caution: 'Package managers normally own these files. Manual edits may be overwritten.' },
  { path: '/tmp', name: 'Temporary shared space', purpose: 'Short-lived working files used by many programs and users.', caution: 'Commonly uses 1777 so the sticky bit prevents users deleting one another’s files.' },
  { path: '/proc', name: 'Process and kernel view', purpose: 'A virtual filesystem exposing live process and kernel information.', caution: 'It is generated by the kernel and does not behave like ordinary stored files.' },
  { path: '/dev', name: 'Device interfaces', purpose: 'Special files representing disks, terminals and other devices.', caution: 'Writing to the wrong device can damage data or disrupt the system.' },
];

const octal = [
  ['0', '---', 'No permission'], ['1', '--x', 'Execute or traverse'], ['2', '-w-', 'Write'], ['3', '-wx', 'Write plus execute'],
  ['4', 'r--', 'Read'], ['5', 'r-x', 'Read plus execute'], ['6', 'rw-', 'Read plus write'], ['7', 'rwx', 'Read, write and execute'],
];

const hardening = [
  ['Scope and inventory', 'Name the asset, owner, purpose, criticality, data, supported version and dependencies. You cannot harden an unknown or unowned system.'],
  ['Trusted installation', 'Use an approved image and repository, verify packages, remove unnecessary components and record the build source.'],
  ['Patch and lifecycle', 'Define normal and emergency updates, maintenance windows, rollback and an exit plan for unsupported software.'],
  ['Least functionality', 'Disable unused services, close unused ports, remove unused accounts and packages, and document every necessary exception.'],
  ['Users and authorization', 'Use named accounts, least privilege, controlled sudo, separate service identities, protected secrets and timely removal.'],
  ['Files and directories', 'Set explicit ownership, rwx or Access Control Lists, protect sensitive configuration and test temporary and shared directories.'],
  ['Connections and logins', 'Constrain Secure Shell access, require strong authentication, set session limits, protect management paths and monitor failure.'],
  ['Logging and audit', 'Collect authentication, privilege, service, configuration and security events with synchronized time and actionable retention.'],
  ['Data and recovery', 'Encrypt where appropriate, protect backups and configuration exports, test restore and retain safe recovery access.'],
  ['Verify and correct drift', 'Compare reality with a versioned baseline, assign exception owners and expiry, remediate change, then retest.'],
];

const commands = [
  { area: 'Navigate and inspect', examples: ['pwd', 'ls -la', 'cd /var/log', 'find /srv/app -maxdepth 2 -type f'], intent: 'Understand where you are and inspect before changing anything.' },
  { area: 'Read text safely', examples: ['less file', 'head -n 20 file', 'tail -n 50 file', 'grep -n pattern file'], intent: 'Read a bounded amount of evidence and search without editing.' },
  { area: 'Identity and permissions', examples: ['id', 'getent group app', 'stat path', 'namei -l /srv/app/config'], intent: 'Inspect user, group, ownership and every directory permission in a path.' },
  { area: 'Processes and services', examples: ['ps aux', 'systemctl status service', 'journalctl -u service --since today', 'ss -lntp'], intent: 'Connect a process to its service state, journal and listening socket.' },
  { area: 'Network evidence', examples: ['ip address', 'ip route', 'ss -tunap', 'dig example.org', 'curl -I https://example.org'], intent: 'Check local addressing, routes, sockets, name resolution and an application response.' },
  { area: 'Storage and capacity', examples: ['df -h', 'du -sh path', 'lsblk', 'mount'], intent: 'Separate filesystem capacity, directory usage, block devices and mounted views.' },
];

export default function LinuxPage() {
  return <main className="linux-page">
    <section className="linux-hero"><div><p className="eyebrow"><span /> From first command to defensible baseline</p><h1>Linux, without<br /><em>the mystery.</em></h1><p>Learn what the system is doing, how permissions really work, where evidence lives and how to make a host smaller, safer, observable and recoverable.</p><div><a href="#permissions">Open permission lab ↓</a><Link href="/learn/system-hardening-baselines-and-verification">Read hardening guide →</Link></div></div><aside><strong>rwx</strong><span>4 · 2 · 1</span><small>read · write · execute</small></aside></section>

    <section className="linux-route"><header><span>Recommended route</span><h2>Build the operating model in order.</h2><p>Linux is not a bag of commands. Learn the filesystem and identity model first, then connect processes, services, networks, logs and secure administration.</p></header><div>{route.map((item) => <Link href={item.href} key={item.n}><span>{item.n}</span><strong>{item.title}</strong><p>{item.detail}</p><i>→</i></Link>)}</div></section>

    <section className="linux-section filesystem-section" id="filesystem"><header><span>01 · Filesystem</span><h2>One tree, many jobs.</h2><p>An absolute path begins at <code>/</code>. A relative path begins from the current working directory. Directories organize names and access. Mounted filesystems can make different disks, network shares and virtual kernel views appear inside the same tree.</p></header><div className="filesystem-map">{filesystem.map((item) => <details key={item.path}><summary><code>{item.path}</code><strong>{item.name}</strong><i>＋</i></summary><div><p>{item.purpose}</p><small><b>Watch for</b>{item.caution}</small></div></details>)}</div></section>

    <section className="linux-section" id="permissions"><header><span>02 · Identity and authorization</span><h2>Read, write and execute are three separate decisions.</h2><p>Every ordinary permission set is evaluated for the file owner, the owning group and everyone else. Each group gets three bits: read is 4, write is 2 and execute is 1. Add only the capabilities that group needs.</p></header>
      <div className="permission-theory"><div><span>Files</span><p><b>Read</b> exposes contents. <b>Write</b> changes contents. <b>Execute</b> allows the file to run as a program when its format and interpreter permit it.</p></div><div><span>Directories</span><p><b>Read</b> lists names. <b>Write</b> creates or removes entries. <b>Execute</b> traverses the directory and reaches a known name. Directory meaning is why 644 works for a file but usually not for a browsable directory.</p></div></div>
      <div className="octal-table"><div><span>Value</span><span>Symbolic</span><span>Meaning</span></div>{octal.map(([value, symbolic, meaning]) => <div key={value}><strong>{value}</strong><code>{symbolic}</code><p>{meaning}</p></div>)}</div>
      <LinuxPermissionsLab />
    </section>

    <section className="linux-section"><header><span>03 · A concrete permission model</span><h2>One application tree, several trust levels.</h2><p>These modes are examples, not universal rules. Ownership, process identity, Access Control Lists, container boundaries and application behavior still matter.</p></header><div className="linux-tree-example"><div><code>/srv/app</code><span>root:app · 755</span><p>Application root is readable and traversable, but ordinary members cannot rewrite it.</p></div><div><code>/srv/app/public</code><span>root:app · 755</span><p>Public directory can be traversed. Ordinary published files inside may use 644.</p></div><div><code>/srv/app/config/secret.env</code><span>root:app · 640</span><p>Owner can change it, the application group can read it and everyone else has no access.</p></div><div><code>/srv/app/keys/private.key</code><span>app:app · 600</span><p>Only the owning service identity can read or replace the private key.</p></div><div><code>/srv/app/shared</code><span>root:app · 2770</span><p>The setgid bit helps new entries inherit the collaborative directory group.</p></div><div><code>/tmp</code><span>root:root · 1777</span><p>Everyone can create temporary files, while the sticky bit limits deletion of another user’s entries.</p></div></div></section>

    <section className="linux-section" id="operations"><header><span>04 · Operate with evidence</span><h2>Trace symptom to service, process, socket, dependency and log.</h2><p>A command is useful when it answers a question. Begin with read-only inspection, record the time and target, form a hypothesis, make the smallest controlled change and verify the user-facing result.</p></header><div className="linux-command-grid">{commands.map((group) => <article key={group.area}><span>{group.area}</span><p>{group.intent}</p><div>{group.examples.map((command) => <code key={command}>{command}</code>)}</div></article>)}</div><div className="linux-request-flow"><div><span>01</span><b>Client request</b></div><i>→</i><div><span>02</span><b>Address and route</b></div><i>→</i><div><span>03</span><b>Listening socket</b></div><i>→</i><div><span>04</span><b>Service process</b></div><i>→</i><div><span>05</span><b>File, data or dependency</b></div><i>→</i><div><span>06</span><b>Journal and response</b></div></div></section>

    <section className="linux-section hardening-section" id="hardening"><header><span>05 · System hardening</span><h2>Reduce exposure, preserve operation and verify the result.</h2><p>Hardening is a controlled lifecycle. A long checklist is not evidence that the host is safe. Start from purpose, remove unnecessary capability, constrain what remains, observe it, recover it and detect drift.</p></header><div className="hardening-layers">{hardening.map(([title, detail], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><div className="hardening-chain"><div>Asset and purpose</div><i>→</i><div>Approved baseline</div><i>→</i><div>Build and configure</div><i>→</i><div>Verify</div><i>→</i><div>Operate and detect drift</div><i>→</i><div>Correct or approve exception</div><i>↩</i></div></section>

    <section className="linux-section safe-practice"><header><span>06 · Safe practice</span><h2>Make the next action reversible and reviewable.</h2></header><div><article><b>Before a change</b><ul><li>Confirm the exact host, environment, path and service.</li><li>Inspect ownership, current value and dependencies.</li><li>Know the expected result, rollback and stop condition.</li><li>Preserve configuration and required evidence.</li></ul></article><article><b>After a change</b><ul><li>Validate syntax before restart where the service supports it.</li><li>Check process, socket, logs and user-facing behavior.</li><li>Confirm security did not create an unintended outage.</li><li>Record the reason, owner, evidence and any exception expiry.</li></ul></article></div><blockquote><b>Good Linux judgment</b><p>Do not memorize a command and search for somewhere to run it. Start with the question, inspect the system, choose the least harmful action, and verify the complete service afterward.</p></blockquote></section>
  </main>;
}
