'use client';

import { useState } from 'react';

const implementationClasses = [
  { id: 'administrative', label: 'Administrative', alias: 'Managerial or organizational', definition: 'Governance, policy, process and people measures that direct, authorize, review or constrain work.', examples: ['Policy', 'Approval workflow', 'Segregation of duties', 'Training', 'Independent review'] },
  { id: 'technical', label: 'Technical', alias: 'Logical', definition: 'Controls enforced or supported by hardware, software, identity, configuration, cryptography or automated logic.', examples: ['Multi-factor authentication', 'Firewall rule', 'Encryption', 'Endpoint policy', 'Automated alert'] },
  { id: 'physical', label: 'Physical', alias: 'Facilities and equipment', definition: 'Measures that protect people, facilities, equipment and physical access to systems or information.', examples: ['Lock', 'Barrier', 'Guard', 'Door alarm', 'Environmental protection'] },
] as const;

const controlFunctions = [
  { id: 'directive', label: 'Directive', timing: 'Before and throughout activity', question: 'What behavior or outcome is required?', definition: 'States required or prohibited behavior and establishes the authority, responsibility or method people should follow.', examples: { administrative: 'A privileged-access standard requires named accounts, approval and time-limited access.', technical: 'A managed profile distributes the required endpoint settings.', physical: 'Restricted-area signs state authorization and escort requirements.' }, evidence: ['Approved policy or standard', 'Assigned owner', 'Version and effective date', 'Communication record'] },
  { id: 'deterrent', label: 'Deterrent', timing: 'Before activity', question: 'What makes misuse less attractive?', definition: 'Discourages unwanted behavior by increasing the perceived likelihood of detection, cost or consequence.', examples: { administrative: 'A published disciplinary process explains consequences for deliberate misuse.', technical: 'A login notice states that authorized activity is monitored and attributable.', physical: 'Visible guards, lighting and surveillance notices discourage unauthorized entry.' }, evidence: ['Notice or communication', 'Sanctions process', 'Monitoring visibility', 'Physical inspection'] },
  { id: 'preventive', label: 'Preventive', timing: 'Before or at the attempted event', question: 'What stops or reduces the chance of the event?', definition: 'Blocks an unwanted action or reduces the likelihood that it can occur.', examples: { administrative: 'A second approver is required before a high-value payment is released.', technical: 'Multi-factor authentication, least privilege and segmentation block unauthorized paths.', physical: 'Locks, badge-controlled doors and vehicle barriers restrict entry.' }, evidence: ['Approval record', 'Configuration export', 'Access decision log', 'Physical access record'] },
  { id: 'compensating', label: 'Compensating', timing: 'When the preferred control is infeasible', question: 'What alternative addresses the same objective?', definition: 'Provides an alternative safeguard when the preferred control cannot be implemented, with an explicit comparison of the remaining risk.', examples: { administrative: 'An independent daily reconciliation offsets missing segregation of duties in a legacy process.', technical: 'A legacy application is placed behind an authentication gateway, segmented and closely monitored.', physical: 'A staffed guard and visitor escort temporarily replace an unavailable badge reader.' }, evidence: ['Objective comparison', 'Risk assessment', 'Approver', 'Expiry or review date', 'Monitoring results'] },
  { id: 'detective', label: 'Detective', timing: 'During or after activity', question: 'How will we know the event or control failure occurred?', definition: 'Identifies an unwanted event, abnormal condition or failure of another control so investigation can begin.', examples: { administrative: 'An independent reconciliation identifies unauthorized or incomplete transactions.', technical: 'A security analytics rule alerts on impossible travel followed by sensitive-data access.', physical: 'A door alarm or reviewed camera recording identifies unauthorized entry.' }, evidence: ['Alert or exception', 'Review record', 'Investigation case', 'Escalation timeline'] },
  { id: 'corrective', label: 'Corrective', timing: 'After a problem is identified', question: 'What repairs the condition and reduces recurrence?', definition: 'Corrects an unacceptable condition, addresses its cause or changes the system so the problem is less likely to recur.', examples: { administrative: 'A failed access-review process is redesigned and overdue decisions are completed.', technical: 'A vulnerable component is patched and the unsafe configuration is replaced.', physical: 'A compromised lock is replaced and affected badges are reissued.' }, evidence: ['Root-cause analysis', 'Remediation plan', 'Change record', 'Validation evidence'] },
  { id: 'recovery', label: 'Recovery', timing: 'After disruption', question: 'How is an acceptable service restored and verified?', definition: 'Restores service, data, facilities or operational capability and verifies that the recovered state is trustworthy.', examples: { administrative: 'A continuity plan activates alternate staff, priorities and controlled manual procedures.', technical: 'A clean backup is restored, reconciled and security-validated before service resumes.', physical: 'Operations move to an alternate site while damaged equipment is restored.' }, evidence: ['Recovery invocation', 'Restore or failover result', 'Integrity checks', 'Reconciliation', 'Return-to-service approval'] },
] as const;

const matrix = [
  { type: 'Administrative', preventive: 'Approval, training, segregation of duties', detective: 'Access review, reconciliation, supervisory review', corrective: 'Procedure redesign, action plan, retraining' },
  { type: 'Technical', preventive: 'Firewall, strong authentication, encryption', detective: 'Security analytics, intrusion detection, audit logs', corrective: 'Patch, quarantine, configuration repair' },
  { type: 'Physical', preventive: 'Fences, locks, gates, barriers', detective: 'Cameras, guards, door alarms', corrective: 'Repair damage, replace locks, reissue badges' },
];

export default function ControlFunctionExplorer({ compact = false }: { compact?: boolean }) {
  const [selectedId, setSelectedId] = useState('preventive');
  const selected = controlFunctions.find((item) => item.id === selectedId) ?? controlFunctions[0];
  return <section className={`control-explorer ${compact ? 'compact' : ''}`} id="control-functions">
    <header><span>Seven control functions</span><h2>Purpose, implementation and evidence are different dimensions.</h2><p>A single control can serve more than one function. Administrative, technical and physical describe how it is implemented, while the seven functions explain the job it performs.</p></header>
    <div className="control-function-tabs" role="tablist" aria-label="Security control functions">{controlFunctions.map((item, index) => <button type="button" role="tab" aria-selected={selected.id === item.id} className={selected.id === item.id ? 'active' : ''} onClick={() => setSelectedId(item.id)} key={item.id}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item.label}</strong><small>{item.timing}</small></button>)}</div>
    <article className="control-function-detail" role="tabpanel">
      <div><span>{selected.timing}</span><h3>{selected.label} control</h3><strong>{selected.question}</strong><p>{selected.definition}</p></div>
      <div className="control-example-grid">{implementationClasses.map((item) => <section key={item.id}><span>{item.label}</span><p>{selected.examples[item.id]}</p></section>)}</div>
      <aside><span>Evidence to inspect</span><div>{selected.evidence.map((item) => <b key={item}>{item}</b>)}</div></aside>
    </article>
    {!compact && <>
      <div className="implementation-class-grid">{implementationClasses.map((item) => <article key={item.id}><span>{item.label}</span><small>{item.alias}</small><p>{item.definition}</p><div>{item.examples.map((example) => <b key={example}>{example}</b>)}</div></article>)}</div>
      <div className="control-matrix"><header><span>Control-function matrix</span><h3>Classify by implementation and purpose.</h3><p>This visual is a memory aid, not a rule that every control fits only one box.</p></header><div className="control-matrix-table"><div className="matrix-corner">Implementation</div><strong>Preventive</strong><strong>Detective</strong><strong>Corrective</strong>{matrix.map((row) => <div className="matrix-row" key={row.type}><b>{row.type}</b><p>{row.preventive}</p><p>{row.detective}</p><p>{row.corrective}</p></div>)}</div></div>
      <p className="taxonomy-note"><strong>Taxonomy note</strong> Compensating describes a relationship to a preferred control. Containment is often taught as an incident-response action. Corrective controls repair a condition or its cause; recovery controls restore acceptable service.</p>
    </>}
  </section>;
}
