export type FrameworkAuthority =
  | 'Law or regulation'
  | 'Directive'
  | 'Certifiable standard'
  | 'Guidance standard'
  | 'Framework'
  | 'Control catalog'
  | 'Assurance criteria'
  | 'Attestation examination'
  | 'Knowledge base'
  | 'Testing guide'
  | 'Industry standard';

export type FrameworkTimelineItem = {
  date: string;
  status: 'In force' | 'Scheduled' | 'Current' | 'Transition';
  detail: string;
};

export type FrameworkRecord = {
  slug: string;
  shortName: string;
  fullName: string;
  aliases?: string[];
  authorityType: FrameworkAuthority;
  owner: string;
  jurisdiction: string;
  domains: string[];
  currentEdition: string;
  status: string;
  statusDetail: string;
  applicableTo: string;
  purpose: string;
  structure: string[];
  usefulFor: string[];
  evidence: string[];
  notEquivalentTo: string[];
  certificationOrAssurance: string;
  officialUrl: string;
  complementary: string[];
  timeline?: FrameworkTimelineItem[];
  checkedAt: '2026-08-31';
};

const checkedAt = '2026-08-31' as const;

export const frameworkCatalog: FrameworkRecord[] = [
  {
    slug: 'gdpr', shortName: 'GDPR', fullName: 'General Data Protection Regulation', aliases: ['Regulation (EU) 2016/679'], authorityType: 'Law or regulation', owner: 'European Union', jurisdiction: 'European Economic Area and relevant extraterritorial processing', domains: ['Privacy', 'Data', 'Governance'], currentEdition: 'Regulation (EU) 2016/679', status: 'Applicable', statusDetail: 'Applicable since 25 May 2018 and incorporated into the European Economic Area Agreement. Applicability depends on territorial scope, establishment, offering goods or services, monitoring behavior, and the processing role. DGPR is a common misspelling, not an official abbreviation.', applicableTo: 'Controllers and processors that fall within the Regulation’s material and territorial scope. The role and processing context matter more than the location of a server alone.', purpose: 'Protect natural persons in relation to personal-data processing and make organizations accountable for lawful, fair, transparent, secure and rights-respecting processing.', structure: ['Principles and lawful bases', 'Rights of data subjects', 'Controller and processor duties', 'Security and breach notification', 'International transfers', 'Supervision, remedies and penalties'], usefulFor: ['Data inventories and Records of Processing Activities', 'Privacy notices, rights workflows and retention', 'Data Protection Impact Assessments', 'Processor contracting and transfer governance'], evidence: ['Records of Processing Activities', 'Lawful-basis assessment', 'Data Protection Impact Assessment', 'Processor agreement and transfer assessment', 'Rights-request and breach decision logs'], notEquivalentTo: ['A privacy certification', 'A universal ban on processing personal data', 'A generic cybersecurity checklist', 'Proof that every processing activity is lawful'], certificationOrAssurance: 'Compliance is a legal responsibility. Approved certification mechanisms may support accountability, but they do not replace legal obligations or supervisory authority.', officialUrl: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj', complementary: ['iso-iec-27701', 'nist-privacy-framework', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'india-dpdp-act-rules', shortName: 'India DPDP Act and Rules', fullName: 'Digital Personal Data Protection Act, 2023 and Digital Personal Data Protection Rules, 2025', aliases: ['DPDPA', 'Digital Personal Data Protection Act'], authorityType: 'Law or regulation', owner: 'Government of India, Ministry of Electronics and Information Technology', jurisdiction: 'India, including defined processing outside India connected with offering goods or services in India', domains: ['Privacy', 'Data', 'Governance', 'India'], currentEdition: '2023 Act with 2025 Rules and phased commencement', status: 'Phased commencement', statusDetail: 'Only designated provisions are in force on 30 August 2026. Most operational duties are scheduled for 13 May 2027, with an intermediate phase on 13 November 2026.', applicableTo: 'Digital personal data processed within scope, with duties allocated to Data Fiduciaries and additional duties for Significant Data Fiduciaries. Exact commencement, exclusions and role definitions must be checked.', purpose: 'Create a rights and accountability regime for digital personal-data processing in India, including notice, consent and specified legitimate uses, safeguards, breach response, individual rights and regulatory governance.', structure: ['Scope and definitions', 'Grounds and duties for processing', 'Data Principal rights and duties', 'Children and Significant Data Fiduciaries', 'Data Protection Board and enforcement', 'Rules governing notices, consent, safeguards, breaches and transfers'], usefulFor: ['India privacy roadmaps', 'Consent and notice redesign', 'Data-retention and erasure decisions', 'Breach-response and Data Principal workflows'], evidence: ['Processing and role inventory', 'Versioned notice and consent records', 'Reasonable-security-safeguard record', 'Breach assessment and notification record', 'Data Principal request and grievance log'], notEquivalentTo: ['The GDPR under a different name', 'A fully commenced regime on 30 August 2026', 'A certification standard', 'Permission to ignore sector-specific obligations'], certificationOrAssurance: 'It is law, not a certification. Organizations need legal interpretation, operational evidence and ongoing monitoring of commencement notifications.', officialUrl: 'https://www.meity.gov.in/writereaddata/files/Digital%20Personal%20Data%20Protection%20Act%202023.pdf', complementary: ['iso-iec-27701', 'nist-privacy-framework', 'iso-iec-27001'], timeline: [
      { date: '13 Nov 2025', status: 'In force', detail: 'Selected preliminary, Data Protection Board, governance and rulemaking provisions, plus Rules 1, 2 and 17 to 21. The penalty provision in section 33 is scheduled for the later 18-month phase.' },
      { date: '13 Nov 2026', status: 'Scheduled', detail: 'Act section 6(9), section 27(1)(d) and Rule 4 are scheduled to commence.' },
      { date: '13 May 2027', status: 'Scheduled', detail: 'Most operational processing, duty, rights and rules provisions are scheduled to commence.' },
    ], checkedAt,
  },
  {
    slug: 'hipaa-rule-suite', shortName: 'HIPAA Rule Suite', fullName: 'Health Insurance Portability and Accountability Act Privacy, Security and Breach Notification Rules', aliases: ['HIPAA'], authorityType: 'Law or regulation', owner: 'United States Department of Health and Human Services', jurisdiction: 'United States', domains: ['Healthcare', 'Privacy', 'Security'], currentEdition: 'Current codified HIPAA Rules', status: 'Current rule in force', statusDetail: 'The current Security Rule remains in effect. A proposal to strengthen it is not a final rule and must not be presented as current law. HIPPA is a common misspelling, not an official abbreviation.', applicableTo: 'HIPAA covered entities and business associates, with duties that depend on the role and use or disclosure. It does not cover every organization that happens to process health-related information.', purpose: 'Protect health information, define permitted uses and disclosures, require safeguards for electronic protected health information, and govern breach notification.', structure: ['Privacy Rule', 'Security Rule administrative safeguards', 'Security Rule physical safeguards', 'Security Rule technical safeguards', 'Breach Notification Rule', 'Enforcement and role relationships'], usefulFor: ['Healthcare data-flow mapping', 'Security risk analysis', 'Business Associate Agreements', 'Minimum-necessary and access-control workflows'], evidence: ['Security risk analysis', 'Risk-management plan', 'Business Associate Agreement', 'Access and audit-control records', 'Breach risk assessment and notification decision'], notEquivalentTo: ['A law covering every health application', 'A cybersecurity product standard', 'Automatic compliance with other privacy laws', 'The proposed Security Rule being final'], certificationOrAssurance: 'The United States Department of Health and Human Services does not recognize a universal official HIPAA certification. Third-party assessments can support assurance but do not bind regulators.', officialUrl: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html', complementary: ['nist-csf', 'nist-sp-800-53', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'eu-ai-act', shortName: 'EU AI Act', fullName: 'European Union Artificial Intelligence Act', aliases: ['AI Act', 'Regulation (EU) 2024/1689'], authorityType: 'Law or regulation', owner: 'European Union', jurisdiction: 'European Union with defined extraterritorial reach', domains: ['Artificial intelligence', 'Governance', 'Product'], currentEdition: 'Regulation (EU) 2024/1689 with staged application', status: 'Staged application', statusDetail: 'Entered into force on 1 August 2024 and became broadly applicable on 2 August 2026, subject to staged exceptions. High-risk systems listed in Annex III and selected sensitive-use contexts move to 2 December 2027, while product-embedded Annex I high-risk systems move to 2 August 2028.', applicableTo: 'Providers, deployers, importers, distributors and other actors where the Act’s scope applies. Duties depend on the system category, role and value-chain position.', purpose: 'Set harmonized, risk-based requirements for artificial-intelligence systems, including prohibited practices, high-risk controls, transparency and general-purpose AI duties.', structure: ['Prohibited practices', 'High-risk system classification and duties', 'Transparency obligations', 'General-purpose AI model duties', 'Governance, conformity and post-market monitoring', 'Enforcement and staged application'], usefulFor: ['AI system inventory and classification', 'Provider and deployer role mapping', 'Technical documentation and human oversight', 'Post-market monitoring and incident governance'], evidence: ['AI system register and classification rationale', 'Risk-management and data-governance file', 'Technical documentation and instructions for use', 'Human-oversight design and competence record', 'Monitoring, logging and incident record'], notEquivalentTo: ['A general AI ethics code', 'A guarantee that a model is accurate', 'A single checklist for every AI use', 'ISO/IEC 42001 certification'], certificationOrAssurance: 'Selected systems may require conformity assessment. Compliance depends on legal role, risk class, applicable standards and ongoing operation, not a one-time label.', officialUrl: 'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai', complementary: ['nist-ai-rmf', 'iso-iec-42001', 'iso-iec-23894'], timeline: [
      { date: '2 Aug 2026', status: 'In force', detail: 'Most provisions apply, subject to the Act\'s staged exceptions and transitions.' },
      { date: '2 Dec 2027', status: 'Scheduled', detail: 'High-risk obligations for Annex III and selected sensitive-use systems move to this date under the current timeline.' },
      { date: '2 Aug 2028', status: 'Scheduled', detail: 'High-risk obligations for product-embedded systems covered through Annex I move to this date.' },
    ], checkedAt,
  },
  {
    slug: 'eu-dora', shortName: 'EU DORA', fullName: 'European Union Digital Operational Resilience Act', aliases: ['DORA regulation', 'Regulation (EU) 2022/2554'], authorityType: 'Law or regulation', owner: 'European Union', jurisdiction: 'European Union financial sector', domains: ['Financial services', 'Resilience', 'Third-party risk'], currentEdition: 'Regulation (EU) 2022/2554', status: 'Applicable', statusDetail: 'Applicable since 17 January 2025, supported by regulatory and implementing technical standards.', applicableTo: 'Defined financial entities and relevant Information and Communication Technology third-party arrangements in the European Union. Scope and proportionality must be assessed by entity type.', purpose: 'Strengthen Information and Communication Technology risk management, incident handling, resilience testing and oversight of critical technology providers across financial services.', structure: ['ICT risk management', 'Incident classification and reporting', 'Digital operational resilience testing', 'ICT third-party risk', 'Information sharing', 'Oversight of critical providers'], usefulFor: ['Resilience governance and service mapping', 'Technology incident processes', 'Threat-led penetration testing', 'Contract and concentration-risk reviews'], evidence: ['ICT risk-management framework', 'Critical-service and dependency map', 'Incident classification and report', 'Resilience-test plan and remediation record', 'Third-party register and contract assessment'], notEquivalentTo: ['Google DevOps Research and Assessment', 'A cybersecurity certification', 'A replacement for prudential supervision', 'A requirement applying to every company'], certificationOrAssurance: 'DORA is regulation. Supervisory review and evidence matter; there is no universal DORA certification that removes accountability.', officialUrl: 'https://eur-lex.europa.eu/legal-content/EN/LSU/?uri=CELEX%3A32022R2554', complementary: ['iso-22301', 'cobit-2019', 'nist-csf'], checkedAt,
  },
  {
    slug: 'nis2', shortName: 'NIS2', fullName: 'Directive on measures for a high common level of cybersecurity across the Union', aliases: ['Directive (EU) 2022/2555'], authorityType: 'Directive', owner: 'European Union', jurisdiction: 'European Union through national transposition', domains: ['Cybersecurity', 'Critical infrastructure', 'Governance'], currentEdition: 'Directive (EU) 2022/2555', status: 'National transposition varies', statusDetail: 'Member States were required to transpose the Directive by 17 October 2024. The applicable national law, authority, scope and enforcement position must be checked.', applicableTo: 'Essential and important entities in defined sectors, subject to size, sector, national rules and specific inclusions.', purpose: 'Raise cybersecurity risk-management and incident-reporting capability across important and essential sectors in the European Union.', structure: ['Scope and entity classification', 'Governance accountability', 'Risk-management measures', 'Incident reporting', 'Supervision and enforcement', 'National and European cooperation'], usefulFor: ['Entity scope assessment', 'Management accountability', 'Supply-chain security', 'Major-incident notification workflows'], evidence: ['Scope and entity classification', 'Risk-treatment and policy records', 'Supply-chain security assessment', 'Incident decision timeline', 'Management training and approval records'], notEquivalentTo: ['One directly identical law in every Member State', 'A certification framework', 'The original NIS Directive', 'A cybersecurity product baseline'], certificationOrAssurance: 'It is a directive implemented through national law. Certificates may support evidence but do not prove compliance with national obligations.', officialUrl: 'https://digital-strategy.ec.europa.eu/en/policies/nis2-directive', complementary: ['nist-csf', 'iso-iec-27001', 'iec-62443'], checkedAt,
  },
  {
    slug: 'nist-csf', shortName: 'NIST CSF 2.0', fullName: 'NIST Cybersecurity Framework 2.0', aliases: ['Cybersecurity Framework'], authorityType: 'Framework', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'Global voluntary use unless adopted by contract, policy or authority', domains: ['Cybersecurity', 'Governance', 'Risk'], currentEdition: 'Version 2.0, 2024', status: 'Current', statusDetail: 'CSF 2.0 added Govern as a core function and is designed for organizations of any size or sector.', applicableTo: 'Organizations that need a common language for cybersecurity outcomes, current and target profiles, priorities and communication.', purpose: 'Organize cybersecurity outcomes into a flexible structure that connects governance, risk decisions, protection, detection, response and recovery.', structure: ['Govern', 'Identify', 'Protect', 'Detect', 'Respond', 'Recover'], usefulFor: ['Current and target profiles', 'Executive communication', 'Gap and priority discussions', 'Crosswalks to controls and obligations'], evidence: ['Current-state profile', 'Target-state profile', 'Gap and priority register', 'Implementation tier rationale', 'Mapped evidence and accountable owners'], notEquivalentTo: ['A prescriptive control catalog', 'A certification', 'A maturity score by itself', 'Proof that all cyber risk is controlled'], certificationOrAssurance: 'NIST does not certify organizations against the CSF. Independent assurance can assess a defined implementation, but claims need scope and evidence.', officialUrl: 'https://www.nist.gov/cyberframework', complementary: ['nist-sp-800-53', 'iso-iec-27001', 'cis-controls'], checkedAt,
  },
  {
    slug: 'nist-rmf', shortName: 'NIST RMF', fullName: 'NIST Risk Management Framework', aliases: ['NIST SP 800-37 Revision 2'], authorityType: 'Framework', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'United States federal origin with broader use', domains: ['Risk', 'Systems', 'Authorization'], currentEdition: 'NIST SP 800-37 Revision 2', status: 'Current', statusDetail: 'The Risk Management Framework integrates security and privacy risk into system development, authorization and continuous monitoring.', applicableTo: 'System owners, authorizing officials, control providers, assessors and governance bodies that need a traceable risk-authorization process.', purpose: 'Provide a lifecycle for preparing, categorizing, selecting, implementing, assessing, authorizing and continuously monitoring system controls.', structure: ['Prepare', 'Categorize', 'Select', 'Implement', 'Assess', 'Authorize', 'Monitor'], usefulFor: ['System authorization', 'Control tailoring', 'Risk acceptance', 'Continuous monitoring'], evidence: ['System security and privacy plan', 'Security categorization', 'Control implementation record', 'Assessment report', 'Authorization decision and Plan of Action and Milestones'], notEquivalentTo: ['The NIST Cybersecurity Framework', 'A control catalog', 'Automatic Authorization to Operate', 'A one-time compliance exercise'], certificationOrAssurance: 'RMF produces an accountable authorization decision rather than a generic certificate. The authorizing official accepts or rejects defined residual risk.', officialUrl: 'https://csrc.nist.gov/pubs/sp/800/37/r2/final', complementary: ['nist-sp-800-53', 'nist-csf', 'nist-privacy-framework'], checkedAt,
  },
  {
    slug: 'nist-sp-800-53', shortName: 'NIST SP 800-53', fullName: 'Security and Privacy Controls for Information Systems and Organizations', aliases: ['800-53'], authorityType: 'Control catalog', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'United States federal origin with broad global use', domains: ['Security controls', 'Privacy controls', 'Assurance'], currentEdition: 'Revision 5, control release 5.2.0, August 2025', status: 'Current', statusDetail: 'A broad catalog of security and privacy controls with baselines and tailoring supported by companion publications.', applicableTo: 'Organizations and systems that need structured control selection, specification, assessment and mapping.', purpose: 'Provide a technology-neutral catalog of security and privacy controls that can be selected and tailored to risk and requirements.', structure: ['Control families', 'Control statements', 'Discussion and related controls', 'Control enhancements', 'Baselines and overlays through companion guidance', 'Assessment through companion guidance'], usefulFor: ['Control libraries', 'System security plans', 'Supplier requirements', 'Assessment procedures and crosswalks'], evidence: ['Selected and tailored control baseline', 'Control implementation statement', 'Common-control inheritance record', 'Assessment procedure and result', 'Remediation and continuous-monitoring record'], notEquivalentTo: ['A ready-made baseline for every system', 'A certification', 'The NIST CSF', 'Proof that a control operates effectively'], certificationOrAssurance: 'Organizations may assess against selected controls, but NIST does not issue a general SP 800-53 certificate. Scope, tailoring and operating evidence are essential.', officialUrl: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', complementary: ['nist-rmf', 'nist-csf', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'nist-ssdf', shortName: 'NIST SSDF', fullName: 'Secure Software Development Framework', aliases: ['NIST SP 800-218'], authorityType: 'Framework', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'Global voluntary use unless required', domains: ['Software', 'Secure development', 'Supply chain'], currentEdition: 'Version 1.1, NIST SP 800-218', status: 'Current', statusDetail: 'A set of outcome-oriented secure development practices designed to integrate into an existing Software Development Life Cycle.', applicableTo: 'Software producers, acquirers, development teams and supply-chain governance functions.', purpose: 'Reduce the number and impact of software vulnerabilities by preparing the organization, protecting software, producing well-secured software and responding to vulnerabilities.', structure: ['Prepare the Organization', 'Protect the Software', 'Produce Well-Secured Software', 'Respond to Vulnerabilities'], usefulFor: ['Secure delivery requirements', 'Pipeline and repository controls', 'Supplier attestation', 'Vulnerability-response improvement'], evidence: ['Secure development policy', 'Threat model and design review', 'Protected repository and build record', 'Security test and release decision', 'Vulnerability disclosure and remediation record'], notEquivalentTo: ['A replacement delivery method', 'A product penetration test', 'A certification scheme', 'A complete software-quality model'], certificationOrAssurance: 'SSDF is guidance. Contracts and assurance programs may ask for evidence of practice, but NIST does not issue SSDF certification.', officialUrl: 'https://csrc.nist.gov/pubs/sp/800/218/final', complementary: ['owasp-samm', 'owasp-asvs', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'nist-privacy-framework', shortName: 'NIST Privacy Framework', fullName: 'NIST Privacy Framework: A Tool for Improving Privacy through Enterprise Risk Management', aliases: ['NIST PF'], authorityType: 'Framework', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'Global voluntary use', domains: ['Privacy', 'Data', 'Risk'], currentEdition: 'Version 1.0 final', status: 'Current final is 1.0', statusDetail: 'Version 1.1 remains an Initial Public Draft on the checked date and should not be presented as final.', applicableTo: 'Organizations seeking a risk-based operating model for privacy, regardless of sector or legal regime.', purpose: 'Help organizations identify and manage privacy risk through reusable functions, profiles and implementation tiers.', structure: ['Identify-P', 'Govern-P', 'Control-P', 'Communicate-P', 'Protect-P'], usefulFor: ['Privacy current and target profiles', 'Privacy engineering priorities', 'Risk communication', 'Mapping legal obligations to practices'], evidence: ['Privacy profile', 'Data-processing map', 'Privacy risk assessment', 'Control and communication design', 'Review and improvement record'], notEquivalentTo: ['Privacy law', 'GDPR compliance', 'A certification', 'The draft version being final'], certificationOrAssurance: 'Voluntary framework with no NIST certification. It can organize evidence used for legal, audit or customer assurance.', officialUrl: 'https://www.nist.gov/privacy-framework', complementary: ['gdpr', 'india-dpdp-act-rules', 'iso-iec-27701'], checkedAt,
  },
  {
    slug: 'nist-ai-rmf', shortName: 'NIST AI RMF', fullName: 'NIST Artificial Intelligence Risk Management Framework', aliases: ['AI RMF 1.0'], authorityType: 'Framework', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'Global voluntary use', domains: ['Artificial intelligence', 'Risk', 'Governance'], currentEdition: 'Version 1.0 with Generative AI Profile NIST AI 600-1', status: 'Current with revision work underway', statusDetail: 'Version 1.0 remains the current framework while NIST revision activity continues.', applicableTo: 'Organizations designing, developing, deploying, evaluating, acquiring or governing artificial-intelligence systems.', purpose: 'Provide a voluntary process for governing, mapping, measuring and managing risks to trustworthy and responsible artificial intelligence.', structure: ['Govern', 'Map', 'Measure', 'Manage'], usefulFor: ['AI use-case intake', 'Risk and impact assessment', 'Evaluation planning', 'Monitoring and incident response'], evidence: ['AI inventory and owner', 'Context and impact map', 'Test, Evaluation, Verification and Validation plan', 'Risk-treatment decision', 'Monitoring, feedback and incident record'], notEquivalentTo: ['AI law', 'A model safety guarantee', 'A certification', 'A fixed list of model tests'], certificationOrAssurance: 'NIST does not issue AI RMF certification. Assurance claims need a defined system, context, evaluation method and evidence.', officialUrl: 'https://www.nist.gov/itl/ai-risk-management-framework', complementary: ['iso-iec-42001', 'iso-iec-23894', 'eu-ai-act'], checkedAt,
  },
  {
    slug: 'nist-digital-identity', shortName: 'NIST Digital Identity Guidelines', fullName: 'NIST Special Publication 800-63 Revision 4', aliases: ['NIST SP 800-63-4'], authorityType: 'Guidance standard', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'United States federal origin with broader use', domains: ['Identity', 'Authentication', 'Federation'], currentEdition: 'Revision 4, July 2025', status: 'Current', statusDetail: 'The suite covers identity proofing, authentication and federation using separate assurance dimensions.', applicableTo: 'Digital services selecting identity, authenticator and federation assurance based on risks and user needs.', purpose: 'Provide risk-based guidance for identity proofing, authenticators, lifecycle management and federation.', structure: ['Identity Assurance Level', 'Authenticator Assurance Level', 'Federation Assurance Level', 'Enrollment and proofing', 'Authentication and authenticator management', 'Federation and assertions'], usefulFor: ['Authentication architecture', 'Phishing-resistant access', 'Identity proofing', 'Federation requirements'], evidence: ['Digital identity risk assessment', 'Selected assurance levels', 'Proofing and exception record', 'Authenticator lifecycle record', 'Federation configuration and monitoring evidence'], notEquivalentTo: ['A product certification', 'One universal assurance level', 'Authorization design', 'A requirement that passwords are always sufficient'], certificationOrAssurance: 'Assurance is demonstrated through implementation and assessment in context. NIST does not provide a universal product list that proves compliance.', officialUrl: 'https://pages.nist.gov/800-63-4/', complementary: ['nist-csf', 'zero-trust-architecture', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'nist-incident-response', shortName: 'NIST Incident Response', fullName: 'Incident Response Recommendations and Considerations for Cybersecurity Risk Management', aliases: ['NIST SP 800-61 Revision 3'], authorityType: 'Guidance standard', owner: 'United States National Institute of Standards and Technology', jurisdiction: 'Global guidance', domains: ['Incident response', 'Cybersecurity', 'Resilience'], currentEdition: 'NIST SP 800-61 Revision 3, April 2025', status: 'Current', statusDetail: 'Revision 3 supersedes Revision 2 and aligns incident response with Cybersecurity Framework 2.0.', applicableTo: 'Organizations building or improving incident-response capability and integrating it with risk management.', purpose: 'Embed incident preparation, detection, response and recovery into broader cybersecurity risk management and organizational learning.', structure: ['Govern and prepare', 'Detect and analyze', 'Respond', 'Recover', 'Improve across the lifecycle'], usefulFor: ['Incident policy and playbooks', 'Roles and escalation', 'Evidence preservation', 'Exercises and lessons learned'], evidence: ['Incident-response plan', 'Playbook and contact tree', 'Incident timeline and decision log', 'Evidence chain-of-custody record', 'After-action review and tracked improvements'], notEquivalentTo: ['A forensic procedure manual', 'A Security Operations Center product', 'A compliance certificate', 'Only a linear prepare-detect-contain-eradicate sequence'], certificationOrAssurance: 'Guidance can be assessed through exercises and operating evidence. NIST does not certify incident-response teams against it.', officialUrl: 'https://csrc.nist.gov/pubs/sp/800/61/r3/final', complementary: ['nist-csf', 'iso-22301', 'mitre-attack'], checkedAt,
  },
  {
    slug: 'iso-iec-27001', shortName: 'ISO/IEC 27001', fullName: 'Information security management systems: Requirements', aliases: ['ISO 27001'], authorityType: 'Certifiable standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Information security', 'Management systems', 'Governance'], currentEdition: 'ISO/IEC 27001:2022 with Amendment 1:2024', status: 'Current', statusDetail: 'Specifies requirements for an Information Security Management System and a risk-based Statement of Applicability.', applicableTo: 'Organizations of any size seeking a systematic, scoped Information Security Management System.', purpose: 'Establish, operate, monitor and continually improve a management system for information-security risks and objectives.', structure: ['Organizational context', 'Leadership', 'Planning', 'Support', 'Operation', 'Performance evaluation', 'Improvement', 'Annex A reference controls'], usefulFor: ['Information Security Management System design', 'Risk treatment and control selection', 'Internal audit and management review', 'External certification'], evidence: ['Scope and context record', 'Information-security risk assessment', 'Risk-treatment plan and Statement of Applicability', 'Internal-audit and management-review record', 'Corrective-action evidence'], notEquivalentTo: ['Proof of zero incidents', 'Certification of every service outside scope', 'ISO/IEC 27002', 'A prescriptive technology checklist'], certificationOrAssurance: 'An accredited certification body can certify a defined Information Security Management System scope. The certificate’s scope, issuing body and validity must be checked.', officialUrl: 'https://www.iso.org/standard/27001', complementary: ['iso-iec-27002', 'iso-iec-27005', 'nist-csf'], checkedAt,
  },
  {
    slug: 'iso-iec-27002', shortName: 'ISO/IEC 27002', fullName: 'Information security controls', aliases: ['ISO 27002'], authorityType: 'Guidance standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Information security controls', 'Governance'], currentEdition: 'ISO/IEC 27002:2022', status: 'Current', statusDetail: 'Provides implementation guidance for 93 organizational, people, physical and technological controls.', applicableTo: 'Organizations selecting, designing and explaining information-security controls, especially alongside ISO/IEC 27001.', purpose: 'Explain control purpose, attributes and implementation considerations in a reusable information-security reference set.', structure: ['Organizational controls', 'People controls', 'Physical controls', 'Technological controls', 'Control attributes and themes'], usefulFor: ['Control-library design', 'ISO/IEC 27001 risk treatment', 'Policy and standard development', 'Control-owner guidance'], evidence: ['Mapped control library', 'Control design statement', 'Operating procedure', 'Owner and review cadence', 'Operating and assessment evidence'], notEquivalentTo: ['A certifiable management-system standard', 'A mandatory universal baseline', 'ISO/IEC 27001 certification', 'Proof that a control is effective'], certificationOrAssurance: 'ISO/IEC 27002 is not independently certifiable. It supports control design and assessment within a defined context.', officialUrl: 'https://www.iso.org/standard/75652.html', complementary: ['iso-iec-27001', 'iso-iec-27005', 'nist-sp-800-53'], checkedAt,
  },
  {
    slug: 'iso-iec-27005', shortName: 'ISO/IEC 27005', fullName: 'Guidance on managing information security risks', aliases: ['ISO 27005'], authorityType: 'Guidance standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Risk', 'Information security'], currentEdition: 'ISO/IEC 27005:2022', status: 'Current', statusDetail: 'Provides guidance aligned with ISO/IEC 27001 and the principles of ISO 31000.', applicableTo: 'Organizations designing information-security risk criteria, assessment, treatment, monitoring and communication.', purpose: 'Translate risk-management principles into information-security risk decisions and repeatable evidence.', structure: ['Context and risk criteria', 'Risk identification', 'Risk analysis and evaluation', 'Risk treatment', 'Communication, monitoring and review'], usefulFor: ['Risk methodology', 'Scenario analysis', 'Risk registers', 'Treatment and acceptance decisions'], evidence: ['Risk criteria', 'Scenario and asset record', 'Analysis rationale', 'Treatment plan', 'Acceptance and review record'], notEquivalentTo: ['A certifiable standard', 'One mandatory risk formula', 'ISO 31000 itself', 'A replacement for management accountability'], certificationOrAssurance: 'Guidance is not independently certifiable. It can support assurance over a risk process and ISO/IEC 27001 implementation.', officialUrl: 'https://www.iso.org/standard/80585.html', complementary: ['iso-iec-27001', 'iso-31000', 'open-fair'], checkedAt,
  },
  {
    slug: 'iso-iec-27701', shortName: 'ISO/IEC 27701', fullName: 'Privacy information management systems: Requirements and guidance', aliases: ['ISO 27701'], authorityType: 'Certifiable standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Privacy', 'Management systems', 'Data'], currentEdition: 'ISO/IEC 27701:2025, edition 2', status: 'Current', statusDetail: 'The 2025 second edition is a standalone Privacy Information Management System standard that can integrate with ISO/IEC 27001.', applicableTo: 'Organizations acting as personally identifiable information controllers or processors that need a structured privacy management system.', purpose: 'Establish, operate and improve governance for privacy risks, responsibilities, controls and evidence.', structure: ['Privacy management-system requirements', 'Controller guidance', 'Processor guidance', 'Risk and control integration', 'Performance evaluation and improvement'], usefulFor: ['Privacy Information Management System design', 'Role and responsibility mapping', 'Privacy control evidence', 'Certification planning'], evidence: ['Privacy scope and role map', 'Privacy risk assessment', 'Controller and processor control record', 'Internal audit and management review', 'Corrective-action evidence'], notEquivalentTo: ['Compliance with every privacy law', 'The superseded 2019 edition', 'A data-security product standard', 'Proof that all processing is lawful'], certificationOrAssurance: 'A competent certification body can certify a defined Privacy Information Management System scope. Legal compliance remains the organization’s responsibility.', officialUrl: 'https://www.iso.org/standard/27701', complementary: ['iso-iec-27001', 'gdpr', 'nist-privacy-framework'], checkedAt,
  },
  {
    slug: 'iso-22301', shortName: 'ISO 22301', fullName: 'Security and resilience: Business continuity management systems: Requirements', authorityType: 'Certifiable standard', owner: 'International Organization for Standardization', jurisdiction: 'International', domains: ['Business continuity', 'Resilience'], currentEdition: 'ISO 22301:2019 with Amendment 1:2024', status: 'Current, revision underway', statusDetail: 'The 2019 edition plus 2024 amendment remains current while revision work proceeds.', applicableTo: 'Organizations establishing a Business Continuity Management System across defined products, services, locations or functions.', purpose: 'Provide a management system for understanding disruption impacts, designing continuity strategies, exercising capability and improving it.', structure: ['Context and leadership', 'Business impact analysis and risk assessment', 'Continuity strategies and solutions', 'Plans and procedures', 'Exercise and evaluation', 'Improvement'], usefulFor: ['Business impact analysis', 'Continuity strategies', 'Exercises', 'Recovery governance and certification'], evidence: ['Business impact analysis', 'Continuity strategy', 'Plan and contact record', 'Exercise report', 'Corrective action and management review'], notEquivalentTo: ['A disaster-recovery plan alone', 'Guaranteed uninterrupted service', 'A cybersecurity framework', 'A certificate covering every business activity'], certificationOrAssurance: 'A certification body can certify the defined Business Continuity Management System scope. Real capability still needs realistic exercising.', officialUrl: 'https://www.iso.org/standard/75106.html', complementary: ['nist-incident-response', 'eu-dora', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'iso-31000', shortName: 'ISO 31000', fullName: 'Risk management: Guidelines', authorityType: 'Guidance standard', owner: 'International Organization for Standardization', jurisdiction: 'International', domains: ['Enterprise risk', 'Governance'], currentEdition: 'ISO 31000:2018', status: 'Current, revision underway', statusDetail: 'The 2018 edition remains current and is explicitly guidance, not a certifiable management-system standard.', applicableTo: 'Any organization integrating risk into governance, strategy, planning, decisions and performance.', purpose: 'Provide principles, a framework and a process for managing uncertainty around objectives.', structure: ['Principles', 'Leadership and integration', 'Framework design and implementation', 'Risk process', 'Monitoring, review and improvement'], usefulFor: ['Enterprise risk methodology', 'Decision and escalation criteria', 'Risk communication', 'Integration across risk types'], evidence: ['Risk policy and criteria', 'Decision and ownership record', 'Risk assessment', 'Treatment and acceptance record', 'Monitoring and review evidence'], notEquivalentTo: ['A certifiable standard', 'A cybersecurity control catalog', 'One quantitative risk method', 'Proof that risk is low'], certificationOrAssurance: 'ISO states that ISO 31000 is not intended for certification. Reviews can assess alignment and operating effectiveness without claiming certification.', officialUrl: 'https://www.iso.org/standard/65694.html', complementary: ['iso-iec-27005', 'open-fair', 'coso-erm'], checkedAt,
  },
  {
    slug: 'iso-iec-42001', shortName: 'ISO/IEC 42001', fullName: 'Artificial intelligence management system: Requirements', aliases: ['ISO 42001'], authorityType: 'Certifiable standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Artificial intelligence', 'Management systems', 'Governance'], currentEdition: 'ISO/IEC 42001:2023', status: 'Current', statusDetail: 'The first international certifiable management-system standard focused on organizational governance of artificial intelligence.', applicableTo: 'Organizations that provide or use artificial-intelligence systems and want a scoped management system for policy, objectives, risk and continual improvement.', purpose: 'Create organizational governance for responsible development, provision or use of artificial intelligence across its lifecycle.', structure: ['Context and leadership', 'AI policy and objectives', 'Risk and impact assessment', 'Operational controls', 'Performance evaluation', 'Continual improvement'], usefulFor: ['AI governance operating model', 'AI inventory and objectives', 'Impact and risk controls', 'External certification'], evidence: ['AI management-system scope', 'AI policy and objectives', 'Impact and risk assessment', 'Operational control and supplier record', 'Internal audit, management review and corrective action'], notEquivalentTo: ['Certification that every model output is correct', 'EU AI Act compliance', 'A model benchmark', 'ISO/IEC 23894 guidance'], certificationOrAssurance: 'An accredited certification body can certify a defined Artificial Intelligence Management System scope. Product and legal claims still require separate evidence.', officialUrl: 'https://www.iso.org/standard/42001', complementary: ['nist-ai-rmf', 'iso-iec-23894', 'eu-ai-act'], checkedAt,
  },
  {
    slug: 'iso-iec-23894', shortName: 'ISO/IEC 23894', fullName: 'Artificial intelligence: Guidance on risk management', aliases: ['ISO 23894'], authorityType: 'Guidance standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Artificial intelligence', 'Risk'], currentEdition: 'ISO/IEC 23894:2023', status: 'Current', statusDetail: 'Guidance for integrating artificial-intelligence-specific considerations into risk-management activities.', applicableTo: 'Organizations developing, deploying, operating or governing artificial-intelligence products, services and systems.', purpose: 'Help organizations recognize uncertainty, data, model, human, societal, security and lifecycle risks specific to artificial intelligence.', structure: ['Principles and context', 'AI risk sources', 'Risk assessment', 'Risk treatment', 'Communication, monitoring and review'], usefulFor: ['AI risk methodology', 'Lifecycle risk workshops', 'Impact assessment', 'Monitoring design'], evidence: ['AI context and stakeholder map', 'Risk taxonomy and scenarios', 'Evaluation and treatment plan', 'Residual-risk decision', 'Monitoring and change record'], notEquivalentTo: ['A certifiable management-system standard', 'A legal compliance framework', 'A model card template', 'A guarantee of responsible AI'], certificationOrAssurance: 'Guidance is not independently certifiable. It can support ISO/IEC 42001 and other assurance work.', officialUrl: 'https://www.iso.org/standard/77304.html', complementary: ['iso-iec-42001', 'nist-ai-rmf', 'eu-ai-act'], checkedAt,
  },
  {
    slug: 'iso-iec-20000-1', shortName: 'ISO/IEC 20000-1', fullName: 'Information technology: Service management system requirements', aliases: ['ISO 20000'], authorityType: 'Certifiable standard', owner: 'International Organization for Standardization and International Electrotechnical Commission', jurisdiction: 'International', domains: ['Service management', 'Operations'], currentEdition: 'ISO/IEC 20000-1:2018 with Amendment 1:2024', status: 'Current', statusDetail: 'Specifies requirements for a Service Management System across planning, design, transition, delivery and improvement.', applicableTo: 'Service providers and organizations managing digital or technology-enabled services within a defined scope.', purpose: 'Establish consistent governance and lifecycle management for services, value, relationships, incidents, changes and improvement.', structure: ['Context and leadership', 'Planning and support', 'Service portfolio and relationships', 'Supply and demand', 'Service design, build and transition', 'Resolution, assurance and improvement'], usefulFor: ['Service-management operating model', 'Service level and supplier governance', 'Incident and change control', 'External certification'], evidence: ['Service Management System scope', 'Service catalog and agreements', 'Incident, problem and change records', 'Supplier review', 'Performance review and improvement evidence'], notEquivalentTo: ['ITIL', 'A help-desk standard', 'Proof that every service meets its target', 'Information-security certification'], certificationOrAssurance: 'A certification body can certify a defined Service Management System. ITIL guidance may support implementation but is not the certificate.', officialUrl: 'https://www.iso.org/standard/70636.html', complementary: ['itil-version-5', 'iso-iec-27001', 'iso-22301'], checkedAt,
  },
  {
    slug: 'cis-controls', shortName: 'CIS Controls', fullName: 'CIS Critical Security Controls', aliases: ['CIS Controls v8.1'], authorityType: 'Control catalog', owner: 'Center for Internet Security', jurisdiction: 'Global voluntary use', domains: ['Cybersecurity', 'Control baseline'], currentEdition: 'Version 8.1', status: 'Current', statusDetail: 'A prioritized set of safeguards organized with Implementation Groups to support progressive adoption.', applicableTo: 'Organizations seeking a practical security baseline scaled by resources, exposure and risk.', purpose: 'Prioritize foundational and measurable safeguards that reduce common attack paths and improve cyber hygiene.', structure: ['18 Controls', 'Safeguards', 'Implementation Groups 1 to 3', 'Asset, data, access, vulnerability, logging and response themes'], usefulFor: ['Baseline roadmaps', 'Smaller-organization prioritization', 'Control ownership', 'Crosswalks to other frameworks'], evidence: ['Selected Implementation Group rationale', 'Safeguard applicability record', 'Asset and software inventories', 'Operating evidence by safeguard', 'Exception and improvement register'], notEquivalentTo: ['A law', 'A universal certification', 'CIS Benchmarks', 'A complete enterprise risk framework'], certificationOrAssurance: 'CIS does not provide a universal organization certificate for Controls implementation. Assessments should state version, Implementation Group, scope and evidence.', officialUrl: 'https://www.cisecurity.org/controls/v8-1', complementary: ['cis-benchmarks', 'nist-csf', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'cis-benchmarks', shortName: 'CIS Benchmarks', fullName: 'Center for Internet Security Benchmarks', authorityType: 'Guidance standard', owner: 'Center for Internet Security', jurisdiction: 'Global voluntary use', domains: ['Configuration', 'Hardening', 'Cloud'], currentEdition: 'Living, technology-specific releases', status: 'Living catalog', statusDetail: 'Each operating system, cloud service, database or product benchmark has its own current version, level and publication status.', applicableTo: 'Owners and administrators of supported technologies who need tested secure-configuration recommendations.', purpose: 'Provide community-developed, technology-specific hardening recommendations that can be selected, tested and monitored.', structure: ['Technology-specific benchmark', 'Profile or level', 'Recommendation', 'Rationale and impact', 'Audit and remediation guidance'], usefulFor: ['Linux and server hardening', 'Cloud account baselines', 'Configuration compliance', 'Build-image standards'], evidence: ['Applicable benchmark and version', 'Tailoring and exception record', 'Configuration scan result', 'Change approval and test', 'Remediation and drift record'], notEquivalentTo: ['CIS Controls', 'A safe setting for every workload', 'A vulnerability scan', 'A reason to apply configuration without testing'], certificationOrAssurance: 'Technology images and tools may be assessed or certified through specific CIS programs. Organization-wide claims still require precise scope and version.', officialUrl: 'https://www.cisecurity.org/cis-benchmarks', complementary: ['cis-controls', 'nist-sp-800-53', 'iso-iec-27001'], checkedAt,
  },
  {
    slug: 'cobit-2019', shortName: 'COBIT 2019', fullName: 'Control Objectives for Information and Related Technologies 2019', aliases: ['COBIT'], authorityType: 'Framework', owner: 'ISACA', jurisdiction: 'Global voluntary use', domains: ['Enterprise governance', 'Technology management'], currentEdition: 'COBIT 2019', status: 'Current', statusDetail: 'A governance and management framework with design factors and 40 governance and management objectives.', applicableTo: 'Boards, executives and technology leaders designing governance of enterprise information and technology.', purpose: 'Connect stakeholder needs, governance objectives, management practices, capability, information and performance across enterprise technology.', structure: ['Governance system principles', 'Governance framework principles', 'Design factors', 'Governance objectives', 'Management objectives', 'Goals cascade and performance management'], usefulFor: ['Decision rights and accountability', 'Governance-system design', 'Technology portfolio oversight', 'Cross-framework integration'], evidence: ['Governance-system design', 'Goals and objectives map', 'Decision-rights record', 'Performance and capability assessment', 'Improvement roadmap'], notEquivalentTo: ['A cybersecurity checklist', 'An audit standard', 'ITIL', 'A product implementation method'], certificationOrAssurance: 'COBIT supports assessment and professional credentials. An organization should describe assessed scope and capability rather than imply a universal certification.', officialUrl: 'https://www.isaca.org/resources/cobit', complementary: ['itil-version-5', 'iso-iec-20000-1', 'nist-csf'], checkedAt,
  },
  {
    slug: 'itil-version-5', shortName: 'ITIL Version 5', fullName: 'Information Technology Infrastructure Library Version 5', aliases: ['ITIL 5', 'ITIL'], authorityType: 'Framework', owner: 'PeopleCert', jurisdiction: 'Global commercial guidance', domains: ['Product management', 'Service management', 'Operations'], currentEdition: 'ITIL Version 5', status: 'Current with transition', statusDetail: 'ITIL Version 5 is the current evolution. ITIL 4 remains available during a transition currently planned through 31 December 2027.', applicableTo: 'Organizations managing digital products and services and the value streams, practices, partners and improvement around them.', purpose: 'Provide adaptable guidance for creating, delivering, supporting and improving digital products and services.', structure: ['Value system and guiding principles', 'Product and service lifecycle', 'Value streams', 'Management practices', 'Governance and continual improvement'], usefulFor: ['Service and product operating models', 'Incident, problem and change practices', 'Value-stream design', 'Continual improvement'], evidence: ['Service or product model', 'Value-stream map', 'Practice procedure and ownership', 'Service performance review', 'Continual-improvement register'], notEquivalentTo: ['ISO/IEC 20000-1 certification', 'A rigid process manual', 'Only a help-desk framework', 'A cybersecurity control catalog'], certificationOrAssurance: 'PeopleCert provides individual and organizational schemes, but claims should identify the exact scheme. ITIL guidance is not the same as ISO/IEC 20000 certification.', officialUrl: 'https://www.peoplecert.org/news-and-announcements/itil-version-5-explained', complementary: ['iso-iec-20000-1', 'cobit-2019', 'iso-22301'], checkedAt,
  },
  {
    slug: 'soc-1', shortName: 'SOC 1', fullName: 'System and Organization Controls 1 examination', aliases: ['SOC 1 report', 'SSAE 18 service-organization report'], authorityType: 'Attestation examination', owner: 'American Institute of Certified Public Accountants', jurisdiction: 'United States origin with global financial-reporting assurance use', domains: ['Assurance', 'Financial reporting', 'Service organizations'], currentEdition: '2025 AICPA SOC 1 guide under AT-C section 320', status: 'Current', statusDetail: 'A service-auditor examination of controls at a service organization that are likely to be relevant to user entities internal control over financial reporting.', applicableTo: 'Service organizations and their customers where outsourced services affect financial reporting, including payroll, transaction processing, custody and technology services in scope.', purpose: 'Help user entities and their auditors understand and obtain assurance over financially relevant service-organization controls.', structure: ['Management description and assertion', 'Control objectives and controls', 'Complementary user entity controls', 'Service-auditor tests and results', 'Type I at a date or Type II over a period'], usefulFor: ['Financial-reporting supplier assurance', 'SOX scoping', 'User-auditor reliance decisions', 'Complementary control identification'], evidence: ['System description and scope', 'Management assertion', 'Control objective and test population', 'Exceptions and response', 'Complementary user entity and subservice-organization controls'], notEquivalentTo: ['SOC 2', 'A broad cybersecurity certification', 'A Security Operations Center', 'Proof that every customer control is effective'], certificationOrAssurance: 'SOC 1 is a restricted-use attestation report, not a certification. Type I covers the system description and suitability of control design as of a specified date; Type II additionally covers operating effectiveness over a specified period.', officialUrl: 'https://www.aicpa-cima.com/cpe-learning/publication/reporting-on-an-examination-of-controls-at-a-service-organization-relevant-to-user-entities-internal-control-over-financial-reporting-soc-1-guide', complementary: ['sarbanes-oxley-act', 'coso-internal-control', 'soc-2'], checkedAt,
  },
  {
    slug: 'soc-2', shortName: 'SOC 2', fullName: 'System and Organization Controls 2 examination', aliases: ['SOC 2 report', 'System and Organization Controls 2'], authorityType: 'Attestation examination', owner: 'American Institute of Certified Public Accountants', jurisdiction: 'United States origin with global supplier-assurance use', domains: ['Assurance', 'Technology services', 'Controls'], currentEdition: '2017 Trust Services Criteria with revised 2022 points of focus and 2018 Description Criteria with revised 2022 guidance', status: 'Current', statusDetail: 'A service-auditor examination of controls relevant to selected Trust Services Criteria for a defined system and period or date.', applicableTo: 'Service organizations that need an independent report about a defined system used to provide services to customers.', purpose: 'Give users and their auditors assurance about a service organization’s system description and controls relevant to security and selected additional criteria.', structure: ['System description', 'Security common criteria', 'Optional availability, processing integrity, confidentiality and privacy criteria', 'Management assertion', 'Service auditor tests and opinion'], usefulFor: ['Supplier assurance', 'Control design and operation evidence', 'Customer due diligence', 'Complementary user entity control identification'], evidence: ['System description and boundary', 'Management assertion', 'Control population and samples', 'Exceptions and management response', 'Type I or Type II service auditor report'], notEquivalentTo: ['Security Operations Center', 'A universal certification', 'SOC 1', 'Proof that no incident occurred'], certificationOrAssurance: 'SOC 2 is an attestation report, not a certification. Type I covers the system description and suitability of control design as of a specified date; Type II additionally covers operating effectiveness over a specified period.', officialUrl: 'https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2/', complementary: ['iso-iec-27001', 'csa-ccm', 'nist-sp-800-53'], checkedAt,
  },
  {
    slug: 'owasp-top-10', shortName: 'OWASP Top 10', fullName: 'Open Worldwide Application Security Project Top 10', aliases: ['OWASP Top 10:2025'], authorityType: 'Knowledge base', owner: 'Open Worldwide Application Security Project', jurisdiction: 'Global community project', domains: ['Application security', 'Awareness'], currentEdition: '2025 edition', status: 'Current', statusDetail: 'An awareness document that summarizes broad categories of critical web-application security risk.', applicableTo: 'Developers, testers, product teams and leaders needing a common introduction to recurring web-application risk categories.', purpose: 'Build awareness and conversation around common, consequential web-application security weaknesses.', structure: ['Ten broad risk categories', 'Description and factors', 'Prevention ideas', 'Example attack scenarios', 'References and mappings'], usefulFor: ['Awareness and education', 'Initial design conversations', 'Training examples', 'Starting a broader application-security program'], evidence: ['Training material', 'Threat model mapping', 'Secure-coding standard link', 'Test coverage map', 'Remediation decision'], notEquivalentTo: ['A complete test plan', 'A security standard', 'A guarantee of secure software', 'OWASP ASVS'], certificationOrAssurance: 'There is no official universal OWASP Top 10 compliance certificate. Claims based only on ten categories are too narrow for serious assurance.', officialUrl: 'https://owasp.org/Top10/', complementary: ['owasp-asvs', 'owasp-wstg', 'owasp-samm'], checkedAt,
  },
  {
    slug: 'owasp-asvs', shortName: 'OWASP ASVS', fullName: 'Open Worldwide Application Security Project Application Security Verification Standard', aliases: ['ASVS'], authorityType: 'Guidance standard', owner: 'Open Worldwide Application Security Project', jurisdiction: 'Global community project', domains: ['Application security', 'Verification'], currentEdition: 'Version 5.0.0, May 2025', status: 'Current', statusDetail: 'A structured set of application-security requirements and verification levels for design, development, testing and procurement.', applicableTo: 'Application owners, developers, testers, suppliers and assessors defining or verifying security requirements.', purpose: 'Provide testable application-security requirements that are deeper and more systematic than an awareness list.', structure: ['Verification levels', 'Requirement chapters', 'Requirement identifiers', 'Architecture, authentication, access, validation, cryptography, data and operational themes'], usefulFor: ['Security requirements', 'Verification planning', 'Supplier contracts', 'Release criteria'], evidence: ['Selected verification level and rationale', 'Requirement applicability map', 'Test procedure and result', 'Exception and risk decision', 'Remediation and retest evidence'], notEquivalentTo: ['OWASP Top 10', 'A penetration test report alone', 'A certification issued by OWASP', 'A secure-development maturity model'], certificationOrAssurance: 'Organizations and testers may assess against ASVS, but OWASP does not operate a universal official ASVS product certification program.', officialUrl: 'https://owasp.org/www-project-application-security-verification-standard/', complementary: ['owasp-wstg', 'owasp-samm', 'nist-ssdf'], checkedAt,
  },
  {
    slug: 'owasp-samm', shortName: 'OWASP SAMM', fullName: 'Open Worldwide Application Security Project Software Assurance Maturity Model', aliases: ['Software Assurance Maturity Model'], authorityType: 'Framework', owner: 'Open Worldwide Application Security Project', jurisdiction: 'Global community project', domains: ['Secure development', 'Maturity'], currentEdition: 'Version 2.0 model', status: 'Current', statusDetail: 'A measurable, risk-driven maturity model spanning governance, design, implementation, verification and operations.', applicableTo: 'Organizations improving software-security capability across teams, portfolios and delivery models.', purpose: 'Assess current software-assurance practices, define a target and build a sequenced improvement roadmap.', structure: ['Governance', 'Design', 'Implementation', 'Verification', 'Operations', 'Fifteen security practices with maturity activities'], usefulFor: ['Program maturity assessment', 'Roadmap design', 'Capability comparison', 'Executive investment planning'], evidence: ['Assessment scope and interviews', 'Practice evidence', 'Current and target maturity', 'Prioritized roadmap', 'Follow-up measurement'], notEquivalentTo: ['Application verification', 'OWASP ASVS', 'A control certification', 'A guarantee about one product'], certificationOrAssurance: 'SAMM provides assessment guidance. Any external assurance should state assessor, scope, evidence and method rather than imply OWASP certification.', officialUrl: 'https://owaspsamm.org/model/', complementary: ['nist-ssdf', 'owasp-asvs', 'owasp-wstg'], checkedAt,
  },
  {
    slug: 'owasp-wstg', shortName: 'OWASP WSTG', fullName: 'Open Worldwide Application Security Project Web Security Testing Guide', aliases: ['Web Security Testing Guide'], authorityType: 'Testing guide', owner: 'Open Worldwide Application Security Project', jurisdiction: 'Global community project', domains: ['Web security', 'Testing'], currentEdition: 'Stable 4.2; version 5.0 in development', status: 'Stable and developing branches', statusDetail: 'Use versioned links when citing tests. Do not present the developing 5.0 branch as the stable release.', applicableTo: 'Authorized testers, developers and application owners planning systematic web-security testing.', purpose: 'Provide a structured methodology and scenario catalog for understanding and testing web-application security behavior.', structure: ['Information gathering', 'Configuration and deployment', 'Identity and authentication', 'Authorization and sessions', 'Input validation', 'Business logic, client side and API testing'], usefulFor: ['Rules of engagement', 'Test-plan coverage', 'Evidence collection', 'Reproducible finding references'], evidence: ['Authorized scope and rules', 'Versioned test plan', 'Request and response evidence', 'Finding and impact validation', 'Retest result'], notEquivalentTo: ['Permission to test', 'A vulnerability scanner', 'OWASP ASVS', 'A guarantee of complete coverage'], certificationOrAssurance: 'A test can cite WSTG methods, but there is no universal OWASP certificate proving an application is secure.', officialUrl: 'https://owasp.org/www-project-web-security-testing-guide/', complementary: ['owasp-asvs', 'owasp-top-10', 'nist-ssdf'], checkedAt,
  },
  {
    slug: 'mitre-attack', shortName: 'MITRE ATT&CK', fullName: 'MITRE Adversarial Tactics, Techniques, and Common Knowledge', aliases: ['ATT&CK'], authorityType: 'Knowledge base', owner: 'MITRE', jurisdiction: 'Global knowledge base', domains: ['Threats', 'Detection', 'Adversary behavior'], currentEdition: 'Version 19, released 28 April 2026', status: 'Living knowledge base', statusDetail: 'Continuously updated from reported observations across Enterprise, Mobile and Industrial Control Systems knowledge bases.', applicableTo: 'Threat-intelligence, defensive, red-team, architecture and risk functions that need a shared language for observed adversary behavior.', purpose: 'Describe tactics, techniques, sub-techniques, software, groups, campaigns, mitigations, Detection Strategies, Analytics and Data Components based on real-world observations.', structure: ['Tactics as adversary objectives', 'Techniques and sub-techniques as behavior', 'Procedures, groups, campaigns and software', 'Mitigations', 'Detection Strategies, platform-specific Analytics and Data Components'], usefulFor: ['Threat-informed defense', 'Detection engineering', 'Adversary emulation', 'Coverage and intelligence mapping'], evidence: ['Threat profile and technique rationale', 'Telemetry and Data Component coverage map', 'Detection Strategy, analytic and test', 'Emulation result', 'Coverage gap and improvement record'], notEquivalentTo: ['A compliance framework', 'A complete control catalog', 'Proof of coverage because a cell is colored', 'A list of every possible attack'], certificationOrAssurance: 'ATT&CK mappings are analytical evidence, not certification. Good mappings state scope, data, logic, validation and limitations. Data Sources were deprecated in ATT&CK version 18, so new defensive work should use current Detection Strategies, Analytics and Data Components.', officialUrl: 'https://attack.mitre.org/', complementary: ['mitre-d3fend', 'nist-csf', 'nist-incident-response'], checkedAt,
  },
  {
    slug: 'mitre-d3fend', shortName: 'MITRE D3FEND', fullName: 'MITRE D3FEND cybersecurity countermeasure knowledge graph', aliases: ['D3FEND'], authorityType: 'Knowledge base', owner: 'MITRE', jurisdiction: 'Global knowledge base', domains: ['Defensive security', 'Architecture'], currentEdition: 'Version 1.5.0', status: 'Living knowledge base', statusDetail: 'A knowledge graph connecting defensive techniques, digital artifacts and selected offensive behavior relationships.', applicableTo: 'Architects, detection engineers and defenders reasoning about how defensive techniques affect digital artifacts and attacks.', purpose: 'Create a precise vocabulary for cybersecurity countermeasures and their relationships to system artifacts and adversary techniques.', structure: ['Defensive techniques', 'Digital artifacts', 'Tactics and relationships', 'Mappings and ontology'], usefulFor: ['Defensive architecture', 'Control-effect reasoning', 'Coverage mapping', 'Technical education'], evidence: ['System and artifact map', 'Selected countermeasure rationale', 'ATT&CK relationship map', 'Test and telemetry evidence', 'Coverage limitation record'], notEquivalentTo: ['A prescriptive enterprise baseline', 'A security product catalog', 'MITRE ATT&CK', 'Proof that a control blocks every mapped technique'], certificationOrAssurance: 'It is a knowledge graph, not a certification scheme. Mappings need system context and validation.', officialUrl: 'https://d3fend.mitre.org/', complementary: ['mitre-attack', 'nist-sp-800-53', 'cis-controls'], checkedAt,
  },
  {
    slug: 'csa-ccm', shortName: 'CSA CCM', fullName: 'Cloud Security Alliance Cloud Controls Matrix and Consensus Assessments Initiative Questionnaire', aliases: ['Cloud Controls Matrix', 'CAIQ'], authorityType: 'Control catalog', owner: 'Cloud Security Alliance', jurisdiction: 'Global cloud ecosystem', domains: ['Cloud', 'Supplier assurance', 'Controls'], currentEdition: 'Version 4.1, January 2026', status: 'Current', statusDetail: 'A cloud-focused control framework and assessment questionnaire with mappings to common standards and regulations.', applicableTo: 'Cloud providers, customers, assessors and procurement teams evaluating cloud control responsibilities and evidence.', purpose: 'Provide a cloud-specific control language and reusable questions for assessing provider and customer security practices.', structure: ['Control domains', 'Control specifications', 'Implementation guidance', 'CAIQ questions', 'Framework mappings'], usefulFor: ['Cloud due diligence', 'Shared-responsibility mapping', 'Control design', 'Supplier questionnaires and STAR submissions'], evidence: ['Applicable control map', 'Shared-responsibility matrix', 'Completed CAIQ with supporting evidence', 'Independent assurance link', 'Gap and remediation record'], notEquivalentTo: ['Independent assurance by itself', 'A cloud security certification', 'A provider marketing questionnaire', 'Proof that every service configuration is secure'], certificationOrAssurance: 'CSA STAR offers assurance levels and registry entries. A self-assessment must not be described as an independent audit.', officialUrl: 'https://cloudsecurityalliance.org/artifacts/cloud-controls-matrix-v4-1', complementary: ['iso-iec-27001', 'soc-2', 'nist-csf'], checkedAt,
  },
  {
    slug: 'pci-dss', shortName: 'PCI DSS', fullName: 'Payment Card Industry Data Security Standard', aliases: ['PCI DSS v4.0.1'], authorityType: 'Industry standard', owner: 'PCI Security Standards Council', jurisdiction: 'Global payment-card ecosystem through program rules and agreements', domains: ['Payments', 'Security', 'Compliance'], currentEdition: 'Version 4.0.1', status: 'Current', statusDetail: 'Version 4.0.1 is the active version. Future-dated requirements became effective on 31 March 2025.', applicableTo: 'Entities that store, process or transmit payment account data, and relevant service providers, subject to payment-brand and acquirer program rules.', purpose: 'Protect account data through defined technical and operational security requirements across the Cardholder Data Environment.', structure: ['Network and system controls', 'Account-data protection', 'Vulnerability management', 'Access control', 'Monitoring and testing', 'Security policy and programs'], usefulFor: ['Cardholder Data Environment scoping', 'Payment segmentation', 'Merchant or service-provider validation', 'Targeted risk analysis'], evidence: ['Cardholder Data Environment scope', 'Data-flow and segmentation diagrams', 'Control test results', 'Targeted risk analysis', 'Self-Assessment Questionnaire or Report on Compliance'], notEquivalentTo: ['Government law', 'Protection for every type of personal data', 'Proof that no card breach can happen', 'One validation method for all entities'], certificationOrAssurance: 'Validation depends on entity role and program requirements, using a Self-Assessment Questionnaire or Qualified Security Assessor-led Report on Compliance as applicable.', officialUrl: 'https://www.pcisecuritystandards.org/document_library/', complementary: ['iso-iec-27001', 'nist-csf', 'owasp-asvs'], checkedAt,
  },
  {
    slug: 'open-fair', shortName: 'Open FAIR', fullName: 'Open Factor Analysis of Information Risk', aliases: ['FAIR', 'O-RA', 'O-RT'], authorityType: 'Framework', owner: 'The Open Group', jurisdiction: 'Global voluntary use', domains: ['Quantitative risk', 'Cyber risk'], currentEdition: 'Risk Analysis Standard O-RA 2.0.1 and Risk Taxonomy Standard O-RT 3.0.1', status: 'Current', statusDetail: 'A factor-based taxonomy and analysis method for estimating frequency and magnitude of loss in ranges.', applicableTo: 'Risk practitioners and decision makers who need transparent, quantitative analysis of information and technology risk scenarios.', purpose: 'Decompose risk into estimable factors so uncertainty, assumptions and decision sensitivity can be discussed clearly.', structure: ['Loss event frequency', 'Threat event frequency and vulnerability', 'Probable loss magnitude', 'Primary and secondary loss', 'Ranges, calibration and simulation'], usefulFor: ['Investment decisions', 'Scenario comparison', 'Cyber insurance and loss analysis', 'Communicating uncertainty'], evidence: ['Precisely scoped risk scenario', 'Data and calibrated estimates', 'Assumption and source register', 'Simulation output and sensitivity', 'Decision and review record'], notEquivalentTo: ['A control framework', 'A guaranteed prediction', 'ISO 31000', 'A single-point annual-loss estimate'], certificationOrAssurance: 'The Open Group offers professional certification. Analysis quality still depends on scenario scope, data, calibration and transparent uncertainty.', officialUrl: 'https://www.opengroup.org/open-fair', complementary: ['iso-31000', 'iso-iec-27005', 'coso-erm'], checkedAt,
  },
  {
    slug: 'coso-erm', shortName: 'COSO ERM', fullName: 'Enterprise Risk Management: Integrating with Strategy and Performance', aliases: ['COSO Enterprise Risk Management'], authorityType: 'Framework', owner: 'Committee of Sponsoring Organizations of the Treadway Commission', jurisdiction: 'Global voluntary use with strong United States governance influence', domains: ['Enterprise risk', 'Strategy', 'Performance'], currentEdition: '2017 framework', status: 'Current', statusDetail: 'Integrates risk with strategy-setting, governance, performance and review rather than treating risk as a separate register.', applicableTo: 'Boards and management teams integrating uncertainty and risk into strategy, execution and performance.', purpose: 'Improve decisions by connecting governance and culture, strategy, objectives, risk performance, review and information.', structure: ['Governance and culture', 'Strategy and objective-setting', 'Performance', 'Review and revision', 'Information, communication and reporting'], usefulFor: ['Enterprise-risk operating models', 'Strategy and risk appetite', 'Portfolio risk', 'Board reporting'], evidence: ['Risk governance and appetite', 'Strategy and objective linkage', 'Risk profile and performance measures', 'Portfolio view', 'Review and revision record'], notEquivalentTo: ['COSO Internal Control', 'A cybersecurity framework', 'A certifiable standard', 'One mandatory risk-assessment method'], certificationOrAssurance: 'Organizations can assess alignment and controls, but COSO ERM is not a universal management-system certification.', officialUrl: 'https://www.coso.org/enterprise-risk-management', complementary: ['coso-internal-control', 'iso-31000', 'open-fair'], checkedAt,
  },
  {
    slug: 'coso-internal-control', shortName: 'COSO Internal Control', fullName: 'Internal Control: Integrated Framework', aliases: ['COSO ICIF'], authorityType: 'Framework', owner: 'Committee of Sponsoring Organizations of the Treadway Commission', jurisdiction: 'Global voluntary use with strong United States reporting influence', domains: ['Internal control', 'Financial reporting', 'Operations'], currentEdition: '2013 framework', status: 'Current', statusDetail: 'Uses five components and seventeen principles to evaluate effective internal control across operations, reporting and compliance objectives.', applicableTo: 'Organizations designing, operating and assessing internal controls, especially in financial-reporting and governance contexts.', purpose: 'Provide an integrated model for control environment, risk assessment, control activities, information and communication, and monitoring.', structure: ['Control environment', 'Risk assessment', 'Control activities', 'Information and communication', 'Monitoring activities', 'Seventeen principles'], usefulFor: ['Internal-control design', 'Financial-reporting controls', 'Control deficiency evaluation', 'Assurance communication'], evidence: ['Control objective and risk mapping', 'Process and control documentation', 'Operating evidence', 'Deficiency evaluation', 'Management and audit reporting'], notEquivalentTo: ['COSO ERM', 'A cybersecurity control catalog', 'A certifiable standard', 'Proof that fraud cannot occur'], certificationOrAssurance: 'Internal and external auditors may assess controls using COSO. There is no generic COSO certificate that eliminates management responsibility.', officialUrl: 'https://www.coso.org/guidance-on-ic', complementary: ['coso-erm', 'cobit-2019', 'soc-2'], checkedAt,
  },
  {
    slug: 'iec-62443', shortName: 'IEC 62443', fullName: 'Industrial automation and control systems security series', aliases: ['ISA/IEC 62443'], authorityType: 'Industry standard', owner: 'International Electrotechnical Commission with International Society of Automation collaboration', jurisdiction: 'International', domains: ['Operational technology', 'Industrial security', 'Safety-critical systems'], currentEdition: 'Multi-part series with part-specific editions', status: 'Living multi-part series', statusDetail: 'IEC 62443 is a family of standards, not one document or one edition called IEC 62443:2026.', applicableTo: 'Asset owners, system integrators, service providers and product suppliers across industrial automation and control-system lifecycles.', purpose: 'Establish roles, security programs, zones and conduits, system requirements and secure product-development expectations for industrial environments.', structure: ['Concepts, terminology and models', 'Asset-owner security program', 'Service-provider requirements', 'System design and security levels', 'Secure product development', 'Component technical requirements'], usefulFor: ['Operational Technology zoning', 'Industrial supplier requirements', 'Remote-access design', 'Secure product lifecycle and assurance'], evidence: ['System under consideration and asset map', 'Zone and conduit diagram', 'Target security-level rationale', 'Security-requirement specification', 'Supplier lifecycle and test evidence'], notEquivalentTo: ['One checklist for all factories', 'Information Technology security applied unchanged', 'A safety standard', 'A single certificate covering every part'], certificationOrAssurance: 'Certification schemes can assess defined products, processes or organizations against particular parts. Claims must identify the exact part, scope and scheme.', officialUrl: 'https://syc-se.iec.ch/deliveries/cybersecurity-guidelines/security-standards-and-best-practices/iec-62443/', complementary: ['iso-iec-27001', 'nist-csf', 'cis-controls'], checkedAt,
  },
  {
    slug: 'sarbanes-oxley-act', shortName: 'SOX', fullName: 'Sarbanes-Oxley Act of 2002', aliases: ['Sarbanes Oxley', 'Public Law 107-204'], authorityType: 'Law or regulation', owner: 'United States Congress with Securities and Exchange Commission and Public Company Accounting Oversight Board implementation', jurisdiction: 'United States public-company reporting and defined related parties', domains: ['Financial reporting', 'Governance', 'Internal control', 'Audit'], currentEdition: 'Public Law 107-204 with implementing SEC and PCAOB requirements', status: 'In force', statusDetail: 'The Act remains in force. Exact issuer, filer, certification and auditor-attestation requirements depend on current securities rules, company status and applicable exemptions.', applicableTo: 'United States reporting companies and other defined actors within the statute and implementing rules. Section 404(b) auditor-attestation applicability differs by filer status.', purpose: 'Protect investors by improving the accuracy and reliability of corporate disclosures, executive accountability, audit oversight and internal control over financial reporting.', structure: ['Public Company Accounting Oversight Board and auditor independence', 'Section 302 executive certifications', 'Section 404 management assessment and defined auditor attestation', 'Audit committee responsibilities', 'Records, disclosures, conduct and enforcement'], usefulFor: ['Internal Control over Financial Reporting programs', 'Entity, process and technology control scoping', 'Management certification support', 'Control deficiency evaluation and remediation'], evidence: ['Financial-reporting risk and scope assessment', 'Process, application and Information Technology General Control documentation', 'Design and operating-effectiveness testing', 'Deficiency evaluation and remediation record', 'Management assessment and certification support'], notEquivalentTo: ['A universal cybersecurity law', 'COSO Internal Control itself', 'A requirement that every company receive the same Section 404(b) attestation', 'Proof that fraud or error cannot occur'], certificationOrAssurance: 'SOX is law, not a certification. Management remains responsible for Internal Control over Financial Reporting. Where required, a registered public accounting firm performs an integrated audit under applicable PCAOB standards.', officialUrl: 'https://www.govinfo.gov/app/details/PLAW-107publ204/summary', complementary: ['coso-internal-control', 'soc-1'], checkedAt,
  },
  {
    slug: 'global-internal-audit-standards', shortName: 'Global Internal Audit Standards', fullName: 'The Institute of Internal Auditors Global Internal Audit Standards', aliases: ['GIAS', '2024 IPPF'], authorityType: 'Guidance standard', owner: 'The Institute of Internal Auditors', jurisdiction: 'Global professional practice', domains: ['Internal audit', 'Governance', 'Assurance'], currentEdition: '2024 edition, effective 9 January 2025', status: 'Current', statusDetail: 'The 2024 Standards superseded the 2017 International Professional Practices Framework standards and became effective on 9 January 2025.', applicableTo: 'Internal audit functions and practitioners applying the International Professional Practices Framework, subject to legal and sector requirements.', purpose: 'Guide effective internal auditing through principles and requirements for purpose, ethics, governance, management and performance.', structure: ['Purpose of internal auditing', 'Ethics and professionalism', 'Governing the internal audit function', 'Managing the internal audit function', 'Performing internal audit services', 'Topical Requirements and Global Guidance'], usefulFor: ['Internal-audit charter and mandate', 'Risk-based planning and engagement performance', 'Board and chief audit executive relationships', 'Quality Assurance and Improvement Program'], evidence: ['Board-approved charter', 'Independence and organizational-position record', 'Risk-based plan and resource assessment', 'Engagement workpapers and communications', 'Internal and external quality-assessment results'], notEquivalentTo: ['External-audit standards', 'A law in every jurisdiction', 'Management ownership of risk and controls', 'A certificate proving every engagement is effective'], certificationOrAssurance: 'Conformance is evaluated through the internal audit function’s Quality Assurance and Improvement Program, including internal and periodic external assessments. Legal and regulatory duties remain separate.', officialUrl: 'https://www.theiia.org/en/standards/', complementary: ['coso-erm', 'coso-internal-control'], checkedAt,
  },
];

export const frameworkBySlug = new Map(frameworkCatalog.map((framework) => [framework.slug, framework]));

export const frameworkDomains = [...new Set(frameworkCatalog.flatMap((framework) => framework.domains))].sort();

export function frameworkTypeSummary(type: FrameworkAuthority) {
  const summaries: Record<FrameworkAuthority, string> = {
    'Law or regulation': 'A binding legal instrument when its jurisdiction, subject matter and role-based scope apply.',
    Directive: 'A European Union legal instrument implemented through national law, so local transposition must be checked.',
    'Certifiable standard': 'A requirements standard against which a defined management-system or other scope may be independently certified.',
    'Guidance standard': 'Published guidance that supports implementation but is not independently certifiable unless a separate scheme says otherwise.',
    Framework: 'A structured way to organize decisions, outcomes or practices. Its authority depends on how it is adopted.',
    'Control catalog': 'A reusable set of controls or safeguards that must be selected, tailored, implemented and evidenced in context.',
    'Assurance criteria': 'Criteria used by an independent practitioner to evaluate and report on a defined subject matter and scope.',
    'Attestation examination': 'An independent practitioner examines a defined subject matter against suitable criteria and issues a report. It is not a product badge or universal certification.',
    'Knowledge base': 'A maintained body of concepts and relationships used for analysis, design and communication rather than compliance certification.',
    'Testing guide': 'A structured testing methodology that still requires authorization, scope, safe execution and professional judgment.',
    'Industry standard': 'A standard applied through an industry ecosystem, contract, program or specific adoption rather than general government law.',
  };
  return summaries[type];
}
