export type AdditionalGlossaryTerm = {
  term: string;
  expansion?: string;
  category: string;
  domainSlug: string;
  meaning: string;
  example: string;
  howItWorks?: string;
  whyItMatters?: string;
  commonConfusion?: string;
  where?: string;
  boundary?: string;
  aliases?: string[];
  related?: string[];
  officialUrl?: string;
  authority?: string;
  jurisdiction?: string;
  version?: string;
  status?: string;
  lastReviewed?: string;
};

export const additionalGlossary: AdditionalGlossaryTerm[] = [
  { term: 'Linux', category: 'Linux', domainSlug: 'computing-linux', meaning: 'The open-source operating-system kernel and, informally, the family of operating systems built around it.', example: 'Ubuntu, Debian and Red Hat Enterprise Linux combine the Linux kernel with maintained user-space tools.', where: 'On servers, cloud workloads, embedded devices, developer systems, network appliances and personal computers.', related: ['Kernel', 'Linux distribution', 'Shell'] },
  { term: 'Linux distribution', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A packaged operating system combining the Linux kernel, user-space utilities, package management and maintained software repositories.', example: 'A team selects a supported enterprise distribution with a defined security-update lifecycle.', where: 'Installed on physical, virtual, cloud, container-host and embedded systems.', related: ['Linux', 'Package manager', 'Kernel'] },
  { term: 'Kernel', category: 'Linux', domainSlug: 'computing-linux', meaning: 'The privileged operating-system core that manages processors, memory, devices, processes and system calls.', example: 'A program requests file access through a system call that the kernel mediates.', where: 'Between applications and hardware, executing with high privilege.', related: ['Linux', 'Process', 'System call'] },
  { term: 'Shell', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A command interpreter that lets a user or script request operating-system actions.', example: 'Bash expands a command, starts a process and displays its output in a terminal.', where: 'Locally in a terminal, remotely through Secure Shell, or non-interactively in a script.', related: ['Terminal', 'SSH', 'Process'] },
  { term: 'Terminal', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A text interface through which a person interacts with a shell or a remote system.', example: 'A terminal window runs a shell that accepts commands and renders output.', boundary: 'The terminal is the interface; the shell interprets commands. They are related but not identical.', related: ['Shell', 'SSH'] },
  { term: 'Filesystem hierarchy', category: 'Linux', domainSlug: 'computing-linux', meaning: 'The organized directory tree that separates configuration, programs, variable data, users, devices and runtime state.', example: 'Configuration is commonly under /etc while changing logs and queues are commonly under /var.', where: 'Mounted beneath a single root directory represented by a forward slash.', related: ['Inode', 'Mount point', 'File permission'] },
  { term: 'Inode', category: 'Linux', domainSlug: 'computing-linux', meaning: 'Filesystem metadata identifying an object and storing attributes such as ownership, permissions and data-block references.', example: 'Two hard links can refer to the same inode while using different directory entries.', where: 'Inside filesystems that use inode-style metadata.', related: ['Filesystem hierarchy', 'File permission'] },
  { term: 'root user', category: 'Linux', domainSlug: 'computing-linux', meaning: 'The Linux superuser account with broad authority across the system.', example: 'An administrator uses sudo for one approved command instead of remaining logged in as root.', where: 'Local and remote administration, service setup and recovery.', boundary: 'Root access can bypass many ordinary permission checks, so it should be restricted, attributable and monitored.', aliases: ['root'], related: ['sudo', 'Least privilege'] },
  { term: 'sudo', expansion: 'Superuser do', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A controlled mechanism for running an approved command with another identity, commonly root.', example: 'A support role may restart one service without receiving unrestricted administrator access.', where: 'Configured through sudo policy and recorded in operating-system logs.', related: ['root user', 'Least privilege'] },
  { term: 'rwx', expansion: 'Read, write and execute', category: 'Linux', domainSlug: 'computing-linux', meaning: 'The three basic Linux permission bits applied separately to the file owner, owning group and others.', example: 'rwxr-x--- means the owner can read, write and execute, the group can read and execute, and others have no access.', where: 'Stored as mode bits on filesystem objects.', related: ['Octal permission', 'chmod', 'File permission'] },
  { term: 'Octal permission', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A numeric representation of Linux permissions using read equals 4, write equals 2 and execute equals 1 for each identity class.', example: '750 means owner 7 or rwx, group 5 or r-x, and others 0 or no permissions.', where: 'Used by commands such as chmod and shown by administration tools.', boundary: '777 is the maximum ordinary rwx combination, not a security goal. It grants every identity broad access.', aliases: ['Linux permission number'], related: ['rwx', 'chmod', 'umask'] },
  { term: 'chmod', expansion: 'Change mode', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A command and system operation used to change file or directory permission bits.', example: 'chmod 640 report.txt grants the owner read and write, the group read, and others no access.', where: 'Linux and Unix-like filesystems.', related: ['Octal permission', 'rwx', 'chown'] },
  { term: 'chown', expansion: 'Change owner', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A command and system operation used to change file or directory ownership.', example: 'A deployment changes an application directory to the dedicated service account and group.', where: 'Linux and Unix-like filesystems, normally requiring suitable privilege.', related: ['chmod', 'root user', 'Least privilege'] },
  { term: 'umask', expansion: 'User file-creation mode mask', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A process setting that removes selected permissions from newly created files and directories.', example: 'A restrictive umask prevents newly created files from being readable by unrelated users.', where: 'Inherited by processes and often configured in shell, service or system policy.', related: ['Octal permission', 'chmod'] },
  { term: 'setuid', expansion: 'Set user ID', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A special permission that can make an executable run with the file owner’s effective identity.', example: 'A narrowly designed system utility may need controlled elevated behavior.', where: 'On executable filesystem objects.', boundary: 'A vulnerable setuid-root program can become a privilege-escalation path and should be minimized and monitored.', related: ['root user', 'Least privilege'] },
  { term: 'setgid', expansion: 'Set group ID', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A special permission that changes executable group identity or makes new objects in a directory inherit its group.', example: 'A shared project directory uses setgid so new files retain the project group.', where: 'On executable files or shared directories.', related: ['Octal permission', 'chown'] },
  { term: 'Sticky bit', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A directory permission commonly used to prevent users from deleting one another’s files in a shared writable directory.', example: '/tmp is typically writable by many users but protected with the sticky bit.', where: 'On shared directories, displayed as a final t in symbolic permissions.', related: ['Octal permission', 'rwx'] },
  { term: 'systemd', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A common Linux system and service manager responsible for startup, service supervision and related system state.', example: 'systemctl shows whether an application service is running and enables it at boot.', where: 'As the initial userspace process and management layer on many Linux distributions.', related: ['Process', 'Service', 'journal'] },
  { term: 'Package manager', category: 'Linux', domainSlug: 'computing-linux', meaning: 'Software that installs, verifies, updates and removes packages through configured repositories.', example: 'A server obtains a signed security update through its distribution package manager.', where: 'At the operating-system software-maintenance layer.', related: ['Linux distribution', 'Patch management'] },
  { term: 'SSH', expansion: 'Secure Shell', category: 'Linux', domainSlug: 'computing-linux', meaning: 'A protocol and tool family for authenticated, encrypted remote administration and file transfer.', example: 'An administrator authenticates with a key through a controlled bastion host.', where: 'Between an SSH client and server, commonly over Transmission Control Protocol port 22.', boundary: 'Encryption does not make an exposed, weakly authenticated or overprivileged SSH service safe.', related: ['Shell', 'MFA', 'Least privilege'] },

  { term: 'Artificial Intelligence', expansion: 'AI', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'The broad field of building systems that perform tasks associated with perception, language, reasoning, learning or action.', example: 'A service classifies documents, recommends next actions and explains the supporting evidence.', boundary: 'Artificial intelligence is an umbrella term. It does not imply consciousness, general intelligence or reliable judgment.', related: ['Machine Learning', 'Generative AI', 'Agent'] },
  { term: 'Machine Learning', expansion: 'ML', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Methods that learn patterns from data to make predictions or guide outputs without manually encoding every rule.', example: 'A fraud model learns patterns from past transactions and produces a risk score.', where: 'Inside analytical products, decision services, recommendation systems and automation.', related: ['Supervised learning', 'Deep Learning', 'Inference'] },
  { term: 'Traditional AI', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A broad informal label for rule-based, search, optimization, planning and predictive approaches that predate or sit outside today’s generative-model focus.', example: 'A scheduling engine searches possible plans against constraints without generating natural-language content.', boundary: 'Traditional does not mean obsolete. Deterministic rules and optimization can be safer and more efficient for well-defined decisions.', related: ['Artificial Intelligence', 'Machine Learning', 'Generative AI'] },
  { term: 'Generative AI', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Artificial Intelligence that creates new text, images, audio, video, code or other content from learned patterns and supplied context.', example: 'A language model drafts a customer response from an approved policy and the current case details.', boundary: 'Plausible generation is not proof of truth, authorization or fitness for a consequential decision.', related: ['LLM', 'RAG', 'Grounding'] },
  { term: 'Agentic AI', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'An Artificial Intelligence system pattern that interprets a goal, plans or selects steps, uses tools, observes results and continues within stopping and authorization rules.', example: 'An operations agent gathers approved diagnostics, proposes a response and waits for human approval before changing a service.', boundary: 'Agentic behavior increases action, permission, cost and error propagation risk. Autonomy must be bounded by identity, policy, validation and human oversight.', related: ['Agent', 'Generative AI', 'Guardrail'] },
  { term: 'AI model', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A learned or programmed mathematical representation that transforms inputs into predictions, classifications, generated content or actions.', example: 'A document model maps an uploaded file to categories and confidence estimates.', boundary: 'The model is one component. The usable Artificial Intelligence system also includes data, interfaces, prompts, retrieval, tools, monitoring and people.', aliases: ['Model'], related: ['Inference', 'Foundation model', 'Evaluation'] },
  { term: 'AI evaluation', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A planned process for measuring system behavior against representative tasks, harms, constraints and acceptance criteria.', example: 'A team evaluates answer correctness, source support, refusal behavior, bias, latency and cost before and after a change.', boundary: 'One benchmark score cannot establish fitness across every user, language, condition or downstream workflow.', aliases: ['Evaluation', 'Evals'], related: ['Grounding', 'Distribution shift', 'Monitoring'] },
  { term: 'Supervised learning', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Learning from examples paired with known target labels or values.', example: 'A model learns to predict whether a payment is fraudulent from reviewed historical cases.', related: ['Machine Learning', 'Training data'] },
  { term: 'Unsupervised learning', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Finding structure or patterns in data without predefined target labels.', example: 'Clustering groups customers with similar behavior without a preassigned segment.', related: ['Machine Learning', 'Clustering'] },
  { term: 'Self-supervised learning', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Creating training signals from the data itself, often by predicting masked or related portions.', example: 'A language model learns by predicting missing or next tokens in large text collections.', related: ['Foundation model', 'Transformer', 'Training data'] },
  { term: 'Reinforcement learning', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Learning behavior through actions, feedback and accumulated reward in an environment.', example: 'A control policy learns which sequence of actions improves a simulated outcome.', boundary: 'A poorly designed reward can optimize the measurable proxy while harming the real objective.', related: ['Agent', 'Reward model'] },
  { term: 'Neural network', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A layered, parameterized mathematical model trained to transform inputs into representations or outputs.', example: 'A neural network maps image pixels to probabilities for recognized objects.', related: ['Deep Learning', 'Transformer', 'Parameter'] },
  { term: 'Deep Learning', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Machine Learning using neural networks with multiple representation-learning layers.', example: 'A deep model learns patterns in audio that support speech recognition.', related: ['Machine Learning', 'Neural network'] },
  { term: 'NLP', expansion: 'Natural Language Processing', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Methods for analyzing, generating or transforming human language.', example: 'A support system identifies intent, extracts entities and drafts a response.', where: 'Search, translation, summarization, classification, assistants and document workflows.', related: ['LLM', 'Transformer', 'Token'] },
  { term: 'Computer vision', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Methods for interpreting, generating or acting on images and video.', example: 'A quality system identifies visual defects on a production line for human review.', related: ['Multimodal AI', 'Deep Learning'] },
  { term: 'Multimodal AI', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'An Artificial Intelligence system that processes or produces more than one modality such as text, image, audio or video.', example: 'A model reads a chart, listens to a question and explains the visible trend.', related: ['Computer vision', 'NLP', 'Foundation model'] },
  { term: 'Transformer', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A neural-network architecture built around attention and widely used in language and multimodal models.', example: 'A transformer represents relationships between tokens across a document context.', related: ['Attention', 'LLM', 'Foundation model'] },
  { term: 'Attention', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A model mechanism that weighs relationships between parts of an input while constructing a representation.', example: 'Attention helps a language model relate a pronoun to an earlier noun in the context.', boundary: 'Attention weights are not automatically a reliable human explanation of a model decision.', related: ['Transformer', 'Context window'] },
  { term: 'Context window', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'The limited amount of input and generated content a model can consider during one inference.', example: 'A long document may need retrieval or chunking because it exceeds the model’s usable context.', related: ['Token', 'RAG'] },
  { term: 'Grounding', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Connecting an Artificial Intelligence output to supplied evidence, observable data, rules or a real operating context.', example: 'An answer cites a retrieved policy section and states when the source does not resolve the question.', boundary: 'Grounding reduces unsupported answers but does not guarantee the retrieved source is correct, current or sufficient.', related: ['RAG', 'Hallucination', 'Evidence'] },
  { term: 'Fine-tuning', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Further training a pretrained model on selected examples to adapt behavior or task performance.', example: 'A model is tuned on reviewed examples of the organization’s classification task.', boundary: 'Fine-tuning changes learned behavior; it is not the same as retrieving current private documents at inference time.', related: ['RAG', 'Foundation model', 'Training data'] },
  { term: 'Overfitting', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'Learning development data too specifically so performance does not generalize reliably to new cases.', example: 'A model scores extremely well on training examples but fails on later customer data.', related: ['Distribution shift', 'Evaluation'] },
  { term: 'Distribution shift', category: 'Artificial intelligence', domainSlug: 'artificial-intelligence', meaning: 'A material difference between development data or conditions and the environment encountered later.', example: 'A model trained on one product region loses accuracy after a policy and customer mix change.', related: ['Monitoring', 'Overfitting', 'Evaluation'] },

  { term: 'DLT', expansion: 'Distributed Ledger Technology', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'A shared record maintained across multiple participants through agreed update and validation rules.', example: 'Several organizations maintain a common asset-transfer history without one participant owning the only ledger.', related: ['Blockchain', 'Consensus mechanism'] },
  { term: 'Blockchain', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'A distributed-ledger pattern that groups records into cryptographically linked blocks.', example: 'A permissioned consortium records approved supply-chain events on a shared ledger.', boundary: 'A blockchain does not make incorrect input truthful, remove governance or guarantee privacy.', related: ['DLT', 'Smart contract', 'Blockchain oracle'] },
  { term: 'Consensus mechanism', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'Rules through which distributed participants agree on accepted ledger state.', example: 'Validator nodes follow a protocol to decide which proposed transaction history becomes authoritative.', related: ['Blockchain', 'DLT'] },
  { term: 'Smart contract', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'Program logic deployed on a distributed ledger that executes according to defined inputs and state.', example: 'A contract releases a tokenized asset after approved conditions are recorded.', boundary: 'A smart contract can contain software defects and still depends on governance, keys and external data.', related: ['Blockchain oracle', 'Blockchain'] },
  { term: 'Permissioned ledger', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'A distributed ledger where participation and roles are controlled by an identified authority or consortium.', example: 'Only approved banks can operate validating nodes in a settlement network.', related: ['DLT', 'Consensus mechanism'] },
  { term: 'Tokenization', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'Representing a right, claim, asset or unit of value as a digital token within a system.', example: 'A token represents a defined claim on an asset while legal ownership remains governed by applicable agreements and law.', boundary: 'The token and the underlying legal right are not automatically identical.', related: ['Smart contract', 'Blockchain'] },
  { term: 'Blockchain oracle', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'A mechanism that supplies a smart contract with information from outside its ledger.', example: 'An oracle provides a verified market price used by a contract.', boundary: 'An oracle creates a trust and integrity dependency between the external world and on-ledger logic.', related: ['Smart contract', 'Data integrity'] },
  { term: 'Qubit', expansion: 'Quantum bit', category: 'Quantum', domainSlug: 'emerging-technology', meaning: 'The basic unit of quantum information represented by a quantum state.', example: 'A quantum algorithm manipulates a system of qubits before measurement produces classical outcomes.', related: ['Superposition', 'Quantum entanglement'] },
  { term: 'Superposition', category: 'Quantum', domainSlug: 'emerging-technology', meaning: 'A quantum state represented as a combination of possible basis states until measured.', example: 'A qubit can be prepared in a state described by amplitudes for two basis outcomes.', boundary: 'It does not mean a classical object simply holds two ordinary values at once.', related: ['Qubit', 'Quantum entanglement'] },
  { term: 'Quantum entanglement', category: 'Quantum', domainSlug: 'emerging-technology', meaning: 'A relationship in which parts of a quantum system have correlated states that must be described together.', example: 'Measurements on entangled qubits show correlations described by their joint state.', related: ['Qubit', 'Superposition'] },
  { term: 'PQC', expansion: 'Post-Quantum Cryptography', category: 'Quantum', domainSlug: 'emerging-technology', meaning: 'Cryptographic algorithms designed to resist attacks from sufficiently capable quantum computers while running on conventional systems.', example: 'An organization inventories vulnerable public-key cryptography and plans tested migration to standardized post-quantum algorithms.', related: ['Cryptographic agility', 'Harvest now, decrypt later'] },
  { term: 'Cryptographic agility', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'The ability to discover, replace and migrate cryptographic algorithms, keys and protocols without rebuilding an entire service.', example: 'A protocol can negotiate a new approved algorithm while inventories identify every dependent certificate and library.', related: ['PQC', 'PKI', 'Encryption'] },
  { term: 'Harvest now, decrypt later', category: 'Quantum', domainSlug: 'emerging-technology', meaning: 'A threat in which encrypted data is collected today for possible decryption when future capabilities become available.', example: 'Long-lived sensitive records justify earlier cryptographic migration even before a large quantum computer exists.', related: ['PQC', 'Cryptographic agility'] },
  { term: 'Edge computing', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'Processing data close to its source or user to reduce latency, bandwidth dependence or disconnected-operation risk.', example: 'A factory gateway analyzes sensor readings locally and sends summarized events to the cloud.', boundary: 'Edge deployment distributes patching, identity, physical protection and lifecycle responsibilities.', related: ['IoT', 'Cloud', 'Digital twin'] },
  { term: 'Digital twin', category: 'Emerging technology', domainSlug: 'emerging-technology', meaning: 'A maintained digital representation of a physical asset or process used for observation, simulation or optimization.', example: 'A turbine twin combines design data, sensor state and maintenance history to test operating scenarios.', boundary: 'A stale or poorly calibrated twin can create confident but unsafe decisions.', related: ['IoT', 'OT', 'Data lineage'] },

  { term: 'Personal data', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'Information relating to an identified or identifiable person, with exact scope determined by the applicable law.', example: 'A customer identifier becomes personal data when it can be connected to a person.', related: ['Processing', 'Data subject', 'Data minimization'] },
  { term: 'Processing', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'An operation performed on personal data, such as collection, use, disclosure, storage, modification or deletion.', example: 'Copying an employee file into an analytics system is processing even if no decision is yet made.', related: ['Personal data', 'Controller', 'Processor'] },
  { term: 'Data subject', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'The person to whom personal data relates in General Data Protection Regulation terminology.', example: 'A customer exercises a right concerning information held about that customer.', related: ['Personal data', 'Controller'] },
  { term: 'Controller', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'The party that determines why and how personal data is processed in General Data Protection Regulation-oriented terminology.', example: 'A retailer decides the purposes and means of its customer-loyalty processing.', boundary: 'Contract labels do not override the real allocation of decisions and responsibilities.', related: ['Processor', 'Data subject'] },
  { term: 'Processor', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'A party processing personal data on behalf of a controller in General Data Protection Regulation-oriented terminology.', example: 'A hosted payroll provider processes employee data under documented instructions.', related: ['Controller', 'Processing'] },
  { term: 'Data Principal', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'The individual to whom personal data relates under India’s Digital Personal Data Protection Act terminology.', example: 'A person uses the statutory grievance route for processing of that person’s data.', related: ['Data Fiduciary', 'India DPDP Act and Rules'] },
  { term: 'Data Fiduciary', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'The person who determines the purpose and means of processing personal data under India’s Digital Personal Data Protection Act terminology.', example: 'An online service determines why customer profile data is collected and how it is used.', related: ['Data Principal', 'India DPDP Act and Rules'] },
  { term: 'Consent', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'A person’s agreement to specified processing, subject to the quality and withdrawal requirements of the applicable law.', example: 'A service records the notice version, purpose, affirmative action and later withdrawal.', boundary: 'Consent is not always the only available or appropriate legal ground.', related: ['Lawful basis', 'Purpose limitation'] },
  { term: 'Lawful basis', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'A legally recognized justification for processing personal data.', example: 'A controller documents why a processing purpose relies on contract, legal obligation or another applicable basis.', boundary: 'The available grounds and required analysis depend on the governing law.', related: ['Consent', 'Processing'] },
  { term: 'Purpose limitation', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'Using personal data only for specified and legitimate purposes rather than unrelated later uses.', example: 'Delivery-address data is not silently reused for a new profiling purpose without analysis and required transparency.', related: ['Data minimization', 'Storage limitation'] },
  { term: 'Data minimization', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'Collecting and using only personal data that is necessary and proportionate for the stated purpose.', example: 'An age-eligibility check records the result instead of retaining a full identity document when not needed.', related: ['Purpose limitation', 'Storage limitation'] },
  { term: 'Storage limitation', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'Retaining personal data only for as long as the purpose and applicable obligations justify.', example: 'A retention schedule defines a trigger, period, exception and verified deletion action.', related: ['Data minimization', 'Records management'] },
  { term: 'Privacy by design and default', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'Building privacy principles into system and process design and making protective settings the ordinary starting state.', example: 'A new profile is private by default and exposes only fields necessary for the selected service.', related: ['DPIA', 'Data minimization'] },
  { term: 'DPIA', expansion: 'Data Protection Impact Assessment', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'A structured evaluation of privacy risk and safeguards for processing likely to create consequential risk.', example: 'A biometric-access proposal maps necessity, people affected, risks, alternatives and approved mitigations before use.', related: ['Privacy by design and default', 'Data minimization'] },
  { term: 'DPO', expansion: 'Data Protection Officer', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'A formally designated privacy oversight role required in specified circumstances under some laws.', example: 'A Data Protection Officer advises on impact assessment and monitors compliance while retaining appropriate independence.', boundary: 'The role, independence and mandatory appointment conditions depend on the governing law.', related: ['DPIA', 'Accountability'] },
  { term: 'Personal data breach', category: 'Privacy', domainSlug: 'privacy-law', meaning: 'A security breach affecting the confidentiality, integrity or availability of personal data.', example: 'A misdirected file containing customer records triggers a documented breach assessment.', boundary: 'Not every security event becomes a reportable breach, but every credible event needs timely triage against the applicable rule.', related: ['Incident', 'Personal data'] },

  { term: 'Governance', category: 'Governance', domainSlug: 'governance-assurance', meaning: 'The system through which direction is set, authority is exercised, accountability is assigned and performance is overseen.', example: 'A board approves risk appetite while management assigns owners and reports outcomes.', related: ['Accountability', 'Policy', 'COBIT 2019'] },
  { term: 'Accountability', category: 'Governance', domainSlug: 'governance-assurance', meaning: 'The obligation to answer for a decision, action or outcome and support it with appropriate evidence.', example: 'A service owner approves residual risk and records the basis, conditions and review date.', related: ['Governance', 'Evidence'] },
  { term: 'Policy hierarchy', category: 'Governance', domainSlug: 'governance-assurance', meaning: 'The relationship among policies, standards, procedures, guidelines and supporting records.', example: 'A policy requires protection, a standard sets the approved method, and a procedure explains how an operator performs it.', related: ['Policy', 'Standard', 'Procedure'] },
  { term: 'Control objective', category: 'Control', domainSlug: 'governance-assurance', meaning: 'The intended condition or outcome a control or group of controls is meant to achieve.', example: 'Only authorized changes reach production and every release is traceable to approval and test evidence.', related: ['Control', 'Control design'] },
  { term: 'Control owner', category: 'Control', domainSlug: 'governance-assurance', meaning: 'The person accountable for ensuring a control is appropriately designed, operated, monitored and improved.', example: 'The identity-platform owner reviews access-review completion and resolves recurring exceptions.', related: ['Control design', 'Accountability'] },
  { term: 'Control design', category: 'Control', domainSlug: 'governance-assurance', meaning: 'The documented mechanism, responsibility, frequency, population and evidence through which a control should achieve its objective.', example: 'A joiner workflow states its trigger, approval, access rules, completion target, exception path and audit record.', related: ['Control objective', 'Operating effectiveness'] },
  { term: 'Operating effectiveness', category: 'Assurance', domainSlug: 'governance-assurance', meaning: 'The extent to which a suitably designed control actually worked across the relevant period and population.', example: 'An assessor samples completed access reviews and checks timeliness, coverage, decisions and follow-up.', related: ['Control design', 'Control testing'] },
  { term: 'Preventive control', category: 'Control', domainSlug: 'governance-assurance', meaning: 'A control intended to stop an unwanted event before it occurs.', example: 'A delivery policy blocks unsigned code from entering the production release path.', related: ['Detective control', 'Corrective control'] },
  { term: 'Detective control', category: 'Control', domainSlug: 'governance-assurance', meaning: 'A control intended to identify an unwanted event or condition after or while it occurs.', example: 'A reconciliation identifies a transaction that did not reach the ledger correctly.', related: ['Preventive control', 'Corrective control'] },
  { term: 'Corrective control', category: 'Control', domainSlug: 'governance-assurance', meaning: 'A control intended to restore an acceptable state and address the effects or cause of a problem.', example: 'A tested recovery process restores a corrupted configuration and validates service integrity.', related: ['Preventive control', 'Detective control'] },
  { term: 'Compensating control', category: 'Control', domainSlug: 'governance-assurance', meaning: 'An alternative measure used when the preferred control is unavailable while aiming to address comparable risk.', example: 'A legacy system without modern authentication is isolated behind a monitored access gateway while replacement proceeds.', boundary: 'A compensating control needs an explicit objective, risk comparison, owner, evidence and expiry or review date.', related: ['Residual risk', 'Control design'] },
  { term: 'Control deficiency', category: 'Assurance', domainSlug: 'governance-assurance', meaning: 'A weakness in control design or operation that may prevent the control objective from being achieved.', example: 'A quarterly review omitted part of the population because the source inventory was incomplete.', related: ['Control testing', 'Operating effectiveness'] },
  { term: 'Control testing', category: 'Assurance', domainSlug: 'governance-assurance', meaning: 'An evidence-based assessment of control design, implementation or operating effectiveness.', example: 'A tester defines the population, selects samples, inspects evidence, records exceptions and reaches a scoped conclusion.', related: ['Control design', 'Operating effectiveness', 'Evidence'] },
  { term: 'RCSA', expansion: 'Risk and Control Self-Assessment', category: 'Governance', domainSlug: 'governance-assurance', meaning: 'A structured process through which responsible teams identify risks, evaluate controls and document resulting actions.', example: 'A business process owner updates scenarios, assesses control effectiveness and agrees remediation with oversight.', boundary: 'Self-assessment is management evidence, not independent assurance.', related: ['Risk assessment', 'Three Lines Model'] },
  { term: 'Three Lines Model', category: 'Governance', domainSlug: 'governance-assurance', meaning: 'A governance model distinguishing management responsibility, specialist support and challenge, and independent internal audit assurance.', example: 'The product team owns risk, a specialist risk function advises and challenges, and internal audit independently evaluates governance and controls.', boundary: 'The lines describe roles, not three isolated departments or a sequence that transfers ownership away from management.', related: ['Governance', 'Audit', 'Accountability'] },
  { term: 'Statement of Applicability', expansion: 'SoA', category: 'Assurance', domainSlug: 'governance-assurance', meaning: 'An ISO/IEC 27001 document identifying selected controls, inclusion or exclusion decisions and supporting justification.', example: 'The Information Security Management System records why a control applies, how it is implemented and where evidence sits.', related: ['ISO/IEC 27001', 'Control design'] },
];
