import type { Topic } from './topics';

export type GuideOpener = { analogy: string; picture: string; remember: string };

const openers: Record<string, GuideOpener> = {
  'business-to-technology-map': { analogy: 'Think of a restaurant. The menu is the promise, the kitchen is the operating model, the order ticket is data, and the meal is the customer outcome.', picture: 'Technology only has meaning when you can trace it to a decision, service or obligation.', remember: 'Begin with the outcome. Then find the process, system, data, owner, failure and evidence behind it.' },
  'network-foundations-and-protocol-models': { analogy: 'Sending data is like sending a parcel through nested delivery systems. Each layer adds information needed by the next handler, and the receiver unwraps it in reverse.', picture: 'The OSI model is a troubleshooting lens, not seven separate machines. A real packet crosses media, network paths, transport conversations and application rules.', remember: 'Ask which layer owns the symptom, which layer can observe it and where trust changes.' },
  'man-in-the-middle-spoofing-and-transport-trust': { analogy: 'Imagine handing a sealed envelope to someone wearing a courier uniform. Encryption protects the contents, but only if you verify the courier and the destination rather than trusting the uniform.', picture: 'An interception attack succeeds by entering a path or corrupting a trust decision: local addressing, wireless identity, name resolution, routing, proxy trust or certificate validation.', remember: 'Ask who authenticated whom, which path was trusted, what was encrypted, and whether freshness and integrity were verified.' },
  'linux-users-groups-and-file-permissions': { analogy: 'A Linux file is like a room with three audiences: the owner, a named group and everyone else. Read, write and execute are three different keys.', picture: 'The familiar 755 or 640 notation is just three permission groups written as octal numbers.', remember: 'Permissions are evaluated with ownership, groups, directory behavior, Access Control Lists and the process identity.' },
  'linux-administration-patching-and-hardening': { analogy: 'Hardening is like preparing a hotel for guests: close unused entrances, issue only the right keys, keep records, inspect rooms and rehearse emergencies.', picture: 'A hardened host has fewer unnecessary services, timely patches, constrained identities, useful logs and tested recovery.', remember: 'A checklist is a starting baseline. The real result is a host that is necessary, patched, observable, recoverable and owned.' },
  'enterprise-technology-and-cyber-risk-management': { analogy: 'Risk management is route planning in bad weather. You care about the destination, the conditions, the available safeguards and who can decide whether to continue.', picture: 'Risk is uncertainty around an objective, expressed through a plausible scenario and consequence.', remember: 'Name the objective, cause, event, consequence, controls, current residual exposure and decision owner.' },
  'risk-foundations-taxonomies-appetite-and-tolerance': { analogy: 'Risk appetite is the speed a driver is generally willing to accept. Tolerance is the boundary that triggers action. Capacity is the point beyond which the organization may not survive.', picture: 'Categories help organize risk, but the decision happens in a scenario with an owner, controls and consequences.', remember: 'Never say “residual risk” without stating which controls received credit and whether the value is current or target.' },
  'control-design-operation-testing-and-evidence': { analogy: 'A smoke alarm is only useful if it is installed in the right place, powered, audible, tested and linked to a response. A policy saying “have alarms” is not operating evidence.', picture: 'Control design explains how risk should change. Operating evidence shows whether that design actually ran for the required population and period.', remember: 'Separate purpose, design, implementation, operation, evidence, testing and remediation.' },
  'digital-identity-directories-and-the-identity-lifecycle': { analogy: 'An identity is a person’s institutional record; an account is one door key; a session is the temporary wristband issued after the key is checked.', picture: 'Identity lifecycle joins authoritative records, directories, accounts, roles, authenticators, sessions and reviews.', remember: 'One person can have many accounts, and many important identities are not people at all.' },
  'authentication-and-authenticators': { analogy: 'Showing a passport proves something about who you are. A boarding pass proves what trip you may take. Authentication and authorization answer different questions.', picture: 'Authentication establishes confidence in an identity claim using one or more authenticators and context.', remember: 'Strong authentication still needs safe enrollment, recovery, session management and phishing resistance.' },
  'security-operations-detection-and-threat-intelligence': { analogy: 'A Security Operations Center is closer to an emergency department than a CCTV room. Signals arrive incomplete, triage matters, specialists need context and every action must be recorded.', picture: 'Telemetry becomes a detection only after reliable collection, analytical logic, context, validation, triage and feedback.', remember: 'An alert is a prompt to investigate, not proof of compromise.' },
  'generative-ai-large-language-models-retrieval-and-agents': { analogy: 'A language model is a fluent pattern-completer. Retrieval gives it an open notebook. Tools give it hands. An agent adds a loop that can choose and repeat actions.', picture: 'Useful AI systems combine models with instructions, context, retrieval, tools, permissions, evaluation and human oversight.', remember: 'Grounding can improve relevance, but it does not guarantee truth, authorization or safe action.' },
  'artificial-intelligence-and-machine-learning-foundations': { analogy: 'Traditional software follows rules written by people. Machine learning estimates a rule from examples, then applies that learned pattern to new inputs.', picture: 'AI is the umbrella. Machine learning is one approach. Deep learning uses layered neural networks. Generative systems produce new content from learned patterns.', remember: 'Always separate the model, the surrounding system, the task, the data and the decision consequence.' },
  'cloud-fundamentals-and-shared-responsibility': { analogy: 'Cloud is like renting part of a managed building. The landlord runs some infrastructure, but you still decide who gets keys, what you store and how you recover your work.', picture: 'Responsibility moves with the service model. It does not disappear.', remember: 'For every workload, write down what the provider operates, what the customer configures and how each side proves recovery and security.' },
  'software-development-life-cycle-and-delivery-methods': { analogy: 'Building software is more like running a living city than finishing a sculpture. Requirements change, dependencies age, residents find new uses and maintenance never ends.', picture: 'The lifecycle connects discovery, design, build, verification, release, operation, change and retirement.', remember: 'A release is one controlled transition in a much longer product and service lifecycle.' },
  'software-vulnerability-families-and-secure-coding': { analogy: 'Treat external input like freight arriving at a secure warehouse. Check the label and dimensions, but also keep the cargo separated from control machinery, enforce who may move it and make the handling safe when two deliveries arrive together.', picture: 'A vulnerability appears when an unsafe assumption crosses a boundary involving memory, syntax, time, identity, authority or device trust.', remember: 'Name the invariant, use a safe interface, test the hostile edge case and connect the defect to a business consequence.' },
  'password-attacks-offline-cracking-and-authentication-defense': { analogy: 'Online guessing is trying keys at a guarded door, where guards can slow and observe you. Offline cracking is stealing a copy of the lock mechanism and testing keys in a private workshop where the building cannot rate-limit you.', picture: 'The same password faces different economics depending on whether the attacker talks to the live verifier or possesses its stored hash.', remember: 'Separate candidate strategy, verifier location, storage resistance, live-service controls and the authority required to test.' },
  'internal-audit-planning-engagements-findings-and-follow-up': { analogy: 'Internal audit is the organization’s independent mirror. It does not drive the car or choose the route; it shows the board whether the controls and risk decisions are working as represented.', picture: 'A good engagement moves from mandate and risk-based scope to evidence, evaluation, communication and verified follow-up.', remember: 'Internal Audit provides assurance and advice. Management owns the risks, controls and remediation.' },
  'sox-icfr-itgc-and-application-controls': { analogy: 'Financial statements are the final scoreboard. SOX work asks whether the scoring system, source records, calculations, approvals and technology can be trusted.', picture: 'Internal Control over Financial Reporting connects financial risks to entity, process, application and Information Technology General Controls.', remember: 'A technology control matters to SOX only when it supports a financially relevant risk, process or system dependency.' },
};

const categoryOpeners: Record<Topic['category'], (title: string) => GuideOpener> = {
  orientation: (title) => ({ analogy: `Learning ${title.toLowerCase()} is like learning a city from its streets rather than memorizing a list of buildings. The routes and connections explain how the place actually works.`, picture: 'Keep the outcome, the moving parts, the failure points and the evidence in the same view.', remember: 'A useful map should help you ask a better question or make a better decision.' }),
  business: (title) => ({ analogy: `${title} is like the backstage operation of a theatre. The audience sees the performance, while roles, timing, money, handoffs and recovery determine whether the promise is kept.`, picture: 'Trace the need through the operating model to the delivered outcome and its full cost.', remember: 'Activity is not value. Name who benefits, what changes and how the result is measured.' }),
  systems: (title) => ({ analogy: `${title} is like the plumbing in a tall building. Most people notice it only when pressure, routing, capacity or a hidden dependency fails.`, picture: 'Locate the component, its interfaces, its state, its dependencies and the signals it emits.', remember: 'Troubleshoot from evidence: symptom, boundary, dependency, signal, test, conclusion.' }),
  software: (title) => ({ analogy: `${title} is like changing a busy railway timetable. A small edit can affect many routes, so design, testing, release, observation and rollback belong to one decision.`, picture: 'Follow the change from a user need through code and dependencies into production behavior.', remember: 'Software is complete only when it can be operated, recovered, changed and retired safely.' }),
  cloud: (title) => ({ analogy: `${title} is like renting a fitted commercial kitchen. The provider runs some layers, but your team still controls ingredients, access, configuration, recipes and recovery.`, picture: 'Draw the provider and customer boundary for identity, network, workload, data, monitoring and recovery.', remember: 'Managed does not mean ownerless. Verify the responsibility for every important failure.' }),
  cyber: (title) => ({ analogy: `${title} is like protecting a museum during opening hours. Locks matter, but so do visitor routes, staff behavior, surveillance, response authority and proof that controls worked.`, picture: 'Start with a plausible harm path, then place preventive, detective, corrective and recovery capability along it.', remember: 'A security product is not a control outcome until it is configured, operated, tested and connected to response.' }),
  governance: (title) => ({ analogy: `${title} is like the rules and recordkeeping of a professional sport. The rulebook, referee, team manager and independent review each have different authority.`, picture: 'Separate who directs, who owns, who performs, who challenges and what evidence reaches oversight.', remember: 'A policy states intent. Governance becomes real through decisions, operation, evidence and consequence.' }),
  risk: (title) => ({ analogy: `${title} is like planning a mountain route. Weather, skill, equipment, alternatives and the point at which you turn back matter because the objective is to return safely, not merely reach the summit.`, picture: 'Write the objective, cause, event, consequence, controls, uncertainty and decision threshold.', remember: 'A risk category files the issue. A risk scenario makes it possible to decide.' }),
  data: (title) => ({ analogy: `${title} is like working with ingredients in a shared kitchen. Labels, source, freshness, transformations and permitted use determine whether the final dish can be trusted.`, picture: 'Trace meaning and ownership from the source through every copy, transformation and decision.', remember: 'A number without definition, lineage and context is not reliable evidence.' }),
  ai: (title) => ({ analogy: `${title} is like employing a fast junior researcher with an unusual memory. It can be useful, but the brief, sources, permissions, review and consequence of error still belong to the surrounding system.`, picture: 'Separate the model from its data, context, retrieval, tools, interface, evaluation and human decision.', remember: 'Fluent output is behavior, not proof. Test the task, the system and the real consequence.' }),
  emerging: (title) => ({ analogy: `${title} is like testing a new material for a bridge. A striking laboratory result is only the beginning; standards, maintainability, suppliers, safety and failure behavior decide whether it belongs in service.`, picture: 'Move from claim to evidence, prototype, operating fit, controlled trial and a reversible adoption decision.', remember: 'Novelty is not maturity. Set learning goals, limits and a stop condition before scaling.' }),
  industries: (title) => ({ analogy: `${title} is like using the same vehicle in a city, a mine and an airport. The machinery may be familiar, but the consequence, rules and recovery expectations change the design.`, picture: 'Begin with the industry value chain, crown jewels, failure consequences and operating constraints.', remember: 'Context changes control strength. Copying another industry can create confident but unsafe design.' }),
  people: (title) => ({ analogy: `${title} is like playing in an ensemble. Technical skill matters, but timing, listening, handoffs and adjustment determine whether the group produces something coherent.`, picture: 'Notice what the other person needs to understand, decide or do next.', remember: 'Clarity is measured by shared understanding and follow-through, not by how much was said.' }),
  ecosystem: (title) => ({ analogy: `${title} is like reading labels in a medicine cabinet. Regulator, standards body, certification scheme, professional association and vendor may all publish advice, but their authority is not interchangeable.`, picture: 'Check the body, mandate, jurisdiction, audience, version, adoption route and primary source.', remember: 'Recognition does not make guidance mandatory. Authority comes from law, contract, adoption or explicit governance.' }),
};

export function guideOpenerFor(slug: string, topic?: Pick<Topic, 'category' | 'title'>) {
  return openers[slug] ?? (topic ? categoryOpeners[topic.category](topic.title) : undefined);
}
