export type IndustryChainStage = {
  id: string;
  label: string;
  outcome: string;
  systems: string[];
  data: string[];
  people: string[];
  failureModes: string[];
  controls: string[];
  evidence: string[];
};

export type IndustryChain = {
  industrySlug: string;
  title: string;
  dominantConsequence: string;
  feedback: string;
  stages: IndustryChainStage[];
};

const list = (value: string) => value.split('|');

function stage(id: string, label: string, outcome: string, systems: string, data: string, people: string, failureModes: string, controls: string, evidence: string): IndustryChainStage {
  return { id, label, outcome, systems: list(systems), data: list(data), people: list(people), failureModes: list(failureModes), controls: list(controls), evidence: list(evidence) };
}

export const industryChains: IndustryChain[] = [
  {
    industrySlug: 'financial-services', title: 'Financial services', dominantConsequence: 'Trust depends on accurate value movement, strong authorization, liquidity and complete books and records.', feedback: 'Exceptions, fraud outcomes, complaints, losses and regulatory findings reshape product rules, models and limits.',
    stages: [
      stage('fs-acquire', 'Acquire and verify', 'Establish a legitimate customer, purpose and risk profile.', 'Digital onboarding|Identity verification|Customer master', 'Identity evidence|Consent and disclosures|Risk classification', 'Customer|Operations reviewer|Compliance owner', 'Impersonation|Exclusion of a legitimate customer|Weak due diligence', 'Identity proofing|Sanctions and screening workflow|Manual exception review', 'Verification result|Reviewer decision|Notice and consent record'),
      stage('fs-fund', 'Accept funds or capital', 'Receive value into the correct account with traceable origin.', 'Payment rails|Core ledger|Fraud monitoring', 'Payment instruction|Account state|Source-of-funds signals', 'Customer|Treasury operations|Fraud analyst', 'Misdirected funds|Account takeover|Duplicate posting', 'Strong transaction authentication|Limits and anomaly checks|Idempotent posting', 'Authentication event|Payment message|Ledger entry'),
      stage('fs-transact', 'Lend, invest, pay or insure', 'Execute an authorized financial decision within product and risk rules.', 'Decision engine|Trading or payment gateway|Policy administration', 'Order or application|Limit and model result|Approval', 'Customer|Product owner|Risk approver', 'Fraud|Model error|Unauthorized or unsuitable transaction', 'Segregation of duties|Limit checks|Human approval for defined cases', 'Decision trace|Approval record|Model and rule version'),
      stage('fs-settle', 'Clear and settle', 'Exchange final obligations and assets accurately and on time.', 'Clearing network|Settlement account|Market infrastructure', 'Matched instruction|Position|Settlement status', 'Operations|Counterparty|Treasury', 'Failed settlement|Liquidity shortfall|Counterparty mismatch', 'Confirmation and matching|Liquidity monitoring|Cutoff management', 'Matched confirmation|Settlement message|Exception queue'),
      stage('fs-reconcile', 'Reconcile and report', 'Prove that records agree and explain every material exception.', 'General ledger|Reconciliation platform|Regulatory reporting', 'Sub-ledger balance|General-ledger balance|Exception and adjustment', 'Finance controller|Operations owner|Regulatory reporting', 'Unexplained difference|Late correction|Misstatement', 'Independent reconciliation|Aged-exception escalation|Report validation', 'Reconciliation sign-off|Adjustment approval|Filed report'),
    ],
  },
  {
    industrySlug: 'manufacturing', title: 'Manufacturing and industrial operations', dominantConsequence: 'A digital failure can change physical safety, product quality, equipment integrity and production availability.', feedback: 'Quality escapes, downtime, maintenance findings and safety events update design tolerances, supplier controls and operating procedures.',
    stages: [
      stage('mfg-design', 'Design', 'Turn a need into a manufacturable product and controlled process.', 'Product Lifecycle Management|Engineering workstations|Simulation', 'Bill of materials|Design file|Process specification', 'Engineer|Safety specialist|Product owner', 'Unsafe requirement|Stolen intellectual property|Uncontrolled design change', 'Design review|Version control|Segregated engineering access', 'Approved drawing|Review record|Change history'),
      stage('mfg-source', 'Source', 'Obtain authentic materials and services from capable suppliers.', 'Supplier portal|Enterprise Resource Planning|Quality system', 'Supplier qualification|Purchase order|Material certificate', 'Procurement|Quality engineer|Supplier owner', 'Counterfeit component|Single-source dependency|Compromised supplier access', 'Supplier assurance|Incoming verification|Contract and access controls', 'Qualification record|Certificate validation|Receipt inspection'),
      stage('mfg-plan', 'Plan', 'Translate demand, capacity and constraints into a feasible schedule.', 'Enterprise Resource Planning|Advanced planning|Warehouse management', 'Forecast|Capacity|Inventory|Production order', 'Planner|Operations manager|Maintenance lead', 'Bad demand signal|Unavailable equipment|Unsafe schedule pressure', 'Data-quality checks|Capacity constraints|Maintenance and safety gates', 'Approved schedule|Constraint exception|Planner override'),
      stage('mfg-produce', 'Produce', 'Operate equipment within approved recipe, sequence and safety limits.', 'Manufacturing Execution System|Programmable Logic Controllers|Human-Machine Interfaces', 'Recipe|Set point|Machine state|Operator action', 'Operator|Control engineer|Shift supervisor', 'Unsafe command|Ransomware outage|Recipe manipulation', 'IT and OT segmentation|Role-limited commands|Safety interlocks', 'Controller change log|Batch record|Alarm history'),
      stage('mfg-inspect', 'Inspect', 'Verify output against specification before release.', 'Quality Management System|Vision inspection|Laboratory system', 'Sample result|Defect record|Release decision', 'Quality inspector|Laboratory analyst|Release authority', 'False pass|Tampered result|Unrepresentative sampling', 'Calibrated equipment|Independent release|Data-integrity controls', 'Calibration record|Test result|Release sign-off'),
      stage('mfg-distribute', 'Store and distribute', 'Preserve identity, condition and custody through delivery.', 'Warehouse management|Transport management|Sensors', 'Lot and serial number|Location|Condition|Custody event', 'Warehouse operator|Logistics provider|Customer service', 'Wrong shipment|Temperature excursion|Counterfeit substitution', 'Barcode or tag verification|Condition monitoring|Chain of custody', 'Pick and pack record|Sensor history|Delivery confirmation'),
      stage('mfg-maintain', 'Maintain', 'Restore reliable equipment without introducing unsafe change.', 'Computerized maintenance system|Remote support gateway|Configuration backup', 'Work order|Asset configuration|Maintenance history', 'Maintenance engineer|Vendor technician|Operations approver', 'Overprivileged vendor|Wrong firmware|Unrecoverable configuration', 'Time-limited remote access|Safe change window|Tested configuration restore', 'Session recording|Work completion|Before and after configuration'),
    ],
  },
  {
    industrySlug: 'healthcare', title: 'Healthcare and life sciences', dominantConsequence: 'Patient safety and continuity of care must be protected alongside privacy, research integrity and product quality.', feedback: 'Clinical outcomes, adverse events, device signals and research findings update care pathways, product controls and risk decisions.',
    stages: [
      stage('hc-prevent', 'Prevent and diagnose', 'Identify risk or condition early with reliable evidence.', 'Electronic health record|Imaging|Laboratory system', 'Patient identity|Observation|Image or result', 'Patient|Clinician|Laboratory professional', 'Patient mismatch|False result|Delayed diagnosis', 'Positive identification|Result verification|Critical-result escalation', 'Order and result|Identity check|Clinical acknowledgement'),
      stage('hc-treat', 'Treat and monitor', 'Deliver the right intervention and detect harmful change.', 'Medication system|Medical device|Clinical monitoring', 'Order|Dose or setting|Vital signal|Alert', 'Clinician|Pharmacist|Biomedical engineer', 'Wrong dose|Unsafe device behavior|Alert fatigue', 'Clinical authorization|Device configuration control|Alarm governance', 'Administration record|Device log|Alert response'),
      stage('hc-coordinate', 'Coordinate care', 'Share sufficient, accurate information across the care team.', 'Electronic health record|Referral platform|Health-information exchange', 'Care plan|Referral|Discharge summary', 'Care team|Patient|External provider', 'Missing handoff|Excess disclosure|Unavailable record', 'Role and relationship access|Minimum necessary sharing|Downtime procedure', 'Access log|Handoff record|Downtime reconciliation'),
      stage('hc-research', 'Research and develop', 'Generate trustworthy evidence while protecting participants.', 'Clinical trial system|Research data platform|Laboratory informatics', 'Protocol|Consent|Observation|Analysis dataset', 'Investigator|Participant|Ethics and quality reviewer', 'Protocol deviation|Re-identification|Manipulated result', 'Protocol and consent control|De-identification|Data lineage and review', 'Consent version|Protocol deviation|Analysis provenance'),
      stage('hc-manufacture', 'Manufacture and distribute therapy', 'Release a safe, effective and traceable product.', 'Manufacturing Execution System|Quality system|Cold-chain monitoring', 'Batch record|Test result|Serial and condition', 'Qualified person|Manufacturer|Distributor', 'Contamination|Falsified record|Temperature excursion', 'Validated process|Independent batch release|Track and trace', 'Electronic batch record|Release decision|Condition history'),
    ],
  },
  {
    industrySlug: 'retail', title: 'Retail, e-commerce and consumer services', dominantConsequence: 'High-volume journeys depend on payment integrity, order accuracy, trust and availability during sharp demand peaks.', feedback: 'Returns, fraud, conversion, fulfillment delays and complaints reshape assortment, controls and customer experience.',
    stages: [
      stage('retail-plan', 'Plan assortment', 'Choose products, price and inventory around evidence of demand.', 'Merchandising platform|Forecasting|Product-information system', 'Demand forecast|Product master|Price and margin', 'Buyer|Merchandiser|Finance partner', 'Bad forecast|Unauthorized price|Biased targeting', 'Approval limits|Data-quality review|Scenario testing', 'Forecast version|Price approval|Assumption log'),
      stage('retail-source', 'Source inventory', 'Acquire authentic inventory in the right volume and condition.', 'Supplier portal|Procurement|Inventory system', 'Supplier record|Purchase order|Shipment status', 'Procurement|Supplier|Quality owner', 'Counterfeit goods|Supplier failure|Incorrect quantity', 'Supplier qualification|Receipt verification|Dual sourcing where justified', 'Supplier review|Purchase order|Inspection record'),
      stage('retail-sell', 'Market and sell', 'Present an accurate offer and accept a legitimate order.', 'Commerce platform|Customer identity|Marketing technology', 'Catalog|Customer session|Cart and order', 'Customer|Product team|Marketing owner', 'Account takeover|Dark pattern|Third-party script compromise', 'Secure session|Consent and preference control|Script inventory and policy', 'Session event|Consent record|Order confirmation'),
      stage('retail-pay', 'Take payment', 'Authorize payment without exposing account data or creating unnecessary friction.', 'Payment gateway|Fraud engine|Point of sale', 'Payment token|Risk signal|Authorization result', 'Customer|Cashier or channel|Fraud analyst', 'Payment fraud|Skimming|False decline', 'Tokenization|Payment segmentation|Risk-based step-up', 'Authorization log|Fraud decision|Payment exception'),
      stage('retail-fulfil', 'Fulfil and deliver', 'Pick, pack and deliver the correct order with visible custody.', 'Order management|Warehouse automation|Delivery platform', 'Inventory location|Pick list|Tracking event', 'Warehouse team|Carrier|Customer service', 'Wrong item|Lost parcel|Automation outage', 'Scan verification|Chain of custody|Manual continuity process', 'Pick confirmation|Custody event|Delivery evidence'),
      stage('retail-retain', 'Support and retain', 'Resolve issues fairly and learn without overusing customer data.', 'Customer relationship management|Support platform|Returns system', 'Interaction|Return reason|Resolution|Preference', 'Customer|Support agent|Experience owner', 'Social engineering|Unauthorized refund|Excessive profiling', 'Agent verification|Refund approval|Retention and access rules', 'Support transcript|Refund decision|Deletion or preference record'),
    ],
  },
  {
    industrySlug: 'public-sector', title: 'Government, public services and education', dominantConsequence: 'Public trust depends on accessible services, lawful decisions, durable records and continuity for people who may have no alternative.', feedback: 'Appeals, outcomes, accessibility evidence, audit and public scrutiny reshape policy and delivery.',
    stages: [
      stage('pub-policy', 'Set policy', 'Define a lawful, explainable public outcome and eligibility model.', 'Policy repository|Consultation platform|Legislative records', 'Authority|Impact evidence|Policy text', 'Policy owner|Legal adviser|Affected community', 'Unlawful criterion|Hidden impact|Unclear authority', 'Legal review|Impact assessment|Public consultation', 'Authority record|Impact assessment|Approved policy'),
      stage('pub-fund', 'Fund and plan', 'Allocate public resources to measurable outcomes and delivery capacity.', 'Budget system|Portfolio platform|Grant management', 'Budget|Business case|Outcome measure', 'Finance authority|Program owner|Oversight body', 'Misallocation|Optimism bias|Supplier concentration', 'Business-case challenge|Benefits ownership|Procurement controls', 'Funding decision|Assumption register|Contract record'),
      stage('pub-deliver', 'Deliver services', 'Provide an inclusive, secure and usable service.', 'Citizen or learner portal|Identity platform|Contact center', 'Application|Identity evidence|Service decision', 'Citizen or learner|Case worker|Service owner', 'Digital exclusion|Fraud|Service outage', 'Accessible alternatives|Risk-based verification|Continuity channel', 'Accessibility test|Decision log|Availability evidence'),
      stage('pub-cases', 'Manage cases and records', 'Maintain complete records and reach consistent accountable decisions.', 'Case-management system|Document management|Records archive', 'Case file|Evidence|Decision|Retention class', 'Case worker|Reviewer|Records manager', 'Lost evidence|Unauthorized access|Inconsistent decision', 'Role and case access|Four-eyes review|Records schedule', 'Access log|Review approval|Disposition record'),
      stage('pub-measure', 'Measure outcomes', 'Learn whether the service created the intended public value.', 'Analytics platform|Survey tool|Open-data portal', 'Outcome metric|Feedback|Aggregate dataset', 'Program evaluator|Data steward|Community', 'Misleading metric|Re-identification|Gaming', 'Measure design review|Privacy protection|Independent evaluation', 'Metric definition|Quality result|Published methodology'),
      stage('pub-account', 'Remain accountable', 'Explain authority, spending, performance and correction to the public.', 'Audit platform|Disclosure portal|Committee records', 'Audit trail|Finding|Response|Public report', 'Executive|Auditor|Elected or public oversight', 'Opaque decision|Unresolved finding|Misinformation', 'Independent audit|Transparent reporting|Tracked corrective action', 'Audit report|Management response|Closure evidence'),
    ],
  },
  {
    industrySlug: 'telecommunications', title: 'Telecommunications, media and entertainment', dominantConsequence: 'Always-on networks and rights-based content services operate at immense scale with concentrated infrastructure dependencies.', feedback: 'Traffic, quality, fraud, rights disputes and subscriber behavior shape capacity, products and abuse controls.',
    stages: [
      stage('tel-build', 'Build network or acquire content', 'Create capacity or obtain rights with clear ownership and resilience.', 'Network planning|Rights management|Supplier systems', 'Topology or title|Capacity|License and territory', 'Network engineer|Rights owner|Procurement', 'Single point of failure|Rights conflict|Supplier backdoor', 'Diverse design|Rights validation|Supplier security', 'Design review|License record|Supplier assessment'),
      stage('tel-provision', 'Provision subscribers', 'Create the correct identity, service and entitlement.', 'Subscriber management|Identity platform|Order orchestration', 'Subscriber identity|Plan|Device or entitlement', 'Customer|Provisioning team|Fraud analyst', 'SIM swap|Wrong entitlement|Identity mismatch', 'Strong verification|Privileged change control|Activation monitoring', 'Verification event|Provisioning order|Change audit'),
      stage('tel-deliver', 'Deliver connection or experience', 'Route traffic or content at required quality and scale.', 'Core and access network|Content delivery network|Streaming platform', 'Routing state|Session|Quality telemetry', 'Network operations|Platform team|Customer', 'Outage|Route leak|Capacity collapse', 'Redundancy|Traffic engineering|Automated rollback', 'Route and configuration history|Availability metric|Incident timeline'),
      stage('tel-bill', 'Bill and support', 'Measure usage accurately and resolve subscriber issues.', 'Metering|Billing|Customer support', 'Usage event|Tariff|Invoice|Support case', 'Subscriber|Billing operations|Support agent', 'Revenue leakage|Incorrect charge|Support impersonation', 'Usage reconciliation|Tariff approval|Agent verification', 'Usage-to-bill trace|Adjustment approval|Support log'),
      stage('tel-protect', 'Protect rights and quality', 'Detect abuse while preserving lawful access and service quality.', 'Digital rights management|Fraud analytics|Quality monitoring', 'License state|Abuse signal|Quality indicator', 'Rights owner|Security analyst|Service owner', 'Piracy|Signaling abuse|Overblocking', 'Rights enforcement|Abuse detection|Appeal and exception process', 'Detection evidence|Enforcement decision|Quality and appeal record'),
    ],
  },
  {
    industrySlug: 'energy', title: 'Energy, utilities and critical infrastructure', dominantConsequence: 'Safety, environmental protection and stable physical service dominate design, change and recovery decisions.', feedback: 'Demand, faults, weather, near misses and asset condition reshape operations, maintenance and long-term investment.',
    stages: [
      stage('energy-generate', 'Generate or source', 'Produce or obtain energy within safety and market limits.', 'Plant control|Market platform|Fuel management', 'Output|Set point|Market schedule|Fuel state', 'Plant operator|Trader|Safety authority', 'Unsafe output|Fuel disruption|Market error', 'Safety interlock|Dispatch authorization|Supplier resilience', 'Operator action|Schedule|Safety event'),
      stage('energy-transmit', 'Transmit', 'Move bulk energy while maintaining system stability.', 'Control center|SCADA|Protection relays', 'Frequency|Voltage or pressure|Topology|Alarm', 'Control-room operator|Grid engineer|Field team', 'Cascading outage|False telemetry|Protection failure', 'Redundant sensing|Segmentation|Protective schemes', 'Telemetry history|Relay event|Operator decision'),
      stage('energy-distribute', 'Distribute', 'Deliver service safely through local infrastructure.', 'Distribution management|Field devices|Outage management', 'Feeder state|Fault location|Switching order', 'Dispatcher|Field crew|Emergency coordinator', 'Unsafe switching|Extended outage|Remote-control abuse', 'Switching procedure|Command authorization|Manual fallback', 'Switching log|Crew confirmation|Restoration record'),
      stage('energy-meter', 'Meter and bill', 'Measure consumption and produce accurate customer accounts.', 'Advanced metering|Meter-data management|Billing', 'Interval reading|Tariff|Account|Exception', 'Customer|Meter operations|Billing owner', 'Meter tampering|Privacy harm|Incorrect bill', 'Device identity|Usage validation|Billing reconciliation', 'Meter event|Validation result|Adjustment record'),
      stage('energy-maintain', 'Maintain assets', 'Preserve safe, reliable equipment across a long lifecycle.', 'Asset management|Maintenance system|Remote access gateway', 'Asset condition|Work order|Configuration', 'Asset engineer|Vendor|Field technician', 'Legacy failure|Unsafe firmware|Vendor misuse', 'Condition monitoring|Controlled remote access|Configuration backup', 'Inspection|Session record|Before and after configuration'),
      stage('energy-balance', 'Balance demand and supply', 'Keep the physical system stable as conditions change.', 'Forecasting|Energy management|Demand response', 'Demand forecast|Reserve|Constraint|Control action', 'System operator|Market participant|Emergency authority', 'Forecast error|Insufficient reserve|Manipulated signal', 'Independent forecasts|Operating reserves|Crisis playbook', 'Forecast accuracy|Dispatch action|Reserve and event report'),
    ],
  },
  {
    industrySlug: 'transport-logistics', title: 'Transportation, logistics and mobility', dominantConsequence: 'People, vehicles and goods move through safety-critical, time-sensitive and cross-border dependency chains.', feedback: 'Delay, route risk, custody exceptions, weather and maintenance reliability reshape schedules and capacity.',
    stages: [
      stage('tr-plan', 'Plan and book', 'Match demand, capacity, route and obligation into a feasible movement.', 'Booking|Route planning|Capacity management', 'Passenger or cargo|Route|Schedule|Constraint', 'Customer|Planner|Safety or compliance owner', 'Overbooking|Unsafe route|Wrong documentation', 'Constraint validation|Identity and document checks|Approval for exceptions', 'Booking record|Route approval|Exception decision'),
      stage('tr-dispatch', 'Dispatch', 'Assign authorized people and assets with a safe operating plan.', 'Dispatch platform|Crew management|Fleet system', 'Vehicle|Crew qualification|Load|Departure plan', 'Dispatcher|Crew|Operations supervisor', 'Unqualified crew|Wrong load|Stale plan', 'Qualification check|Load verification|Pre-departure briefing', 'Dispatch release|Crew record|Checklist'),
      stage('tr-move', 'Move', 'Navigate and operate safely while conditions change.', 'Vehicle control|Navigation|Communications', 'Position|Speed|Route|Vehicle state', 'Driver or crew|Controller|Emergency services', 'Navigation manipulation|Collision|Communications loss', 'Independent positioning|Safety limits|Alternate communications', 'Position history|Control event|Incident log'),
      stage('tr-track', 'Track', 'Maintain trustworthy visibility of location, condition and expected arrival.', 'Tracking platform|Telematics|Customer portal', 'Location|Condition|Estimated arrival', 'Operations|Customer|Carrier', 'Spoofed position|Missing condition alert|Privacy misuse', 'Signal validation|Condition thresholds|Role-limited visibility', 'Tracking event|Alert response|Access log'),
      stage('tr-transfer', 'Transfer and clear', 'Move custody and satisfy border, port or hub requirements.', 'Port or terminal system|Customs platform|Warehouse automation', 'Manifest|Custody event|Clearance', 'Handler|Customs or authority|Broker', 'Cargo substitution|Document fraud|Hub outage', 'Seal and scan checks|Document validation|Continuity procedure', 'Custody record|Clearance|Exception resolution'),
      stage('tr-deliver', 'Deliver', 'Complete movement to the correct recipient with evidence.', 'Last-mile platform|Proof-of-delivery service|Customer notification', 'Recipient|Delivery event|Condition|Exception', 'Courier or crew|Recipient|Customer service', 'Wrong recipient|Theft|False completion', 'Recipient verification|Proof of delivery|Exception escalation', 'Delivery evidence|Identity check|Claim record'),
      stage('tr-maintain', 'Maintain', 'Keep vehicles and infrastructure safe and available.', 'Maintenance system|Diagnostic platform|Parts inventory', 'Fault|Service interval|Part|Release decision', 'Maintenance engineer|Inspector|Fleet owner', 'Deferred defect|Counterfeit part|Unsafe software change', 'Preventive maintenance|Part provenance|Independent release', 'Work order|Inspection|Return-to-service approval'),
    ],
  },
  {
    industrySlug: 'technology-services', title: 'Technology, SaaS and professional services', dominantConsequence: 'Shared platforms and expert services depend on tenant isolation, safe rapid change, customer trust and recoverable operations.', feedback: 'Usage, support evidence, incidents, customer outcomes and technical debt shape the roadmap and platform design.',
    stages: [
      stage('tech-discover', 'Discover need', 'Define a valuable problem, user and measurable outcome.', 'Research repository|Product analytics|Customer relationship management', 'User need|Constraint|Outcome measure', 'User|Product manager|Risk and domain adviser', 'Wrong problem|Hidden legal constraint|Biased sample', 'Discovery research|Stakeholder and risk review|Outcome definition', 'Research note|Decision record|Success measure'),
      stage('tech-build', 'Design and build', 'Create a secure, maintainable solution with explicit trust boundaries.', 'Source control|Build pipeline|Cloud development platform', 'Requirement|Source code|Dependency|Build artifact', 'Developer|Architect|Security champion', 'Supply-chain compromise|Broken authorization|Unreviewed change', 'Threat modeling|Code review and testing|Protected build provenance', 'Review|Test result|Artifact attestation'),
      stage('tech-onboard', 'Sell and onboard', 'Set accurate expectations and configure a safe customer boundary.', 'Contract platform|Tenant provisioning|Identity federation', 'Contract|Tenant|Configuration|Administrator', 'Customer owner|Sales|Implementation team', 'Overpromise|Wrong tenant configuration|Excess privilege', 'Approved claims|Provisioning template|Named administrator verification', 'Contract approval|Tenant creation log|Acceptance record'),
      stage('tech-operate', 'Operate and support', 'Maintain availability, isolation and helpful controlled support.', 'Cloud platform|Observability|Support system', 'Telemetry|Alert|Support case|Session', 'Site Reliability Engineering|Support agent|Customer', 'Cross-tenant exposure|Privileged support misuse|Outage', 'Tenant-aware authorization|Just-in-time support access|Incident response', 'Access and session log|Incident timeline|Support decision'),
      stage('tech-renew', 'Renew and expand', 'Prove value and extend use without uncontrolled data or access growth.', 'Billing|Usage analytics|Customer success platform', 'Usage|Entitlement|Outcome|Renewal', 'Customer owner|Customer success|Finance', 'Shelfware|Entitlement creep|Misleading metric', 'Outcome review|Entitlement reconciliation|Transparent pricing', 'Value review|Access review|Renewal decision'),
      stage('tech-retire', 'Retire and exit', 'End service cleanly, return data and remove residual access and dependencies.', 'Data export|Identity lifecycle|Asset and deletion workflow', 'Export|Retention obligation|Deletion result|Revocation', 'Customer|Service owner|Data and security owner', 'Orphaned access|Incomplete deletion|Unusable export', 'Exit plan|Verified revocation and deletion|Portable documented export', 'Export confirmation|Deletion evidence|Access closure'),
    ],
  },
];

export const industryChainBySlug = new Map(industryChains.map((chain) => [chain.industrySlug, chain]));
