export const pillarDrafts = {
  business: {
    id: 'business',
    title: 'Business, Product & Operations',
    purpose: `Understand how an organization chooses where to play, creates value, organizes people and resources, delivers products and services, measures performance, and improves. This pillar connects strategy to daily work so readers can trace a technology decision from customer need through process, economics, delivery, adoption, and measurable benefit.`,
    sections: [
      {
        order: 1,
        title: 'Value, customers, and business models',
        body: `Every organization exists to create an outcome for someone. A commercial firm may solve a customer problem in exchange for revenue, while a public body or nonprofit may allocate funding to create social value. Start by identifying the customer, user, beneficiary, payer, and other stakeholders because they may be different people. A value proposition explains the useful change offered to them, not simply the product being sold. The business model then describes how value is created, delivered, and captured through channels, relationships, capabilities, partners, revenue, and costs. Test the model with evidence: Are people choosing the offer, receiving the promised outcome, and doing so at sustainable economics? Technology supports the model but does not define it. A polished app attached to weak demand or poor unit economics is still a weak business. Good analysis makes assumptions visible, compares alternatives, and tracks whether the model remains viable as customer behavior, competition, regulation, and costs change.`,
      },
      {
        order: 2,
        title: 'Strategy, value chains, and operating models',
        body: `Strategy is a coherent set of choices about outcomes, customers, capabilities, and trade-offs. It says what the organization will prioritize and what it will deliberately not pursue. A value chain traces the activities that create an outcome, including suppliers, internal work, channels, service, and feedback. An operating model explains how that chain runs repeatedly through roles, decision rights, processes, information, technology, locations, partners, and governance. Together they convert an ambition into a system of work. Map the critical capabilities first, then identify where the organization must excel, partner, standardize, or accept constraints. Architecture and sourcing choices should follow those decisions. When strategy changes, the operating model may need new skills, controls, incentives, data, or platforms. Misalignment is common: a company may promise a seamless digital experience while funding teams, measures, and systems in isolated silos. A useful operating model reveals those contradictions and gives leaders a practical design for resolving them.`,
      },
      {
        order: 3,
        title: 'Processes, operations, and continuous improvement',
        body: `A process is a repeatable sequence that transforms an input into an outcome. Operations manage that process under real conditions, including variable demand, limited capacity, exceptions, errors, and dependencies. Begin with the current flow: trigger, activities, decisions, hand-offs, queues, controls, outputs, and owner. Measure elapsed time, effort, error, rework, demand, capacity, and customer impact. A bottleneck is the constraint limiting the whole system, so improving a nonconstraint may only create a larger queue elsewhere. Distinguish value-adding work from necessary control and avoidable waste. Lean methods remove friction, while statistical and quality methods reduce variation and defects. Automation can improve speed and consistency only after rules, exceptions, ownership, and failure handling are understood. Operational management also needs service levels, escalation paths, incident handling, capacity planning, and feedback. Continuous improvement is a disciplined loop: observe performance, find causes, test a targeted change, compare results, standardize what worked, and keep monitoring for unintended effects.`,
      },
      {
        order: 4,
        title: 'Product management, service design, and customer experience',
        body: `Product management steers a capability toward valuable outcomes across its life, not merely toward a list of features. Discovery investigates users, problems, alternatives, constraints, and willingness to change. Delivery turns the strongest assumptions into small, testable increments. Service design widens the view beyond an interface to the complete journey, including people, policies, channels, backstage processes, support, and recovery when something fails. Customer experience is the cumulative perception created by these interactions. A roadmap should express outcome bets and sequencing, while a backlog contains candidate work that can change as evidence develops. Prioritization balances customer value, strategic fit, risk reduction, effort, dependencies, and learning value. Teams should pair behavior measures, such as successful completion, with outcome measures, such as reduced waiting time or improved retention. Launch is the start of learning, not the finish. Product health also requires accessibility, reliability, security, support, cost management, and a clear retirement path when the capability no longer earns its place.`,
      },
      {
        order: 5,
        title: 'Business analysis, requirements, and acceptance',
        body: `Business analysis turns an unclear need into shared understanding and testable decisions. The analyst identifies stakeholders, desired outcomes, current pain, business rules, data, constraints, assumptions, dependencies, and risks. Requirements can describe capabilities, user behavior, quality attributes, legal duties, interfaces, migration, or operational support. They should explain the need and success condition without prematurely locking the team into one solution. User stories are useful conversation prompts, but they do not replace process models, data definitions, prototypes, or nonfunctional requirements. Acceptance criteria make expected behavior observable, including boundaries and failure cases. Traceability connects an objective to a requirement, design choice, test, release, and evidence so teams can see why work exists and what a change affects. Resolve conflicts by returning to outcomes and decision rights. Good requirements evolve when learning changes the problem; uncontrolled ambiguity is not agility. Before build begins, confirm shared language, scope boundaries, assumptions to test, accountable owners, and how users will validate that the result is fit for purpose.`,
      },
      {
        order: 6,
        title: 'Projects, programs, products, and portfolios',
        body: `A project is temporary work that creates a defined output. A program coordinates related change to produce broader benefits. A product is an enduring capability managed through discovery, delivery, operation, and improvement. A portfolio balances investments across strategic priorities, capacity, risk, and expected value. These forms can coexist, but confusing them causes trouble. A project can deliver a platform release, while a product team remains accountable for adoption, reliability, and later evolution. Every initiative needs a clear outcome, owner, scope boundary, plan, dependencies, resources, risks, decisions, and evidence of progress. Time, cost, scope, quality, and risk interact, so a change in one should trigger an explicit trade-off rather than silent pressure. Governance should be proportionate: short feedback cycles for delivery, milestone decisions for major commitments, and portfolio reviews for continuation or stopping. Status reporting must separate completed activity from forecast outcome. Successful delivery means not only producing the output, but also enabling the operational capability and benefits that justified the investment.`,
      },
      {
        order: 7,
        title: 'Objectives, metrics, and decision quality',
        body: `Objectives describe a meaningful result; measures show whether reality is moving toward it. A good measurement system combines leading indicators, which signal likely future performance, with lagging indicators, which confirm results. Key Performance Indicators should be few, owned, consistently defined, and tied to decisions. Objectives and Key Results can align teams when the objective is qualitative and the results are measurable outcomes rather than task lists. Avoid vanity metrics, averages that hide harmful segments, and targets that invite gaming. Pair speed with quality, growth with sustainability, and efficiency with customer or employee impact. Decision quality also depends on alternatives, assumptions, uncertainty, reversibility, opportunity cost, and who holds the decision right. Record important decisions and the evidence available at the time, then review outcomes without hindsight bias. Experiments can reduce uncertainty when ethical, measurable, and appropriately scoped. Dashboards do not make decisions. People do, using data alongside context, judgment, constraints, and an explicit understanding of what the measures cannot prove.`,
      },
      {
        order: 8,
        title: 'Finance, procurement, and commercial management',
        body: `Financial literacy helps teams compare value, affordability, and timing. Revenue, cost, margin, cash flow, assets, and liabilities describe different aspects of performance. Investment analysis should consider expected benefit, implementation cost, ongoing operating cost, risk, time to value, and opportunity cost. Total Cost of Ownership includes licenses, infrastructure, people, integration, controls, support, change, and exit, not just the purchase price. Unit economics tests whether value scales at the level of a customer, transaction, or service unit. Procurement converts a need into a fair, controlled sourcing decision through requirements, market analysis, due diligence, competition, negotiation, approval, and contracting. A contract should make service, security, privacy, audit, data ownership, intellectual property, change, liability, continuity, and termination expectations explicit. Vendor management continues after signature with performance reviews, risk monitoring, issue resolution, financial oversight, and exit readiness. The cheapest bid may create the highest lifetime cost, while the strongest brand may still be a poor fit for the operating model.`,
      },
      {
        order: 9,
        title: 'Change, adoption, and benefits realization',
        body: `Delivery creates a capability; adoption changes behavior; benefits appear only when the new behavior improves an outcome. Change begins with a credible reason, stakeholder analysis, visible sponsorship, and an honest account of who gains, who loses, and what becomes harder. Involve affected people early enough to shape the design. Prepare communications, training, process updates, support, incentives, data migration, local champions, and manager expectations as parts of delivery, not as launch decoration. Readiness measures whether people, operations, controls, and technology can sustain the change. Adoption measures meaningful use, proficiency, satisfaction, workarounds, and abandonment rather than logins alone. Benefits need named owners, baselines, target measures, timing, and attribution assumptions. Resistance can reveal a bad design, conflicting incentives, overload, or legitimate risk, so treat it as evidence before labeling it attitude. Reinforce the change through coaching, feedback, fixes, and leadership behavior. If promised benefits do not appear, revisit the underlying assumptions and be willing to adapt or stop.`,
      },
    ],
    lifecycle: [
      'Identify the stakeholder need and intended outcome',
      'Understand context, demand, constraints, and current performance',
      'Choose a value proposition and strategic position',
      'Design the value chain and operating model',
      'Define requirements, measures, economics, and risks',
      'Prioritize and fund the portfolio of change',
      'Discover, deliver, and validate the product or service',
      'Launch with operational readiness and adoption support',
      'Measure outcomes, costs, service health, and benefits',
      'Improve, scale, replace, or retire based on evidence',
    ],
    terms: [
      { term: 'Value proposition', definition: 'The specific useful outcome promised to a defined customer, user, or beneficiary, and the reason they would choose it over alternatives.' },
      { term: 'Operating model', definition: 'The practical arrangement of capabilities, people, processes, information, technology, partners, locations, and governance used to execute strategy.' },
      { term: 'KPI', fullForm: 'Key Performance Indicator', definition: 'A deliberately selected measure that shows performance against an important objective and supports a decision.' },
      { term: 'OKR', fullForm: 'Objectives and Key Results', definition: 'A goal-setting method that pairs a meaningful qualitative objective with a small set of measurable outcome results.' },
      { term: 'TCO', fullForm: 'Total Cost of Ownership', definition: 'The full lifecycle cost of acquiring, implementing, operating, supporting, changing, and retiring a capability.' },
      { term: 'SLA', fullForm: 'Service Level Agreement', definition: 'A documented agreement defining measurable service commitments, responsibilities, remedies, and how performance will be assessed.' },
    ],
    example: {
      title: 'A regional hospital redesigns outpatient appointments',
      context: 'Patients face long telephone queues, missed appointments, and repeated data entry. The hospital wants digital self-service without excluding people who need assisted channels.',
      steps: [
        'Map the patient journey, clinical scheduling rules, call-center work, identity checks, accessibility needs, and failure points.',
        'Define outcomes: shorter booking time, fewer missed appointments, equitable access, accurate records, and no reduction in patient safety.',
        'Create a product team spanning operations, clinicians, design, software, data, privacy, cybersecurity, finance, and change leadership.',
        'Integrate the portal with scheduling and identity services, retain telephone support, and test unusual clinical and access scenarios.',
        'Launch by clinic, monitor completion and exclusion by patient segment, support staff adoption, and fix process bottlenecks before scaling.',
      ],
      lesson: 'Business value comes from the whole service change. The portal, process, people, data, controls, and economics must work together.',
    },
    misconceptions: [
      { claim: 'Strategy is a list of annual goals.', correction: 'Strategy is a connected set of choices and trade-offs about where and how to create value.' },
      { claim: 'A shipped feature is a realized benefit.', correction: 'A benefit requires adoption, changed behavior, and evidence of an improved outcome.' },
      { claim: 'Automation fixes inefficient processes.', correction: 'Automation can accelerate waste or failure when rules, exceptions, and ownership remain unclear.' },
      { claim: 'Agile means no planning or documentation.', correction: 'Agile favors adaptive planning and useful evidence, not the absence of discipline.' },
      { claim: 'The lowest purchase price is the best commercial decision.', correction: 'Fit, risk, operating cost, dependency, and exit can outweigh the initial price.' },
    ],
    relatedPillars: [
      { id: 'software', reason: 'Turns product intent and requirements into supported software.' },
      { id: 'data', reason: 'Provides trusted measures, customer insight, experimentation, and operational evidence.' },
      { id: 'governance', reason: 'Defines accountability, policy, obligations, controls, and assurance.' },
      { id: 'risk', reason: 'Makes uncertainty, resilience, and investment trade-offs explicit.' },
      { id: 'people', reason: 'Enables leadership, adoption, negotiation, and cross-functional delivery.' },
    ],
  },

  ai: {
    id: 'ai',
    title: 'Artificial Intelligence & Emerging Technology',
    purpose: `Understand how intelligent and emerging technologies are created, evaluated, deployed, governed, secured, and connected to real outcomes. This pillar explains the ideas beneath machine learning, generative systems, agents, robotics, connected devices, and frontier technologies while keeping evidence, economics, human accountability, and lifecycle risk at the center.`,
    sections: [
      {
        order: 1,
        title: 'AI foundations and historical context',
        body: `Artificial intelligence is the broad pursuit of machines performing tasks associated with perception, language, reasoning, learning, or action. Its history is not one straight march toward human-like intelligence. Alan Turing framed machine intelligence as a practical question in 1950. John McCarthy helped establish AI as a field at the 1956 Dartmouth workshop. Frank Rosenblatt developed the perceptron, an early learning system. Periods of high expectation were followed by AI winters when capability and funding fell short. Expert systems encoded specialist rules, while statistical learning increasingly learned patterns from data. Geoffrey Hinton, Yann LeCun, and Yoshua Bengio advanced neural network methods; Fei-Fei Li helped make large-scale visual data central to progress. Increased compute, large datasets, and improved algorithms drove deep learning breakthroughs. The 2017 Transformer architecture by Ashish Vaswani and colleagues reshaped language modeling and later generative AI. This context matters because today’s systems combine decades of ideas, infrastructure, labor, data, and experimentation rather than appearing suddenly or inevitably.`,
      },
      {
        order: 2,
        title: 'Machine learning, training, and inference',
        body: `Machine learning builds a model by finding patterns in examples rather than encoding every rule directly. Supervised learning uses labeled examples to predict a class or value. Unsupervised learning explores structure without target labels. Reinforcement learning improves behavior through feedback from actions and outcomes. A team defines the task, collects and prepares data, selects features or representations, splits data for training and evaluation, fits candidate models, tunes choices, and tests performance on unseen cases. Training is the resource-intensive learning phase; inference is using the trained model to produce a prediction. Performance depends on how well the data represents future use, whether labels are reliable, and whether the metric reflects the real decision. Overfitting occurs when a model learns training detail that does not generalize. Distribution shift appears when live conditions differ from development data. A model is one component of a decision system, so thresholds, human review, interfaces, appeals, monitoring, and fallback behavior are as important as the algorithm.`,
      },
      {
        order: 3,
        title: 'Neural networks, foundation models, and representations',
        body: `A neural network is a layered mathematical function whose parameters are adjusted from examples. Deep learning uses many layers to learn increasingly useful representations of text, images, audio, or other signals. Embeddings represent items as numeric vectors so related meanings or patterns can be placed near one another. Attention lets a model weigh relationships between parts of an input, and Transformers use attention to process sequences efficiently at scale. A foundation model is trained broadly enough to support many later tasks through prompting, retrieval, fine-tuning, or adapters. Large Language Models generate tokens by estimating likely continuations from context; fluent output is therefore not the same as verified knowledge or reasoning. Model capability reflects architecture, data, compute, training objectives, and post-training methods. Size can improve generality but also raises cost, latency, concentration, and environmental concerns. Practitioners should select the smallest model that meets a measured need, understand license and data constraints, and design the surrounding system to compensate for known limitations.`,
      },
      {
        order: 4,
        title: 'Generative AI, retrieval, agents, and system architecture',
        body: `A generative AI application is more than a model endpoint. The full system includes user experience, instructions, context selection, identity, data access, retrieval, tools, memory, safety controls, observability, and human oversight. Retrieval-Augmented Generation searches approved sources and places relevant material in the model context, improving grounding without guaranteeing correctness. Tool use lets a model query a database, calculate, search, or take an authorized action. An agent adds a loop that can interpret a goal, plan steps, call tools, inspect results, and continue until a stopping condition is reached. Greater autonomy also increases the consequences of wrong assumptions, prompt injection, excessive permissions, and runaway cost. Memory may preserve useful state but creates privacy, retention, and contamination risks. Separate trusted instructions from untrusted content, constrain tools to least privilege, validate structured inputs and outputs, require approval for consequential actions, and keep deterministic controls outside the model. Design explicit fallbacks for uncertainty, unavailable tools, unsafe requests, and model failure.`,
      },
      {
        order: 5,
        title: 'Evaluation, experimentation, and AI economics',
        body: `Evaluation asks whether an AI system is useful, safe, reliable, and affordable for its intended context. Begin with real tasks and failure consequences, then build representative test cases, including edge conditions and adversarial inputs. Measures may cover correctness, task completion, groundedness, relevance, calibration, bias, robustness, latency, cost, and user experience. No single benchmark proves production fitness. Automated scoring can scale, human review can judge nuance, and controlled experiments can compare the effect on real work. Define acceptable thresholds and release gates before seeing favorable results. Test the complete system, not just the base model, because retrieval, prompts, tools, interfaces, and people change behavior. Economics include inference volume, model and hosting fees, integration, data preparation, evaluation, human review, monitoring, support, security, and switching cost. Compare against a simpler workflow and estimate the value of errors as well as the value of speed. Continue evaluation after launch because models, data, providers, users, and adversaries change.`,
      },
      {
        order: 6,
        title: 'Responsible AI, governance, and security',
        body: `Responsible AI turns principles such as fairness, transparency, privacy, safety, robustness, and accountability into decisions across the lifecycle. Governance starts with an inventory of systems, named owners, intended use, affected people, risk classification, approval criteria, documentation, and routes for challenge or appeal. Impact depends on context: a writing assistant and a clinical prioritization model require different evidence and oversight. Teams should examine data provenance, consent or legal basis, representation, accessibility, explainability needs, and whether automation changes power or opportunity. AI security includes familiar risks such as identity abuse and data leakage plus model-specific threats such as poisoning, extraction, evasion, prompt injection, insecure tool use, and unsafe model supply chains. Controls include access boundaries, data minimization, isolated retrieval, content handling, red teaming, output validation, rate limits, monitoring, and incident response. Human oversight must be meaningful: reviewers need time, authority, competence, and enough information to disagree. Accountability remains with the organization even when a vendor supplies the model.`,
      },
      {
        order: 7,
        title: 'MLOps, LLMOps, monitoring, and incident response',
        body: `Machine Learning Operations and Large Language Model Operations apply lifecycle discipline to data, models, prompts, retrieval, tools, and evaluations. Teams version code, datasets, features, model artifacts, instructions, policies, and test suites so a production result can be reproduced and investigated. A controlled pipeline moves changes through validation, security checks, approval, staged release, and rollback. Registries record ownership, lineage, intended use, limitations, and deployment status. Monitoring should connect technical signals to user and business outcomes: input drift, output quality, refusal patterns, unsafe content, latency, cost, tool errors, bias, and human override. Logs need privacy controls because prompts and retrieved context may contain sensitive information. Incident plans should define detection, triage, containment, provider coordination, rollback or model substitution, stakeholder communication, and learning. Teams must also watch model and API deprecations, dependency vulnerabilities, expiring data rights, and silent provider changes. Retirement removes endpoints, credentials, replicas, stored prompts, and downstream dependencies while preserving required evidence.`,
      },
      {
        order: 8,
        title: 'IoT, operational technology, robotics, and digital twins',
        body: `The Internet of Things connects sensors, software, networks, and physical objects so they can observe or influence the world. Operational Technology controls physical processes such as manufacturing, energy, or transport, where availability and safety may outweigh rapid feature change. Robotics combines sensing, planning, actuation, and control to perform physical tasks. A digital twin is a maintained digital representation of a real asset or process used for monitoring, simulation, or optimization. These systems create a chain from device hardware and firmware through connectivity, edge computing, cloud platforms, data, analytics, and human operators. Failures can cause physical harm, environmental impact, or prolonged service loss, so engineering must consider safe states, real-time constraints, network loss, manual operation, maintenance windows, and long equipment lifecycles. Security requires asset visibility, segmented networks, strong device identity, signed updates, constrained commands, monitoring, and supplier assurance. Use cases should prove operational value before adding connectivity that increases complexity and attack surface.`,
      },
      {
        order: 9,
        title: 'Horizon scanning and emerging technology decisions',
        body: `Emerging technology should be assessed as a portfolio of uncertain options, not a parade of predictions. Quantum computing may eventually change selected optimization, simulation, and cryptographic assumptions, while post-quantum migration is already a planning issue because sensitive data can be captured now and attacked later. Distributed ledgers can coordinate shared state where parties lack one trusted operator, but ordinary databases are simpler for many cases. Spatial computing blends digital information with physical environments; advanced connectivity can enable low-latency and remote operations; synthetic biology and advanced materials connect digital capability to new physical possibilities. For each technology, define the problem, maturity, evidence, dependencies, economics, regulatory context, security, skills, interoperability, and exit risk. Separate scientific feasibility from reliable products and scalable operating models. Use small experiments to test a specific assumption, with clear learning goals and stop conditions. Maintain signals from research, standards, patents, investment, regulation, and adoption, then revisit decisions as evidence changes rather than committing to hype or dismissing progress too early.`,
      },
    ],
    lifecycle: [
      'Frame the human or business outcome and decide whether AI is appropriate',
      'Assess affected people, failure consequences, constraints, and alternatives',
      'Establish data rights, quality, provenance, and representative coverage',
      'Select an architecture, model, provider, and oversight pattern',
      'Prototype the complete workflow with secure access boundaries',
      'Evaluate quality, safety, bias, robustness, latency, and economics',
      'Approve and release gradually with fallback and human review',
      'Monitor outcomes, drift, misuse, cost, incidents, and provider change',
      'Improve through controlled versions and repeat evaluation',
      'Retire models, data, access, and dependencies responsibly',
    ],
    terms: [
      { term: 'ML', fullForm: 'Machine Learning', definition: 'Methods that learn patterns from examples to make predictions, generate content, or guide actions without every rule being manually programmed.' },
      { term: 'LLM', fullForm: 'Large Language Model', definition: 'A model trained on large text or multimodal collections to predict and generate sequences, often adapted through prompting or post-training.' },
      { term: 'RAG', fullForm: 'Retrieval-Augmented Generation', definition: 'A pattern that retrieves relevant material from approved sources and supplies it as model context before generation.' },
      { term: 'Embedding', definition: 'A numeric vector representation that places items with related meaning or behavior near one another in a learned space.' },
      { term: 'Inference', definition: 'The use of a trained model to produce a prediction, classification, recommendation, or generated output for a new input.' },
      { term: 'AI agent', definition: 'A system that uses a model to interpret a goal, choose steps, call permitted tools, observe results, and continue within defined limits.' },
    ],
    history: [
      { name: 'Alan Turing', context: 'Framed machine intelligence as an operational question and proposed the imitation game in 1950.' },
      { name: 'John McCarthy', context: 'Coined the term artificial intelligence and helped convene the 1956 Dartmouth workshop.' },
      { name: 'Frank Rosenblatt', context: 'Developed the perceptron, an influential early model of machine learning.' },
      { name: 'Geoffrey Hinton, Yann LeCun, and Yoshua Bengio', context: 'Advanced neural network learning and helped establish modern deep learning.' },
      { name: 'Fei-Fei Li', context: 'Led ImageNet, which helped make large, structured datasets central to progress in computer vision.' },
      { name: 'Ashish Vaswani and colleagues', context: 'Introduced the Transformer architecture in 2017, enabling major advances in language and multimodal models.' },
    ],
    example: {
      title: 'A bank introduces an agent-assisted fraud investigation workspace',
      context: 'Investigators spend hours gathering transaction, customer, and case information across systems. The bank wants AI assistance without allowing a model to block accounts or contact customers autonomously.',
      steps: [
        'Define the outcome as faster, more consistent evidence gathering while keeping investigators accountable for decisions.',
        'Connect approved case data through least-privilege retrieval, redact unnecessary personal data, and log every source used.',
        'Use a language model to summarize evidence and suggest next checks, but keep account actions behind deterministic rules and human approval.',
        'Evaluate on historical and synthetic cases for factual support, missed risk, bias, prompt injection, latency, and investigation time.',
        'Release to a small team, compare quality and overrides, monitor leakage and unusual tool calls, and retain a manual fallback.',
      ],
      lesson: 'Useful AI depends on business process, secure data, governed tools, measurable evaluation, skilled people, and explicit decision boundaries.',
    },
    misconceptions: [
      { claim: 'A fluent model understands facts like a person.', correction: 'Language models generate likely sequences and can sound confident while being unsupported or wrong.' },
      { claim: 'More model parameters always produce the best system.', correction: 'Task fit, data, architecture, latency, cost, controls, and evaluation often matter more than size.' },
      { claim: 'RAG eliminates hallucination.', correction: 'Retrieval can improve grounding, but sources, selection, context use, and generation can still fail.' },
      { claim: 'Human review automatically makes high-risk AI safe.', correction: 'Review is meaningful only when people have evidence, time, competence, authority, and manageable workload.' },
      { claim: 'AI governance is only a compliance exercise.', correction: 'Good governance improves design, accountability, reliability, adoption, and incident readiness.' },
    ],
    relatedPillars: [
      { id: 'data', reason: 'Supplies governed data, lineage, quality, privacy, and analytical foundations.' },
      { id: 'cloud', reason: 'Provides scalable compute, deployment platforms, reliability, and cost controls.' },
      { id: 'cyber', reason: 'Protects models, identities, data, tools, and the AI software supply chain.' },
      { id: 'governance', reason: 'Defines accountable use, control requirements, assurance, and regulatory response.' },
      { id: 'business', reason: 'Connects AI investment to a real problem, workflow, economics, adoption, and benefit.' },
      { id: 'people', reason: 'Shapes oversight, changed work, communication, trust, and responsible adoption.' },
    ],
  },

  people: {
    id: 'people',
    title: 'People & Professional Capability',
    purpose: `Build the human capabilities that make technical and business knowledge useful: presence, listening, communication, relationships, leadership, negotiation, interviewing, live reasoning, and thoughtful follow-through. This pillar treats professional skill as learnable behavior grounded in curiosity, structure, judgment, respect, and repeated practice rather than charisma or performance.`,
    sections: [
      {
        order: 1,
        title: 'Social skill and professional presence',
        body: `Social skill is the ability to notice context, help others feel respected, and participate without either disappearing or dominating. Professional presence begins with reliability: arrive prepared, use people’s names correctly, respect time, dress for context, and do what you said you would do. Warmth comes from eye contact appropriate to the culture, an open posture, genuine interest, and responses that show attention. Confidence means speaking clearly while acknowledging uncertainty; it is not volume, status display, or constant certainty. In a new group, observe the rhythm, introduce yourself briefly, ask an accessible question, and connect your contribution to what others have said. Boundaries also matter. You can be kind without oversharing, agreeable without promising what you cannot deliver, and assertive without becoming hostile. Do not treat body language as a secret code because individual and cultural differences are large. Presence grows through small, repeatable habits, feedback from trusted people, and attention directed toward the conversation rather than toward self-monitoring.`,
      },
      {
        order: 2,
        title: 'Listening, empathy, conflict, and cross-cultural communication',
        body: `Listening is active work: attend, interpret, test your understanding, and respond to what matters. Let the speaker finish, notice both facts and emotion, paraphrase the central point, and ask a clarifying question before offering a solution. Empathy means trying to understand another person’s perspective and experience; it does not require agreement. In conflict, separate observation from interpretation, describe the effect, explain the need or concern, and invite a joint next step. Focus on the issue and future behavior rather than attacking identity or guessing motives. Strong emotions may require a pause, but avoidance usually lets ambiguity grow. Cross-cultural communication requires curiosity about different norms for directness, hierarchy, silence, disagreement, time, and relationship building. Avoid assigning behavior to a culture too quickly because personality and context also matter. Confirm shared meaning, especially for decisions and commitments. Repair mistakes directly: name what happened, acknowledge impact, correct the understanding, and change the behavior. Trust often grows more from honest repair than from pretending friction never occurred.`,
      },
      {
        order: 3,
        title: 'Networking and long-term relationships',
        body: `Networking is the gradual creation of mutually useful professional relationships, not collecting contacts or asking strangers for favors. Begin with a reason to connect, such as shared work, curiosity about a field, an event discussion, or a thoughtful introduction. Offer a concise self-introduction that covers who you are, what you are exploring, and why this person’s perspective is relevant. Ask specific questions that cannot be answered by a quick profile search, then listen for interests and problems rather than steering everything back to yourself. Close by agreeing on a modest next step, if one is useful. Follow up within a reasonable time with context, appreciation, and any promised resource. Maintain relationships through occasional relevant notes, congratulations, introductions, useful feedback, or offers of help without creating an obligation. Track important context privately and respectfully. A network should be diverse across roles, experience, disciplines, and viewpoints. Reputation compounds when people experience you as curious, generous, competent, discreet, and dependable over time.`,
      },
      {
        order: 4,
        title: 'Professional writing and executive communication',
        body: `Professional communication helps a specific audience understand, decide, or act. Start with the purpose and reader: what do they know, what matters to them, and what must happen next? Put the conclusion or request early, then provide the minimum context, evidence, implications, and action needed. Use concrete verbs, defined terms, short paragraphs, descriptive headings, and precise dates or owners. Separate fact, inference, recommendation, and uncertainty so the reader can judge each appropriately. An executive update usually needs outcome, current state, material change, risk, decision, owner, and next milestone. Email should have a useful subject, clear ask, and explicit deadline only when one exists. Chat is fast but still creates commitments, so summarize decisions in a durable place. Reports should trace claims to evidence and disclose limitations. Match tone to relationship and consequence without becoming vague or inflated. Edit for accuracy, brevity, and likely misunderstanding, then read important messages from the recipient’s perspective before sending.`,
      },
      {
        order: 5,
        title: 'Presenting, storytelling, facilitation, and public speaking',
        body: `A strong presentation changes what an audience understands, feels, decides, or does. Define that outcome before designing slides. Build a simple arc: current situation, meaningful tension, insight, recommendation, evidence, and next step. Give each section one job and each slide one message. Use visuals to reveal relationships, not decorate empty space. Rehearse aloud for timing, transitions, technical setup, and difficult questions. During delivery, slow down, vary emphasis, pause after important points, face the audience, and translate specialist language. Do not memorize every sentence; know the structure and evidence well enough to adapt. Facilitation is different from presenting because the goal is to help a group think and decide. State the purpose, agenda, roles, decision method, and participation norms. Invite quieter voices, manage dominant speakers respectfully, surface disagreement, test alignment, and record actions. In questions, listen fully, answer directly, distinguish fact from judgment, and offer to verify what you do not know.`,
      },
      {
        order: 6,
        title: 'Leadership, teamwork, delegation, and feedback',
        body: `Leadership creates clarity, conditions, and accountability so people can achieve a shared outcome. It is not limited to a title. Explain the purpose, define success, name constraints, clarify decision rights, and connect each person’s work to the whole. Psychological safety allows people to raise concerns and admit mistakes, but it coexists with high standards and respectful challenge. Delegation transfers a meaningful outcome with authority, resources, boundaries, checkpoints, and support; assigning tasks while retaining every decision is not delegation. Match guidance to the person’s experience and the risk of the work. Run meetings only when interaction is needed, with a purpose, prepared inputs, decisions, owners, and follow-up. Give feedback close to the event: describe observable behavior, explain its impact, invite perspective, and agree on a next step. Recognition should be specific and credible. When performance falls short, diagnose clarity, capability, capacity, incentives, and context before assuming attitude. Leaders earn trust by making consistent decisions, sharing credit, owning mistakes, and addressing difficult issues promptly.`,
      },
      {
        order: 7,
        title: 'Negotiation and stakeholder management',
        body: `Negotiation is joint problem solving under partly different interests. Prepare by identifying your goals, underlying interests, constraints, evidence, priorities, possible trades, and Best Alternative to a Negotiated Agreement. Estimate the other side’s interests without treating assumptions as facts. Open by agreeing on the issue and process, then ask questions before advocating a position. Separate positions, such as a requested price or deadline, from interests, such as budget certainty or launch risk. Generate multiple options and trade across differences in value rather than splitting every difference. Use objective criteria where possible. Name difficult behavior calmly, pause when needed, and do not reward pressure with unexamined concessions. Stakeholder management applies the same discipline over time: map influence, impact, attitude, needs, and decision authority; engage people according to their role; and update the map as conditions change. Close with precise terms, owners, dates, assumptions, and escalation paths. A durable agreement is understood, feasible, fair enough to implement, and supported by the people who must carry it out.`,
      },
      {
        order: 8,
        title: 'Interviews and evidence-based answers',
        body: `An interview is a structured conversation about fit, evidence, judgment, and mutual choice. Prepare by mapping the role’s outcomes and capabilities to specific experiences, then identify gaps you can discuss honestly. The Situation, Task, Action, Result framework keeps behavioral answers clear. Briefly set the context and your responsibility, spend most time on the actions you personally took and why, then quantify the result and explain what you learned. Choose examples that show different capabilities and include a setback, conflict, ambiguous problem, and ethical decision. Do not force every answer into a script. Clarify broad questions, think briefly, and adapt the evidence to what was asked. For technical questions, state assumptions, reason visibly, test edge cases, and correct yourself without panic. For motivation questions, connect genuine interests to the work rather than flattering the company. Research enough to ask informed questions about priorities, team conditions, decision making, learning, and success. Afterward, record what you learned, send a concise thank-you when appropriate, and improve the evidence bank for the next conversation.`,
      },
      {
        order: 9,
        title: 'Live cases, structured reasoning, and insightful questions',
        body: `Live cases test how you structure uncertainty, not whether you instantly know a hidden answer. Restate the objective, clarify scope and success, identify stakeholders and constraints, then propose a logical issue tree or sequence. State assumptions, request relevant evidence, calculate carefully, synthesize after each branch, and connect findings to a recommendation with risks and next steps. PREP, meaning Point, Reason, Example, Point, works for a concise opinion. SCQA, meaning Situation, Complication, Question, Answer, builds a problem narrative. Use STAR, meaning Situation, Task, Action, Result, for evidence from experience. Frameworks should support thinking, not replace it. Insightful questions come from the conversation and reveal mechanisms, trade-offs, or evidence. Ask, “What changed your view?”, “Where does this process fail?”, “How is success measured?”, or “Which constraint matters most?” Follow an answer with a deeper question rather than racing through a list. In group cases, make reasoning visible, invite contributions, disagree with ideas respectfully, and summarize decisions so collaboration becomes part of the evidence.`,
      },
    ],
    conversationFlow: [
      'Prepare: know the purpose, audience, context, and your desired outcome',
      'Open: establish rapport and agree on the purpose or question',
      'Listen: attend to facts, emotions, assumptions, and what remains unsaid',
      'Clarify: paraphrase, ask one useful question, and confirm shared meaning',
      'Structure: choose a simple frame such as PREP, SCQA, STAR, or an issue tree',
      'Respond: give the main point, evidence, limits, and relevant implication',
      'Explore: invite challenge, test trade-offs, and build on the other person’s view',
      'Agree: summarize the decision, owner, timing, and unresolved points',
      'Follow through: deliver commitments, share evidence, and maintain the relationship',
      'Reflect: review what worked, seek feedback, and practice one improvement',
    ],
    terms: [
      { term: 'Active listening', definition: 'Attending, paraphrasing, clarifying, and responding in a way that tests and demonstrates understanding.' },
      { term: 'BATNA', fullForm: 'Best Alternative to a Negotiated Agreement', definition: 'The strongest realistic option available if the current negotiation produces no agreement.' },
      { term: 'STAR', fullForm: 'Situation, Task, Action, Result', definition: 'A structure for giving evidence-based behavioral interview answers, with emphasis on personal action and outcome.' },
      { term: 'PREP', fullForm: 'Point, Reason, Example, Point', definition: 'A compact structure for stating a position, supporting it, illustrating it, and closing clearly.' },
      { term: 'SCQA', fullForm: 'Situation, Complication, Question, Answer', definition: 'A narrative structure that establishes context, introduces tension, frames the key question, and presents the response.' },
      { term: 'Psychological safety', definition: 'A shared belief that people can raise questions, concerns, mistakes, and dissent without interpersonal punishment.' },
    ],
    example: {
      title: 'A product lead handles a failed launch review',
      context: 'A new payment feature caused checkout failures. Engineering, operations, risk, support, and commercial leaders enter the review with conflicting explanations and priorities.',
      steps: [
        'Open with the shared outcome: restore safe service, understand causes, support customers, and prevent recurrence without assigning blame prematurely.',
        'Use active listening to separate observed facts from interpretations, then map the timeline, decisions, controls, and customer impact.',
        'Present the current view through SCQA, use PREP for the recommended containment plan, and assign decisions to accountable owners.',
        'Negotiate the release pause by surfacing commercial and safety interests, alternatives, thresholds, and evidence needed to resume.',
        'Give specific feedback privately, communicate the outcome clearly, and follow through on technical, process, training, and customer actions.',
      ],
      lesson: 'Professional capability makes cross-domain expertise usable by turning conflict and uncertainty into evidence, decisions, coordinated action, and learning.',
    },
    misconceptions: [
      { claim: 'Confidence means answering immediately.', correction: 'Credible confidence includes pausing, clarifying, reasoning, and naming what you do not know.' },
      { claim: 'Networking is asking influential people for opportunities.', correction: 'Strong networks grow through relevance, reciprocity, trust, and consistent maintenance.' },
      { claim: 'Good presenters are naturally charismatic.', correction: 'Clear structure, audience understanding, rehearsal, evidence, and deliberate delivery are learnable.' },
      { claim: 'Negotiation is winning concessions.', correction: 'Durable negotiation improves the total agreement by understanding interests, alternatives, and implementability.' },
      { claim: 'Frameworks guarantee a strong answer.', correction: 'STAR, PREP, and SCQA organize relevant thinking; they cannot replace evidence, judgment, or listening.' },
    ],
    relatedPillars: [
      { id: 'business', reason: 'Provides the outcomes, stakeholders, operating context, and decisions that communication must serve.' },
      { id: 'software', reason: 'Uses collaboration, feedback, facilitation, and shared reasoning throughout delivery.' },
      { id: 'cyber', reason: 'Depends on clear incident communication, human-centered controls, and trustworthy security culture.' },
      { id: 'governance', reason: 'Requires concise reporting, constructive challenge, accountability, and ethical judgment.' },
      { id: 'risk', reason: 'Needs transparent uncertainty, scenario discussion, negotiation, and crisis leadership.' },
      { id: 'ai', reason: 'Changes roles and decisions, making oversight, adoption, trust, and responsible communication essential.' },
    ],
  },
} as const;
