export type AttackSurface = 'Identity' | 'Endpoint' | 'Network' | 'Application' | 'Cloud' | 'Data' | 'Supply chain' | 'Human' | 'AI';

export type AttackFamily = {
  id: string;
  title: string;
  surface: AttackSurface;
  objective: string;
  mechanism: string;
  redValidation: string[];
  redTools: string[];
  examples: string[];
  signals: string[];
  prevent: string[];
  detect: string[];
  respond: string[];
  blueTechnology: string[];
  mappings: Array<{ label: string; url: string }>;
};

export const attackSurfaces: AttackSurface[] = ['Identity', 'Endpoint', 'Network', 'Application', 'Cloud', 'Data', 'Supply chain', 'Human', 'AI'];

export const attackFamilies: AttackFamily[] = [
  {
    id: 'recon-exposure', title: 'Reconnaissance and exposed services', surface: 'Network', objective: 'Discover reachable assets, technologies, identities and trust relationships that could support a later intrusion.',
    mechanism: 'Public records, certificate data, search engines, naming patterns and active service discovery reveal an organization\'s external attack surface. The danger is not discovery alone, but an unknown or unmanaged service with a useful weakness.',
    redValidation: ['Confirm written scope and safe scan rates.', 'Compare known inventory with externally observable domains, addresses, certificates and services.', 'Validate only the minimum facts needed to prove ownership, exposure and version risk.', 'Record false positives, cloud ownership and third-party boundaries before escalation.'],
    redTools: ['Nmap for authorized service discovery', 'Masscan for carefully rate-limited large ranges', 'Shodan and Censys for internet exposure context', 'Amass or Subfinder for domain discovery'],
    examples: ['Forgotten staging server exposed to the internet', 'Remote administration interface reachable without an approved gateway', 'Leaked cloud storage endpoint or development hostname'],
    signals: ['Unexpected inbound scans across many ports', 'New public certificate or domain outside inventory', 'Internet-facing service with no owner', 'Repeated requests for common administrative paths'],
    prevent: ['Maintain external asset inventory and ownership.', 'Use approved ingress patterns, network filtering and secure defaults.', 'Remove unused services and separate development from production.', 'Continuously reconcile cloud, domain and certificate inventories.'],
    detect: ['Attack Surface Management findings', 'Firewall and load balancer connection telemetry', 'Certificate transparency monitoring', 'External exposure validation'],
    respond: ['Confirm ownership and business need.', 'Restrict or remove unintended exposure.', 'Patch or isolate vulnerable services.', 'Search for evidence that exposure was previously used.'],
    blueTechnology: ['Microsoft Defender External Attack Surface Management', 'Palo Alto Cortex Xpanse', 'CrowdStrike Falcon Exposure Management', 'SecurityScorecard Attack Surface Intelligence'],
    mappings: [{ label: 'MITRE ATT&CK Reconnaissance', url: 'https://attack.mitre.org/tactics/TA0043/' }],
  },
  {
    id: 'phishing-social', title: 'Phishing and social engineering', surface: 'Human', objective: 'Persuade a person to disclose information, approve access, run content, transfer value or bypass a normal process.',
    mechanism: 'The attacker creates urgency, authority, familiarity or curiosity. Modern campaigns combine email, messaging, voice, fake sign-in pages, QR codes and help-desk impersonation.',
    redValidation: ['Use an approved simulation population, scenario and landing page.', 'Avoid collecting real passwords or sensitive personal content.', 'Measure reporting, escalation and process resistance, not employee embarrassment.', 'Coordinate stop conditions with security, privacy, human resources and communications.'],
    redTools: ['GoPhish for controlled simulations', 'Microsoft Attack Simulation Training', 'Proofpoint Security Awareness', 'Canary tokens for safe interaction evidence'],
    examples: ['Business email compromise and payment diversion', 'MFA fatigue followed by help-desk impersonation', 'OAuth consent phishing', 'QR-code phishing that moves the victim to a mobile browser'],
    signals: ['Lookalike domain or display-name mismatch', 'New inbox rule or unusual OAuth consent', 'Impossible travel or new device after a message', 'Payment detail change outside the approved process'],
    prevent: ['Phishing-resistant authentication such as passkeys or FIDO2.', 'Independent verification for sensitive changes.', 'Email authentication using SPF, DKIM and DMARC.', 'Usable reporting channels and role-specific practice.'],
    detect: ['Secure email gateway verdicts', 'Identity risk and sign-in telemetry', 'Mailbox audit logs', 'User-reported message workflow'],
    respond: ['Disable malicious sessions and revoke tokens.', 'Block domains, senders and payload indicators.', 'Review mailbox rules, delegated access and payment actions.', 'Notify affected people without blame.'],
    blueTechnology: ['Microsoft Defender for Office 365', 'Proofpoint Email Protection', 'Mimecast Email Security', 'Abnormal Security'],
    mappings: [{ label: 'MITRE ATT&CK Phishing T1566', url: 'https://attack.mitre.org/techniques/T1566/' }],
  },
  {
    id: 'credential-attacks', title: 'Credential attacks and account takeover', surface: 'Identity', objective: 'Obtain or abuse valid credentials, authenticators, recovery paths or active sessions.',
    mechanism: 'Password spraying, credential stuffing, token theft, adversary-in-the-middle phishing and weak recovery processes turn legitimate identity paths into initial access.',
    redValidation: ['Use test accounts and approved rate limits.', 'Validate lockout, detection and conditional access without causing user disruption.', 'Test recovery and help-desk proofing with pre-agreed identities.', 'Stop after demonstrating controlled access and revoke all test sessions.'],
    redTools: ['Burp Suite for authorized session analysis', 'Evilginx only in an isolated, approved phishing-resistance lab', 'Kerbrute in a controlled directory assessment', 'Identity provider sign-in and risk dashboards'],
    examples: ['Password spray against remote access', 'Credential stuffing using reused passwords', 'Stolen browser session token', 'Weak password-reset process'],
    signals: ['One source attempting many accounts', 'New device, location or autonomous system', 'Unusual token refresh or consent', 'Successful sign-in immediately after repeated failures'],
    prevent: ['Phishing-resistant multi-factor authentication.', 'Password screening and breached-password controls.', 'Rate limits, smart lockout and bot management.', 'Strong recovery proofing and session protection.'],
    detect: ['Identity Protection and user risk', 'Authentication logs and behavioral analytics', 'Endpoint browser and token access signals', 'Impossible-travel and unfamiliar sign-in analytics'],
    respond: ['Revoke sessions, tokens and risky grants.', 'Reset affected authenticators safely.', 'Review actions performed by the identity.', 'Hunt for persistence and linked compromised accounts.'],
    blueTechnology: ['Microsoft Entra ID Protection', 'Okta Identity Threat Protection', 'Cisco Duo', 'CrowdStrike Falcon Identity Protection'],
    mappings: [{ label: 'MITRE ATT&CK Credential Access', url: 'https://attack.mitre.org/tactics/TA0006/' }, { label: 'MITRE Valid Accounts T1078', url: 'https://attack.mitre.org/techniques/T1078/' }],
  },
  {
    id: 'malware-ransomware', title: 'Malware and ransomware', surface: 'Endpoint', objective: 'Execute unauthorized code, establish control, steal data, disrupt operations or extort the organization.',
    mechanism: 'A malicious attachment, vulnerable service, stolen account or compromised software delivers code. Operators then discover systems, elevate privilege, spread, exfiltrate information and encrypt or destroy recoverable data.',
    redValidation: ['Use inert test files and safe behavior emulation rather than live ransomware.', 'Emulate stages separately to validate prevention, telemetry and response.', 'Protect production availability and never encrypt business data.', 'Verify backup isolation and restoration through controlled recovery exercises.'],
    redTools: ['Atomic Red Team for bounded technique tests', 'MITRE Caldera for authorized emulation', 'EICAR test file for anti-malware validation', 'AttackIQ or SafeBreach for control validation'],
    examples: ['Ransomware using stolen remote access credentials', 'Loader delivered by a malicious document', 'Living-off-the-land activity using signed system tools', 'Data theft before encryption'],
    signals: ['Suspicious process tree or script interpreter', 'Rapid file changes and shadow-copy tampering', 'Credential dumping behavior', 'New remote services or lateral connections'],
    prevent: ['Harden endpoints and application execution.', 'Patch exposed paths and protect privileged identity.', 'Segment important services and administrative planes.', 'Keep immutable, tested and separated backups.'],
    detect: ['Endpoint Detection and Response behavioral analytics', 'Network Detection and Response lateral movement signals', 'Security Information and Event Management correlation', 'Canary files and backup tamper alerts'],
    respond: ['Isolate affected hosts and accounts.', 'Preserve evidence before rebuilding.', 'Block command channels and compromised access paths.', 'Restore in dependency order and verify integrity.'],
    blueTechnology: ['CrowdStrike Falcon', 'Microsoft Defender for Endpoint', 'SentinelOne Singularity', 'Palo Alto Cortex XDR'],
    mappings: [{ label: 'MITRE Data Encrypted for Impact T1486', url: 'https://attack.mitre.org/techniques/T1486/' }, { label: 'CISA StopRansomware', url: 'https://www.cisa.gov/stopransomware' }],
  },
  {
    id: 'privilege-persistence', title: 'Privilege escalation and persistence', surface: 'Endpoint', objective: 'Gain stronger permissions and retain access across restarts, credential changes or defensive action.',
    mechanism: 'Weak service permissions, vulnerable drivers, excessive local rights, scheduled tasks, startup items, new accounts and identity trust misconfiguration can turn a foothold into durable control.',
    redValidation: ['Enumerate privilege boundaries without changing production configuration.', 'Use approved test hosts for exploit validation.', 'Create only reversible, named persistence artifacts.', 'Remove artifacts and verify cleanup with the defender.'],
    redTools: ['BloodHound for directory relationship analysis', 'Microsoft Sysinternals Autoruns', 'LinPEAS or WinPEAS in isolated authorized assessments', 'Semgrep for dangerous privilege patterns in code'],
    examples: ['Service path or permission weakness', 'Excessive sudo rule', 'Abusable Active Directory delegation', 'Unauthorized scheduled task'],
    signals: ['New service, task, startup item or privileged group member', 'Unexpected access to credential material', 'Privilege change outside an approved workflow', 'Signed vulnerable driver load'],
    prevent: ['Remove standing privilege and use just-in-time elevation.', 'Harden service and file permissions.', 'Control drivers, scripts and application execution.', 'Review directory delegation and privileged paths.'],
    detect: ['Endpoint persistence detections', 'Directory change auditing', 'Privileged Access Management logs', 'Configuration drift monitoring'],
    respond: ['Disable unauthorized persistence.', 'Rotate affected secrets and review trust relationships.', 'Rebuild systems when integrity cannot be established.', 'Find the initial access and every dependent path.'],
    blueTechnology: ['Microsoft Defender for Identity', 'CyberArk Privileged Access Manager', 'BeyondTrust', 'Elastic Security'],
    mappings: [{ label: 'MITRE ATT&CK Privilege Escalation', url: 'https://attack.mitre.org/tactics/TA0004/' }, { label: 'MITRE ATT&CK Persistence', url: 'https://attack.mitre.org/tactics/TA0003/' }],
  },
  {
    id: 'lateral-movement', title: 'Lateral movement and remote services', surface: 'Network', objective: 'Move from one compromised identity or host to other systems that provide greater access or business impact.',
    mechanism: 'Valid accounts, remote administration protocols, shared secrets, weak segmentation and excessive trust allow an adversary to traverse the environment.',
    redValidation: ['Map authorized paths from a controlled foothold.', 'Use dedicated test credentials and avoid business data.', 'Demonstrate one bounded hop rather than uncontrolled propagation.', 'Coordinate with operations before testing remote services.'],
    redTools: ['BloodHound for attack-path mapping', 'Impacket in a controlled lab', 'Nmap for reachable service validation', 'PurpleSharp or Atomic Red Team for safe telemetry generation'],
    examples: ['Remote Desktop Protocol access with a reused administrator credential', 'Server Message Block movement using shared local passwords', 'Cloud console pivot through federated identity', 'Jump host with overly broad reachability'],
    signals: ['First-time remote logon between peers', 'Administrative share or remote service creation', 'Authentication from unusual workstation classes', 'East-west traffic outside normal application flows'],
    prevent: ['Segment administrative, user and server networks.', 'Use unique managed local credentials.', 'Require privileged access workstations and strong authentication.', 'Limit remote services to approved management paths.'],
    detect: ['Network Detection and Response east-west analytics', 'Windows and Linux authentication telemetry', 'Identity path analytics', 'Firewall policy and flow logs'],
    respond: ['Isolate the source and reached systems.', 'Disable affected identities and remote sessions.', 'Review all hops and delegated privileges.', 'Reimage or restore systems whose integrity is uncertain.'],
    blueTechnology: ['Vectra AI', 'ExtraHop RevealX', 'Microsoft Defender for Identity', 'Corelight'],
    mappings: [{ label: 'MITRE Remote Services T1021', url: 'https://attack.mitre.org/techniques/T1021/' }, { label: 'MITRE Lateral Movement', url: 'https://attack.mitre.org/tactics/TA0008/' }],
  },
  {
    id: 'web-injection', title: 'Injection and unsafe input handling', surface: 'Application', objective: 'Make an interpreter treat untrusted input as code, a query, a command or another trusted instruction.',
    mechanism: 'Data crosses into SQL, operating-system commands, templates, directory queries or browser contexts without safe parameterization, encoding or validation.',
    redValidation: ['Use an authorized test environment and non-destructive proof.', 'Begin with passive review and harmless syntax changes.', 'Prove the smallest impact, such as reading a test record.', 'Do not dump production data or execute destructive commands.'],
    redTools: ['Burp Suite or OWASP ZAP for request testing', 'sqlmap only with explicit authorization and conservative settings', 'Semgrep and CodeQL for source analysis', 'Web Application Firewall logs for validation'],
    examples: ['SQL injection', 'Operating-system command injection', 'Cross-Site Scripting', 'Server-side template injection'],
    signals: ['Interpreter errors or anomalous query shapes', 'Encoded payload patterns', 'Unexpected child process from an application service', 'Web Application Firewall rule matches'],
    prevent: ['Parameterized queries and safe application programming interfaces.', 'Context-aware output encoding.', 'Allow-list validation and typed schemas.', 'Least-privileged application identities.'],
    detect: ['Web Application Firewall telemetry', 'Runtime application protection', 'Database activity monitoring', 'Application logs with safe request context'],
    respond: ['Block the vulnerable path or deploy a safe temporary rule.', 'Fix the code and test all equivalent sinks.', 'Rotate exposed secrets and inspect affected data.', 'Retest and remove temporary compensating controls when safe.'],
    blueTechnology: ['Cloudflare WAF', 'F5 Advanced WAF', 'AWS WAF', 'Datadog Application Security Management'],
    mappings: [{ label: 'OWASP Top 10 2025: Injection', url: 'https://owasp.org/Top10/2025/A05_2025-Injection/' }, { label: 'MITRE Exploitation for Client Execution T1203', url: 'https://attack.mitre.org/techniques/T1203/' }],
  },
  {
    id: 'access-business-logic', title: 'Broken access control and business-logic abuse', surface: 'Application', objective: 'Perform an action or access an object that the current identity should not be allowed to use.',
    mechanism: 'The server trusts an identifier, client-side decision, role claim or workflow order without enforcing authorization and business rules for every request.',
    redValidation: ['Use two or more controlled identities with different roles.', 'Change object references and workflow order only within test data.', 'Check read, update, delete, export and administrative actions.', 'Avoid accessing another real person\'s information.'],
    redTools: ['Burp Suite Repeater and authorization extensions', 'OWASP ZAP', 'Postman or Bruno for controlled API requests', 'Property-based and integration tests'],
    examples: ['Broken Object Level Authorization', 'Missing function-level authorization', 'Coupon, refund or approval workflow abuse', 'Mass assignment of restricted properties'],
    signals: ['One identity accessing many unrelated object identifiers', 'Low-privilege account calling administrative endpoints', 'Workflow transitions without prerequisite events', 'Unusual export volume'],
    prevent: ['Server-side authorization on every object and action.', 'Deny by default and centralize policy decisions.', 'Model abuse cases and state transitions.', 'Use opaque identifiers only as defense in depth.'],
    detect: ['API gateway and application authorization logs', 'User and entity behavior analytics', 'Business transaction monitoring', 'High-value action alerts'],
    respond: ['Disable the abused path or identity.', 'Determine which records and actions were affected.', 'Correct authorization and add regression tests.', 'Notify owners when legal, privacy or contractual duties apply.'],
    blueTechnology: ['Salt Security', 'Traceable API Security', 'Cequence Security', 'Cloudflare API Shield'],
    mappings: [{ label: 'OWASP Top 10 2025: Broken Access Control', url: 'https://owasp.org/Top10/2025/A01_2025-Broken_Access_Control/' }, { label: 'OWASP API Security Top 10 2023', url: 'https://owasp.org/API-Security/editions/2023/en/0x11-t10/' }],
  },
  {
    id: 'misconfiguration-exposure', title: 'Security misconfiguration and exposed secrets', surface: 'Cloud', objective: 'Exploit unsafe defaults, excessive permissions, public resources, debug features or credentials left in code and configuration.',
    mechanism: 'Modern environments are assembled from many policy layers. One public storage rule, broad identity role, exposed management port or secret in a repository can bypass otherwise strong controls.',
    redValidation: ['Review configuration and policy before active testing.', 'Use canary data and test identities for public-access checks.', 'Do not retrieve real secret values unless evidence handling is approved.', 'Confirm inherited, organization-level and service-level policy.'],
    redTools: ['Prowler or ScoutSuite for cloud posture review', 'Trivy for images and configuration', 'Gitleaks for secret detection', 'Cloud provider policy analyzers'],
    examples: ['Public object storage', 'Over-privileged workload identity', 'Secret committed to source history', 'Exposed Kubernetes dashboard'],
    signals: ['Public-access policy change', 'Secret used from an unusual environment', 'Cloud role assumption outside workload pattern', 'New internet-facing resource'],
    prevent: ['Organization guardrails and policy as code.', 'Short-lived workload identity instead of embedded secrets.', 'Secure landing zones and default-deny exposure.', 'Pre-commit and pipeline secret scanning.'],
    detect: ['Cloud Security Posture Management', 'Cloud Infrastructure Entitlement Management', 'Cloud audit logs', 'Repository and secret-manager alerts'],
    respond: ['Remove exposure and revoke leaked credentials.', 'Determine access history and affected resources.', 'Correct the reusable template or guardrail.', 'Search for copies across builds, logs and forks.'],
    blueTechnology: ['Wiz', 'Palo Alto Prisma Cloud', 'Microsoft Defender for Cloud', 'Orca Security'],
    mappings: [{ label: 'OWASP Top 10 2025: Security Misconfiguration', url: 'https://owasp.org/Top10/2025/A02_2025-Security_Misconfiguration/' }, { label: 'MITRE Cloud Infrastructure Discovery T1580', url: 'https://attack.mitre.org/techniques/T1580/' }],
  },
  {
    id: 'supply-chain', title: 'Software supply-chain compromise', surface: 'Supply chain', objective: 'Reach many downstream systems by compromising a dependency, build process, maintainer, update channel or distribution mechanism.',
    mechanism: 'Trust in packages, build workers, signing keys and vendor updates becomes an attack path. Malicious code may arrive with a legitimate name, signature or approved deployment process.',
    redValidation: ['Model dependency and build trust without inserting malicious production code.', 'Use test packages, isolated registries and disposable build workers.', 'Validate provenance, review and release controls.', 'Coordinate supplier simulation and notification boundaries.'],
    redTools: ['Software Bill of Materials generators', 'Syft and Grype', 'SLSA provenance tooling', 'GitHub dependency review and CodeQL'],
    examples: ['Typosquatted package', 'Compromised build credential', 'Malicious dependency update', 'Vendor update channel compromise'],
    signals: ['Unexpected maintainer or package version', 'Build contacting an unapproved destination', 'Artifact hash or provenance mismatch', 'Signing action from an unusual worker'],
    prevent: ['Pin and review dependencies and registries.', 'Isolate builds and protect signing keys.', 'Require provenance and reproducible release evidence.', 'Maintain supplier incident and replacement plans.'],
    detect: ['Software composition analysis', 'Build and artifact telemetry', 'Endpoint behavior after update', 'Supplier advisory and threat intelligence'],
    respond: ['Stop distribution and quarantine affected versions.', 'Rotate build, repository and signing credentials.', 'Identify every deployed consumer.', 'Rebuild from a trusted state and communicate downstream.'],
    blueTechnology: ['GitHub Advanced Security', 'Snyk', 'JFrog Xray', 'Sonatype Lifecycle'],
    mappings: [{ label: 'OWASP Top 10 2025: Software Supply Chain Failures', url: 'https://owasp.org/Top10/2025/A03_2025-Software_Supply_Chain_Failures/' }, { label: 'MITRE Supply Chain Compromise T1195', url: 'https://attack.mitre.org/techniques/T1195/' }],
  },
  {
    id: 'data-exfiltration', title: 'Collection and data exfiltration', surface: 'Data', objective: 'Locate, stage and remove valuable information while avoiding prevention and detection.',
    mechanism: 'An adversary uses legitimate access, compromised identities or malware to query repositories, create archives and send information through web, cloud, email or covert channels.',
    redValidation: ['Use synthetic classified data and approved destinations.', 'Measure discovery and transfer controls with small bounded samples.', 'Do not copy real customer, employee or regulated data.', 'Validate both technical alerts and human escalation.'],
    redTools: ['Canary files and tokens', 'Data Loss Prevention test identifiers', 'MITRE Caldera for safe collection emulation', 'Cloud access and audit tools'],
    examples: ['Large cloud-storage download', 'Database export by a compromised analyst account', 'Archive staged before ransomware', 'Sensitive content sent to personal cloud storage'],
    signals: ['Unusual query or download volume', 'Archive creation in uncommon paths', 'Transfer to new domains or tenants', 'Sensitive label crossing an unapproved boundary'],
    prevent: ['Classify information and minimize broad access.', 'Use egress controls and tenant restrictions.', 'Protect exports and high-volume actions.', 'Tokenize or mask data where full values are unnecessary.'],
    detect: ['Data Loss Prevention', 'Cloud Access Security Broker', 'Database activity monitoring', 'User and Entity Behavior Analytics'],
    respond: ['Stop active transfer and preserve logs.', 'Revoke the access path and identify affected datasets.', 'Assess notification and contractual obligations.', 'Correct permissions and monitoring gaps.'],
    blueTechnology: ['Microsoft Purview DLP', 'Netskope', 'Zscaler Data Protection', 'Varonis Data Security Platform'],
    mappings: [{ label: 'MITRE ATT&CK Exfiltration', url: 'https://attack.mitre.org/tactics/TA0010/' }, { label: 'MITRE Archive Collected Data T1560', url: 'https://attack.mitre.org/techniques/T1560/' }],
  },
  {
    id: 'denial-service', title: 'Denial of service and resource exhaustion', surface: 'Network', objective: 'Make a service unavailable or financially unsustainable by exhausting network, compute, memory, connection, queue or application resources.',
    mechanism: 'High traffic, expensive requests, amplification, protocol-state exhaustion and algorithmic complexity overwhelm a constrained dependency.',
    redValidation: ['Use a performance environment with agreed ceilings.', 'Increase load gradually and monitor safety thresholds.', 'Test application cost and downstream dependencies, not only bandwidth.', 'Never stress a third-party service without its permission.'],
    redTools: ['k6, JMeter or Locust for controlled load', 'Cloud provider load-testing services', 'Chaos engineering platforms', 'Application Performance Monitoring'],
    examples: ['Distributed network flood', 'Expensive unauthenticated API query', 'Queue or connection-pool exhaustion', 'Cloud cost amplification'],
    signals: ['Sharp request or connection increase', 'Latency and error-rate saturation', 'Autoscaling without throughput improvement', 'Concentration by source, endpoint or query shape'],
    prevent: ['Rate limits, quotas and bounded work.', 'Content Delivery Network and Distributed Denial of Service protection.', 'Caching, graceful degradation and backpressure.', 'Capacity design and cost guardrails.'],
    detect: ['Network flow and edge telemetry', 'Application Performance Monitoring', 'API gateway analytics', 'Cost and capacity anomaly detection'],
    respond: ['Apply traffic shaping and selective degradation.', 'Protect critical paths and preserve operator access.', 'Coordinate with providers and communications teams.', 'Review the constrained dependency after stability returns.'],
    blueTechnology: ['Cloudflare DDoS Protection', 'AWS Shield', 'Google Cloud Armor', 'Akamai App and API Protector'],
    mappings: [{ label: 'MITRE Network Denial of Service T1498', url: 'https://attack.mitre.org/techniques/T1498/' }, { label: 'OWASP API4:2023 Resource Consumption', url: 'https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/' }],
  },
  {
    id: 'network-interception', title: 'Man-in-the-middle, interception and spoofing', surface: 'Network', objective: 'Observe, redirect or modify communications by abusing local-network trust, routing, name resolution or weak transport protection.',
    mechanism: 'A man-in-the-middle attack, also called an adversary-in-the-middle attack, places an attacker on or inside a communication path. Address Resolution Protocol spoofing, evil-twin wireless access, Domain Name System manipulation, routing abuse, malicious proxies, Transport Layer Security downgrades and ignored certificate warnings are common paths.',
    redValidation: ['Use an isolated lab or dedicated test segment.', 'Do not capture unrelated user traffic.', 'Validate certificate, name-resolution and segmentation behavior with test identities.', 'Coordinate wireless tests with facilities and network teams.'],
    redTools: ['Wireshark and tcpdump for packet evidence', 'Bettercap in isolated authorized labs', 'Zeek for protocol visibility', 'dig and resolver logs for Domain Name System validation'],
    examples: ['Evil-twin wireless access point', 'Domain Name System spoofing or cache poisoning', 'Address Resolution Protocol spoofing on a local network', 'Transport Layer Security stripping or downgrade', 'Malicious proxy with an untrusted certificate', 'Routing or gateway manipulation'],
    signals: ['Gateway or Media Access Control address change', 'Unexpected resolver or certificate issuer', 'Duplicate address behavior', 'Transport Layer Security downgrade or validation error'],
    prevent: ['Authenticated and encrypted transport.', 'Secure wireless and network access control.', 'Protected Domain Name System administration.', 'Certificate validation and managed trust stores.'],
    detect: ['Network Detection and Response', 'Zeek protocol logs', 'Wireless intrusion detection', 'Certificate and Domain Name System monitoring'],
    respond: ['Remove rogue network elements.', 'Restore trusted name and route configuration.', 'Rotate credentials exposed in unprotected sessions.', 'Inspect affected endpoints and network devices.'],
    blueTechnology: ['Corelight', 'Cisco Secure Network Analytics', 'Aruba ClearPass', 'Infoblox BloxOne Threat Defense'],
    mappings: [{ label: 'MITRE Adversary-in-the-Middle T1557', url: 'https://attack.mitre.org/techniques/T1557/' }],
  },
  {
    id: 'insider-physical', title: 'Insider misuse and physical access', surface: 'Human', objective: 'Use legitimate proximity, knowledge or authorization to steal, alter, sabotage or bypass controls.',
    mechanism: 'A malicious, coerced or careless insider may misuse approved access, tailgate into facilities, connect removable media or exploit process knowledge that technical controls do not understand.',
    redValidation: ['Define strict privacy and labor boundaries.', 'Use role accounts, test documents and approved physical locations.', 'Do not target personal vulnerability or use humiliation.', 'Measure process and control behavior rather than naming individuals.'],
    redTools: ['Badge-system audit reports', 'Data Loss Prevention test policies', 'Canary documents', 'User and Entity Behavior Analytics'],
    examples: ['Unauthorized bulk customer export', 'Tailgating into a restricted room', 'Use of unmanaged removable media', 'Privileged employee alters a control record'],
    signals: ['Access inconsistent with role or shift', 'Bulk export before resignation or transfer', 'Badge and system activity that do not align', 'Repeated exception or override activity'],
    prevent: ['Least privilege and segregation of duties.', 'Joiner, mover and leaver discipline.', 'Physical zoning and visitor management.', 'Healthy reporting, ethics and support culture.'],
    detect: ['Data access analytics', 'Privileged session monitoring', 'Physical access correlation', 'Case management with privacy controls'],
    respond: ['Protect people and preserve evidence.', 'Restrict access proportionately.', 'Coordinate security, legal, human resources and management.', 'Correct process incentives and control gaps.'],
    blueTechnology: ['Varonis', 'Microsoft Purview Insider Risk Management', 'CyberArk', 'Splunk User Behavior Analytics'],
    mappings: [{ label: 'MITRE Insider Threat resources', url: 'https://www.mitre.org/our-impact/intellectual-property/insider-threat-knowledge-base' }],
  },
  {
    id: 'vulnerability-exploitation', title: 'Known vulnerability and zero-day exploitation', surface: 'Application', objective: 'Use a software weakness to execute code, bypass a security boundary, disclose information or disrupt a service.',
    mechanism: 'An exposed component contains a reachable weakness. Exploitability depends on version, configuration, privileges, mitigations, network path and the attacker\'s ability to satisfy preconditions. A severity score alone does not establish organizational risk.',
    redValidation: ['Confirm the exact product, version, configuration and authorized target.', 'Prefer authenticated inspection, configuration evidence and vendor-supported checks before exploitation.', 'Use a benign proof that does not establish persistence, access real data or disrupt service.', 'Record the attack path, privileges gained, mitigating controls and cleanup evidence.'],
    redTools: ['Nmap NSE with reviewed safe scripts', 'Nuclei with approved non-destructive templates', 'Metasploit only in an isolated or explicitly authorized environment', 'Greenbone or Tenable for vulnerability assessment'],
    examples: ['Remote code execution in an internet-facing appliance', 'Authentication bypass in a management interface', 'Path traversal that exposes a test file', 'Memory-safety weakness in a reachable service'],
    signals: ['Request pattern matching a known exploit path', 'Unexpected process, module or child process after a service request', 'Crash, restart or unusual error near the exploit attempt', 'Known Exploited Vulnerabilities exposure with a reachable path'],
    prevent: ['Maintain supported versions and risk-based remediation service levels.', 'Reduce exposure and privileges before patching when immediate change is unsafe.', 'Use exploit mitigations, isolation and secure configuration.', 'Prioritize reachability, asset value and exploitation evidence together.'],
    detect: ['Endpoint Detection and Response behavior telemetry', 'Intrusion Detection System and Web Application Firewall signatures', 'Application, appliance and crash logs', 'External exposure and vulnerability intelligence'],
    respond: ['Isolate or remove the vulnerable path.', 'Patch, upgrade or apply a validated mitigation.', 'Hunt for behavior associated with successful exploitation.', 'Restore integrity, rotate exposed secrets and retest.'],
    blueTechnology: ['Tenable Vulnerability Management', 'Qualys VMDR', 'Rapid7 InsightVM', 'Microsoft Defender Vulnerability Management'],
    mappings: [{ label: 'MITRE Exploit Public-Facing Application T1190', url: 'https://attack.mitre.org/techniques/T1190/' }, { label: 'CISA Known Exploited Vulnerabilities Catalog', url: 'https://www.cisa.gov/known-exploited-vulnerabilities-catalog' }],
  },
  {
    id: 'cryptographic-failures', title: 'Cryptographic failures and key compromise', surface: 'Data', objective: 'Read, alter, forge or deny protected information by defeating how confidentiality, integrity, authenticity or key custody is implemented.',
    mechanism: 'The failure is usually not mathematics. It is obsolete algorithms, unsafe modes, missing validation, predictable randomness, exposed keys, reused nonces or a lifecycle that leaves sensitive data unprotected.',
    redValidation: ['Inventory where sensitive data is stored, transmitted and transformed.', 'Inspect protocols, algorithms, certificate validation, key access and rotation evidence.', 'Use synthetic data to prove exposure or integrity failure.', 'Do not extract production private keys or decrypt real personal data.'],
    redTools: ['testssl.sh for authorized transport assessment', 'OpenSSL for certificate and protocol inspection', 'TruffleHog or Gitleaks for secret discovery', 'Cloud key-management audit logs'],
    examples: ['Obsolete Transport Layer Security configuration', 'Private key committed to a repository', 'Sensitive database field stored in plaintext', 'Unsigned or unverified software artifact'],
    signals: ['Use of deprecated protocol or cipher', 'Key access by a new identity or workload', 'Certificate validation failure or unexpected issuer', 'High-volume decrypt, sign or export activity'],
    prevent: ['Use approved modern algorithms and protocol configurations.', 'Keep keys in managed hardware-backed or key-management services.', 'Separate key administration, use and audit duties.', 'Rotate, revoke and destroy keys through a defined lifecycle.'],
    detect: ['Certificate and protocol posture monitoring', 'Key-management access logs', 'Secret scanning in source and pipelines', 'Data discovery and encryption-state reporting'],
    respond: ['Revoke and replace compromised keys and certificates.', 'Re-encrypt affected data when required.', 'Identify every system, artifact and partner using the material.', 'Investigate forged, exposed or unreadable records.'],
    blueTechnology: ['HashiCorp Vault', 'AWS Key Management Service', 'Azure Key Vault', 'Google Cloud Key Management Service'],
    mappings: [{ label: 'OWASP Top 10 2025: Cryptographic Failures', url: 'https://owasp.org/Top10/2025/A04_2025-Cryptographic_Failures/' }, { label: 'MITRE Unsecured Credentials T1552', url: 'https://attack.mitre.org/techniques/T1552/' }],
  },
  {
    id: 'container-orchestration', title: 'Container and orchestration attacks', surface: 'Cloud', objective: 'Escape a workload boundary, abuse orchestration identity, alter deployment or control other workloads and cluster resources.',
    mechanism: 'Risk sits across the image, registry, runtime, host kernel, workload identity, admission path, network policy and orchestration control plane. A container is a process isolation boundary, not a complete security boundary by itself.',
    redValidation: ['Use a dedicated cluster or explicitly scoped namespace and service account.', 'Review manifests, role bindings, secrets, admission policy and runtime configuration first.', 'Prove excessive access with test resources rather than disrupting other workloads.', 'Do not attempt host escape outside an isolated lab without explicit authorization.'],
    redTools: ['Trivy for images and configuration', 'kube-bench for benchmark checks', 'Kubescape for posture assessment', 'Falco for runtime behavior validation'],
    examples: ['Privileged container with host filesystem access', 'Over-broad Kubernetes role binding', 'Public registry image replaced or poisoned', 'Exposed orchestration dashboard or API'],
    signals: ['Interactive shell in a production container', 'Sensitive host mount or privileged workload creation', 'New cluster-admin binding', 'Unexpected image digest or unsigned deployment'],
    prevent: ['Use minimal signed images and trusted registries.', 'Apply admission controls, restricted security contexts and least privilege.', 'Separate namespaces and network paths based on trust.', 'Protect control-plane and node administration.'],
    detect: ['Orchestration audit logs', 'Runtime process and file telemetry', 'Image and registry monitoring', 'Cloud and cluster identity analytics'],
    respond: ['Isolate the workload and revoke its identity.', 'Remove malicious or untrusted images from deployment paths.', 'Review node and control-plane integrity.', 'Redeploy from verified definitions and artifacts.'],
    blueTechnology: ['Falco', 'Aqua Security', 'Palo Alto Prisma Cloud', 'Sysdig Secure'],
    mappings: [{ label: 'MITRE Containers Matrix', url: 'https://attack.mitre.org/matrices/enterprise/containers/' }, { label: 'Kubernetes Security Documentation', url: 'https://kubernetes.io/docs/concepts/security/' }],
  },
  {
    id: 'ot-iot-attacks', title: 'Operational technology and IoT attacks', surface: 'Endpoint', objective: 'Manipulate, interrupt or observe physical processes and connected devices where cyber behavior can create safety, production or environmental consequences.',
    mechanism: 'Industrial and connected environments combine long-lived devices, specialized protocols, engineering workstations, remote support and safety dependencies. Availability and safe state may matter more than rapid containment.',
    redValidation: ['Use a digital twin, simulator or approved test cell whenever possible.', 'Include engineering, operations and safety owners in authorization and stop conditions.', 'Begin with passive discovery and configuration review.', 'Do not send active commands to a live process unless the exact action is independently proven safe.'],
    redTools: ['Wireshark for passive protocol inspection', 'Nozomi Networks or Claroty for asset visibility', 'GRASSMARLIN for passive network mapping', 'Vendor engineering and diagnostic tools in a test environment'],
    examples: ['Default credential on a connected device', 'Remote engineering path bypasses the approved jump host', 'Unauthorized programmable controller logic change', 'Insecure firmware or update path'],
    signals: ['New controller programming action', 'Engineering protocol from an unusual source', 'Unexpected device reboot or firmware change', 'Remote session outside an approved maintenance window'],
    prevent: ['Segment enterprise, operations and safety zones with controlled conduits.', 'Use brokered remote access and dedicated administrative workstations.', 'Manage firmware, configuration baselines and removable media.', 'Design fail-safe states and independent safety protection.'],
    detect: ['Passive asset and protocol monitoring', 'Engineering workstation and jump-host telemetry', 'Controller logic and configuration change detection', 'Physical process anomaly monitoring'],
    respond: ['Put process safety and operator authority first.', 'Isolate only with awareness of physical consequences.', 'Preserve controller, historian and engineering evidence.', 'Recover through approved operational procedures and validate safe state.'],
    blueTechnology: ['Claroty xDome', 'Nozomi Networks Guardian', 'Dragos Platform', 'Microsoft Defender for IoT'],
    mappings: [{ label: 'MITRE ATT&CK for ICS', url: 'https://attack.mitre.org/matrices/ics/' }, { label: 'NIST SP 800-82 Rev. 3', url: 'https://csrc.nist.gov/pubs/sp/800/82/r3/final' }],
  },
  {
    id: 'ai-system-attacks', title: 'AI application and model attacks', surface: 'AI', objective: 'Manipulate model behavior, retrieve protected context, abuse connected tools, poison data or steal model and system assets.',
    mechanism: 'Prompt injection, insecure tool permissions, retrieval poisoning, excessive agency, sensitive output and model supply-chain weaknesses exploit the complete AI system rather than only the model.',
    redValidation: ['Use synthetic sensitive data and test tool accounts.', 'Evaluate direct and indirect prompt injection across trusted and untrusted content.', 'Test whether the model can exceed approved data and action boundaries.', 'Record reproducible behavior without publishing harmful bypass strings.'],
    redTools: ['Microsoft PyRIT', 'garak', 'Promptfoo', 'OWASP AI Security and Privacy Guide test cases'],
    examples: ['Indirect prompt injection in a retrieved document', 'Agent tool call exceeds user authority', 'Sensitive system prompt or retrieval leakage', 'Poisoned knowledge source'],
    signals: ['Tool request inconsistent with user intent', 'Repeated policy-override patterns', 'Retrieval from unusual source or tenant', 'Output contains canary data or protected identifiers'],
    prevent: ['Treat model output as untrusted input.', 'Use least-privileged, user-bound tool authorization.', 'Separate trusted instructions from untrusted content.', 'Evaluate models, retrieval, tools and human workflow together.'],
    detect: ['Prompt and tool-call telemetry with privacy controls', 'Content provenance and retrieval monitoring', 'Policy decision logs', 'Human escalation for high-impact actions'],
    respond: ['Disable affected tool or retrieval source.', 'Preserve prompt, context, model and policy versions.', 'Review actions already taken.', 'Update evaluation sets and architecture before re-enabling.'],
    blueTechnology: ['Microsoft AI Red Team PyRIT', 'Lakera Guard', 'Protect AI', 'HiddenLayer Model Security'],
    mappings: [{ label: 'OWASP Top 10 for LLM Applications 2025', url: 'https://genai.owasp.org/llm-top-10/' }, { label: 'MITRE ATLAS', url: 'https://atlas.mitre.org/' }],
  },
  {
    id: 'session-token-theft', title: 'Session hijacking and token theft', surface: 'Identity', objective: 'Reuse a valid session, token or browser state to act as an authenticated user without knowing the password.',
    mechanism: 'Attackers obtain session cookies, refresh tokens, bearer tokens or device authorization through malware, unsafe storage, phishing proxies, logs, browser extensions or application flaws. Multi-factor authentication may already have happened, so the stolen session can bypass the original sign-in challenge.',
    redValidation: ['Use dedicated test identities and short-lived test sessions.', 'Review token storage, cookie attributes, audience, expiry and revocation behavior.', 'Demonstrate reuse only against an explicitly authorized test service.', 'Revoke all test artifacts and confirm invalidation after the exercise.'],
    redTools: ['Browser developer tools in a test profile', 'Burp Suite or OWASP ZAP for authorized session inspection', 'JWT tooling for structure and claim review', 'Canary tokens for safe leak detection'],
    examples: ['Stolen refresh token remains valid after password reset', 'Session cookie lacks secure handling', 'Bearer token appears in an application log', 'Reverse-proxy phishing captures an authenticated session'],
    signals: ['Same session used from incompatible devices or locations', 'Token use after revocation event', 'Unexpected refresh or audience pattern', 'Browser session followed by unusual high-impact action'],
    prevent: ['Use short-lived, audience-bound tokens and protected cookie settings.', 'Bind high-risk actions to fresh authorization and context.', 'Protect endpoints and browsers from credential and token theft.', 'Design reliable global session revocation.'],
    detect: ['Identity-provider sign-in and token telemetry', 'Application session and device context', 'Endpoint browser and process telemetry', 'Risk-based behavior analytics'],
    respond: ['Revoke sessions, refresh tokens and affected credentials.', 'Contain the compromised device and preserve evidence.', 'Review actions performed during the session.', 'Fix token exposure and recovery gaps before restoring access.'],
    blueTechnology: ['Microsoft Entra ID Protection', 'Okta Identity Threat Protection', 'CrowdStrike Falcon Identity Protection', 'Cloudflare Zero Trust'],
    mappings: [{ label: 'MITRE ATT&CK Steal Web Session Cookie', url: 'https://attack.mitre.org/techniques/T1539/' }, { label: 'OWASP Session Management Cheat Sheet', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html' }],
  },
  {
    id: 'client-side-attacks', title: 'Cross-site scripting, CSRF and browser-side abuse', surface: 'Application', objective: 'Make a user browser execute untrusted content or send an unintended authenticated request.',
    mechanism: 'Unsafe output encoding, dangerous browser APIs, weak content controls and missing request-intent protections let attacker-controlled content run in a trusted origin or cause the browser to submit actions with existing credentials.',
    redValidation: ['Use harmless proof strings and test accounts.', 'Trace input to the exact browser context where it is rendered or executed.', 'Verify request-intent controls for state-changing actions.', 'Avoid payloads that read real user data or create durable changes.'],
    redTools: ['Burp Suite DOM Invader and Repeater', 'OWASP ZAP', 'Browser developer tools', 'Semgrep rules for risky browser sinks'],
    examples: ['Stored cross-site scripting in a support ticket', 'DOM-based script execution from a URL fragment', 'Cross-site request forgery changes an email address', 'Unsafe postMessage trust between frames'],
    signals: ['Content Security Policy reports', 'Unexpected script origin or inline execution', 'State-changing request without expected intent token', 'Unusual browser error and client telemetry'],
    prevent: ['Use context-aware output encoding and safe templating.', 'Avoid dangerous DOM sinks and apply strict Content Security Policy.', 'Use SameSite cookies and anti-CSRF controls for state changes.', 'Validate postMessage origin and message structure.'],
    detect: ['Content Security Policy reporting', 'Web Application Firewall and application logs', 'Client-side monitoring', 'Secure code analysis'],
    respond: ['Remove or neutralize stored payloads.', 'Expire affected sessions where exposure is plausible.', 'Patch the rendering or request-intent flaw.', 'Search for earlier exploitation and retest every affected context.'],
    blueTechnology: ['Cloudflare WAF', 'F5 Advanced WAF', 'Semgrep', 'Sentry browser monitoring'],
    mappings: [{ label: 'OWASP Cross Site Scripting Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html' }, { label: 'OWASP CSRF Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html' }],
  },
  {
    id: 'ssrf-deserialization', title: 'SSRF, unsafe deserialization and server-side trust abuse', surface: 'Application', objective: 'Make a trusted server contact an unintended destination or construct unsafe objects from attacker-controlled data.',
    mechanism: 'Server-Side Request Forgery abuses a server network position and credentials. Unsafe deserialization lets attacker-controlled data influence object creation or behavior. Both cross a trust boundary behind the public interface.',
    redValidation: ['Use a controlled callback service and non-sensitive metadata targets.', 'Map allowed destinations, redirects, protocols and parser behavior.', 'Prove reachability with a benign request or inert object.', 'Do not access cloud credentials, internal records or execute commands outside a dedicated lab.'],
    redTools: ['Burp Collaborator or Interactsh for controlled callbacks', 'OWASP ZAP', 'Semgrep or CodeQL for source review', 'Cloud metadata hardening checks'],
    examples: ['Image fetcher reaches an internal administration service', 'Webhook follows an unsafe redirect', 'Serialized object triggers an unexpected gadget path', 'Cloud metadata service reachable from a workload'],
    signals: ['Outbound request to unusual address or protocol', 'Workload request to metadata service', 'Parser exception or unexpected class loading', 'DNS callback from a server that should not resolve external names'],
    prevent: ['Use destination allowlists, safe URL parsing and controlled egress.', 'Block metadata access where not required and use hardened metadata modes.', 'Use simple data formats and explicit schemas instead of native object deserialization.', 'Run services with least privilege and segmented network reach.'],
    detect: ['Egress proxy, DNS and workload telemetry', 'Application request and error logs', 'Cloud flow and metadata access logs', 'Runtime application protection where appropriate'],
    respond: ['Restrict egress and rotate credentials that may have been exposed.', 'Patch the fetch or parsing path.', 'Review internal targets and actions reachable from the workload.', 'Retest redirect, protocol and parser edge cases.'],
    blueTechnology: ['AWS GuardDuty', 'Microsoft Defender for Cloud', 'Google Security Command Center', 'Semgrep and CodeQL'],
    mappings: [{ label: 'OWASP SSRF Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html' }, { label: 'OWASP Deserialization', url: 'https://owasp.org/www-community/vulnerabilities/Deserialization_of_untrusted_data' }],
  },
  {
    id: 'cloud-control-plane', title: 'Cloud control-plane and IAM abuse', surface: 'Cloud', objective: 'Use cloud identities and management APIs to alter infrastructure, create persistence, expose data or disable defenses.',
    mechanism: 'A compromised key, workload role, federated identity or over-broad permission can be used through provider APIs. The attacker may create new credentials, change trust policies, copy snapshots or modify logging without touching a traditional server shell.',
    redValidation: ['Use a sandbox account or project with explicit action limits.', 'Enumerate effective permissions and trust relationships before making changes.', 'Prove excess privilege with a reversible test resource.', 'Do not disable production logs, delete resources or copy real data.'],
    redTools: ['Prowler for posture review', 'ScoutSuite', 'Cloudsplaining or IAM Access Analyzer', 'Provider command-line tools in a sandbox'],
    examples: ['Workload role can assume an administrative role', 'Access key creates a new persistent credential', 'Public snapshot exposes data', 'Logging policy can be altered by a monitored workload'],
    signals: ['New access key, role or trust-policy change', 'Management API from unusual workload or geography', 'Logging or security-service modification', 'Snapshot, export or cross-account sharing event'],
    prevent: ['Use short-lived federation and workload identity instead of static keys.', 'Constrain trust policies and permissions with explicit conditions.', 'Separate security logging and recovery administration.', 'Apply organization-level policy guardrails and change review.'],
    detect: ['Provider audit logs and identity analytics', 'Cloud Security Posture Management', 'Cloud Infrastructure Entitlement Management', 'Configuration and policy drift monitoring'],
    respond: ['Disable affected principals and revoke active sessions.', 'Restore trusted policies from reviewed definitions.', 'Inspect cross-account trust, exports and created credentials.', 'Rebuild compromised workloads and validate logging continuity.'],
    blueTechnology: ['Wiz', 'Palo Alto Prisma Cloud', 'Orca Security', 'Microsoft Defender for Cloud'],
    mappings: [{ label: 'MITRE ATT&CK Cloud Accounts', url: 'https://attack.mitre.org/techniques/T1078/004/' }, { label: 'MITRE ATT&CK Cloud Administration Command', url: 'https://attack.mitre.org/techniques/T1651/' }],
  },
  {
    id: 'database-abuse', title: 'Database privilege abuse and record manipulation', surface: 'Data', objective: 'Read, change, delete or fabricate records by abusing database access, application trust or administrative capability.',
    mechanism: 'Attackers can reach data through direct credentials, injected application queries, over-broad service accounts, insecure exports or privileged tools. Integrity attacks may be harder to notice than bulk theft because the system continues to run.',
    redValidation: ['Use synthetic records and a dedicated test database.', 'Compare application, analyst and administrator permissions.', 'Prove only the smallest unauthorized read or harmless update.', 'Restore all test changes and retain a transaction-level audit trail.'],
    redTools: ['SQLmap only in an explicitly authorized test environment', 'Database-native privilege and audit views', 'Burp Suite for application query paths', 'IBM Guardium or Microsoft Defender for SQL validation'],
    examples: ['Service account can modify approval records', 'Database export stored in an open location', 'Shared administrator credential hides attribution', 'Audit trail can be changed by the same role it monitors'],
    signals: ['Unusual bulk query or export', 'Privileged action outside change window', 'Direct database access bypassing application path', 'Reconciliation difference between ledger and source record'],
    prevent: ['Separate application, analyst and administrative identities.', 'Use least privilege, parameterized queries and protected export paths.', 'Apply dual control to high-impact data changes.', 'Keep audit evidence outside the administrator trust boundary where justified.'],
    detect: ['Database activity monitoring', 'Native database audit logs', 'Application-to-database correlation', 'Business reconciliation and integrity checks'],
    respond: ['Stop the abusive identity without destroying evidence.', 'Identify affected records and downstream use.', 'Restore or correct through approved business procedures.', 'Rotate credentials and repair privilege and audit design.'],
    blueTechnology: ['IBM Guardium', 'Microsoft Defender for SQL', 'Oracle Data Safe', 'Imperva Data Security'],
    mappings: [{ label: 'MITRE ATT&CK Data Manipulation', url: 'https://attack.mitre.org/techniques/T1565/' }, { label: 'OWASP SQL Injection Prevention', url: 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html' }],
  },
  {
    id: 'bec-payment-fraud', title: 'Business email compromise and payment diversion', surface: 'Human', objective: 'Manipulate a trusted business process so money, goods or sensitive information are sent to an attacker-controlled destination.',
    mechanism: 'Attackers combine mailbox access or spoofing with knowledge of real suppliers, executives, invoices and timing. The technical message is only one part; the decisive weakness is often a change or payment process that trusts a single channel.',
    redValidation: ['Use approved simulations with finance, legal and human-resources safeguards.', 'Test the process decision, not only whether someone clicks a link.', 'Use fictional beneficiaries and stop before any real payment instruction.', 'Debrief constructively and fix process and identity controls together.'],
    redTools: ['GoPhish for controlled simulations', 'Microsoft Attack Simulation Training', 'DMARC reporting tools', 'Synthetic invoice and callback scenarios'],
    examples: ['Supplier bank detail changed by email', 'Executive impersonation requests urgent transfer', 'Compromised mailbox inserts itself into a real invoice thread', 'Payroll destination changed through weak help-desk verification'],
    signals: ['New payment destination or payee detail', 'Mailbox forwarding or suspicious OAuth grant', 'Message authentication failure', 'Urgent exception outside established process'],
    prevent: ['Verify payment and beneficiary changes through an independent trusted channel.', 'Use phishing-resistant authentication and secure recovery.', 'Implement Segregation of Duties and transaction limits.', 'Deploy SPF, DKIM and DMARC with monitored enforcement.'],
    detect: ['Email-security and identity telemetry', 'New-beneficiary and transaction analytics', 'Mailbox rule and OAuth monitoring', 'Supplier master-data exception reports'],
    respond: ['Contact the financial institution and affected counterparty immediately.', 'Contain mailbox and identity compromise.', 'Preserve messages, approvals and call records.', 'Correct process gaps and warn related suppliers or teams.'],
    blueTechnology: ['Proofpoint', 'Microsoft Defender for Office 365', 'Abnormal Security', 'Fraud and payment-monitoring platforms'],
    mappings: [{ label: 'MITRE ATT&CK Spearphishing', url: 'https://attack.mitre.org/techniques/T1566/' }, { label: 'FBI Business Email Compromise', url: 'https://www.fbi.gov/how-we-can-help-you/scams-and-safety/common-frauds-and-scams/business-email-compromise' }],
  },
  {
    id: 'firmware-boot-chain', title: 'Firmware, boot-chain and hardware-root compromise', surface: 'Endpoint', objective: 'Gain control below the operating system so malicious behavior survives reinstallation or evades normal endpoint visibility.',
    mechanism: 'Weak update verification, exposed management interfaces, insecure boot configuration or vulnerable firmware can undermine the trust placed in the operating system. Testing is specialized because a mistake can permanently disable hardware.',
    redValidation: ['Use vendor-approved labs, spare devices or emulators.', 'Review signing, update, recovery and management paths before active testing.', 'Use read-only measurement and integrity checks where possible.', 'Never flash unknown firmware to production equipment.'],
    redTools: ['CHIPSEC in a controlled hardware lab', 'Firmware analysis toolkits', 'Secure Boot and Trusted Platform Module measurement tools', 'Vendor update and recovery utilities'],
    examples: ['Unsigned firmware update accepted', 'Management controller exposed with default credentials', 'Secure Boot disabled without alert', 'Boot configuration changed outside approved maintenance'],
    signals: ['Firmware or boot measurement change', 'Unexpected management-controller access', 'Secure Boot or Trusted Platform Module state change', 'Device behavior inconsistent with operating-system telemetry'],
    prevent: ['Require signed updates and protect recovery paths.', 'Use Secure Boot, measured boot and hardware-backed keys where appropriate.', 'Restrict out-of-band management networks and credentials.', 'Maintain vendor support and firmware inventory.'],
    detect: ['Measured-boot attestation', 'Firmware inventory and vulnerability monitoring', 'Out-of-band management logs', 'Hardware health and configuration monitoring'],
    respond: ['Isolate and preserve the device for specialist analysis.', 'Use trusted vendor recovery or replace the affected component.', 'Rotate hardware-bound and administrative credentials.', 'Validate boot measurements before returning to service.'],
    blueTechnology: ['Eclypsium', 'CHIPSEC', 'Microsoft Defender System Guard', 'Vendor platform attestation services'],
    mappings: [{ label: 'MITRE ATT&CK Pre-OS Boot', url: 'https://attack.mitre.org/techniques/T1542/' }, { label: 'NIST Platform Firmware Resiliency', url: 'https://csrc.nist.gov/pubs/sp/800/193/final' }],
  },
];
