import { platformToolCatalog } from './tool-catalog-platforms';

export type ToolProfile = {
  slug: string;
  name: string;
  expansion?: string;
  family: string;
  placement: string;
  purpose: string;
  capabilities: string[];
  boundary: string;
  officialUrl: string;
  keywords: string[];
};

const securityToolCatalog: ToolProfile[] = [
  {
    slug: 'nmap', name: 'Nmap', expansion: 'Network Mapper', family: 'Network discovery and validation',
    placement: 'Runs from an authorized assessment or administration host and sends probes to in-scope network addresses.',
    purpose: 'Discover reachable hosts, exposed ports, services and selected configuration clues so people can validate the real attack surface.',
    capabilities: ['Host discovery', 'Port and service identification', 'Version and operating-system clues', 'Scripted checks through the Nmap Scripting Engine'],
    boundary: 'Scanning can disrupt fragile systems and may be unlawful without permission. Define scope, rate limits and stop conditions first.',
    officialUrl: 'https://nmap.org/', keywords: ['network', 'port', 'service', 'reconnaissance', 'enumeration', 'vapt', 'vulnerability', 'attack surface'],
  },
  {
    slug: 'masscan', name: 'Masscan', family: 'High-speed network discovery',
    placement: 'Runs from a controlled scanning host and is normally used against explicitly approved address ranges.',
    purpose: 'Find open ports across very large address spaces quickly before slower, deeper validation is performed with another tool.',
    capabilities: ['Large-scale port discovery', 'Configurable rates', 'Machine-readable output', 'Follow-up target generation'],
    boundary: 'Its speed can overwhelm networks, monitoring systems or third parties. It is not a vulnerability assessment by itself.',
    officialUrl: 'https://github.com/robertdavidgraham/masscan', keywords: ['masscan', 'network', 'port', 'reconnaissance', 'vapt', 'attack surface', 'internet'],
  },
  {
    slug: 'shodan', name: 'Shodan', family: 'Internet exposure intelligence',
    placement: 'A hosted search service built from internet-wide observations of exposed services and device banners.',
    purpose: 'Help defenders find how assets, services and devices appear from the public internet and investigate broader exposure patterns.',
    capabilities: ['Search exposed services', 'Filter banners and product versions', 'Monitor known assets', 'Explore internet-wide trends'],
    boundary: 'Search results can be incomplete, delayed or misattributed. A result is a lead to validate, not proof of ownership or vulnerability.',
    officialUrl: 'https://www.shodan.io/', keywords: ['shodan', 'internet', 'attack surface', 'asm', 'reconnaissance', 'iot', 'exposure'],
  },
  {
    slug: 'wireshark', name: 'Wireshark', family: 'Network protocol analysis',
    placement: 'Captures or opens packet data from an endpoint, network tap, mirror port or saved capture file.',
    purpose: 'Inspect protocol conversations in detail to troubleshoot behavior, investigate incidents and validate security assumptions.',
    capabilities: ['Packet decoding', 'Protocol filtering', 'Conversation and stream analysis', 'Timing and retransmission investigation'],
    boundary: 'Packet data can contain credentials and personal or confidential information. Capture only with authority and protect the evidence.',
    officialUrl: 'https://www.wireshark.org/', keywords: ['packet', 'network', 'protocol', 'traffic', 'sniffing', 'incident', 'tls', 'dns'],
  },
  {
    slug: 'cisco-packet-tracer', name: 'Cisco Packet Tracer', family: 'Network learning and simulation',
    placement: 'Runs as a desktop learning environment where users build simulated networks from hosts, switches, routers, wireless devices, services and links.',
    purpose: 'Make networking behavior visible and safe to practise before using physical equipment or a production network.',
    capabilities: ['Visual network topology building', 'Simulated device configuration', 'Protocol and packet inspection', 'Scenario-based troubleshooting and Internet of Things exercises'],
    boundary: 'Simulation simplifies hardware, timing and protocol behavior. A successful lab does not prove that the same design, command or capacity is correct for a real environment.',
    officialUrl: 'https://www.netacad.com/cisco-packet-tracer', keywords: ['packet tracer', 'cisco', 'network', 'simulation', 'routing', 'switching', 'osi', 'learning'],
  },
  {
    slug: 'tcpdump', name: 'tcpdump', family: 'Command-line packet capture',
    placement: 'Runs on a Linux, Unix or network appliance interface and writes matching packets to the terminal or a capture file.',
    purpose: 'Capture focused network evidence close to a workload or interface when a graphical analyzer is unavailable or unnecessary.',
    capabilities: ['Interface capture', 'Berkeley Packet Filter expressions', 'Packet headers and payload display', 'Packet capture file output for later analysis'],
    boundary: 'Capture files may contain credentials, personal information and secrets. Use narrow filters, minimize retention and protect access.',
    officialUrl: 'https://www.tcpdump.org/', keywords: ['tcpdump', 'packet', 'pcap', 'network', 'protocol', 'traffic', 'linux', 'incident'],
  },
  {
    slug: 'ncat', name: 'Ncat', expansion: 'Network Connector', family: 'Network connection and relay utility',
    placement: 'Runs from a command line as a client, listener or controlled relay on an authorized host.',
    purpose: 'Create or inspect simple TCP and UDP connections for troubleshooting, protocol learning and controlled security validation.',
    capabilities: ['TCP and UDP client or listener', 'Input and output redirection', 'Transport Layer Security support', 'Proxy and access-control options'],
    boundary: 'The same flexibility can create an unintended listener or data path. Use only on approved hosts, bind narrowly and close test listeners after use.',
    officialUrl: 'https://nmap.org/ncat/', keywords: ['ncat', 'netcat', 'nc', 'network', 'socket', 'port', 'listener', 'linux', 'troubleshooting'],
  },
  {
    slug: 'traceroute', name: 'traceroute', family: 'Network path diagnosis',
    placement: 'Runs from an endpoint or administration host and observes responses from routers along a path toward a destination.',
    purpose: 'Estimate the sequence and delay of reachable network hops to help locate routing, latency or filtering changes.',
    capabilities: ['Hop discovery', 'Round-trip timing', 'Protocol and port variations', 'Path comparison during troubleshooting'],
    boundary: 'Missing or changing hops do not automatically prove failure because routers may filter, rate-limit or route probes differently from application traffic.',
    officialUrl: 'https://traceroute.sourceforge.net/', keywords: ['traceroute', 'tracepath', 'network', 'routing', 'hop', 'latency', 'icmp', 'troubleshooting'],
  },
  {
    slug: 'zeek', name: 'Zeek', family: 'Network security monitoring',
    placement: 'Analyzes traffic observed from a network tap, packet broker, mirrored interface or capture file and produces protocol-rich event logs.',
    purpose: 'Turn network conversations into structured evidence for threat hunting, detection, investigation and protocol analysis.',
    capabilities: ['Protocol-aware logs', 'Connection metadata', 'Scripting and detection logic', 'File and certificate observations'],
    boundary: 'Visibility depends on sensor placement, encrypted traffic, packet loss and parsing coverage. Logs still require context and tested analytics.',
    officialUrl: 'https://zeek.org/', keywords: ['zeek', 'network', 'ndr', 'ids', 'protocol', 'traffic', 'detection', 'monitoring', 'incident'],
  },
  {
    slug: 'burp-suite', name: 'Burp Suite', family: 'Web and API security testing',
    placement: 'Acts as an intercepting proxy between an authorized tester and a web or Application Programming Interface target.',
    purpose: 'Observe, modify, replay and test web traffic while mapping application behavior and validating selected weaknesses.',
    capabilities: ['Proxy and traffic history', 'Request replay', 'Application crawling', 'Automated and manual security testing'],
    boundary: 'Automated testing can alter data or availability. Use test accounts, scope controls, rate limits and an agreed evidence plan.',
    officialUrl: 'https://portswigger.net/burp', keywords: ['web', 'api', 'application', 'vapt', 'proxy', 'owasp', 'testing'],
  },
  {
    slug: 'owasp-zap', name: 'OWASP ZAP', expansion: 'Open Worldwide Application Security Project Zed Attack Proxy', family: 'Web application security testing',
    placement: 'Runs as a desktop tool, daemon or pipeline service between a tester or automated check and an authorized application.',
    purpose: 'Support open-source manual and automated discovery of common web application security issues.',
    capabilities: ['Intercepting proxy', 'Spidering and crawling', 'Passive analysis', 'Active scanning and automation'],
    boundary: 'Active scans can send harmful inputs. Separate passive observation from authorized active testing.',
    officialUrl: 'https://www.zaproxy.org/', keywords: ['zap', 'web', 'api', 'application', 'vapt', 'owasp', 'dast', 'testing'],
  },
  {
    slug: 'sqlmap', name: 'sqlmap', family: 'Database injection validation',
    placement: 'Runs from an authorized testing host against a specific in-scope web or Application Programming Interface request.',
    purpose: 'Automate controlled detection and validation of SQL injection behavior after a potential injection point is identified.',
    capabilities: ['Injection detection', 'Database fingerprinting', 'Technique comparison', 'Controlled evidence collection'],
    boundary: 'Some options can extract or modify data and create operational harm. Use the minimum validation necessary under written rules of engagement.',
    officialUrl: 'https://sqlmap.org/', keywords: ['sqlmap', 'sql injection', 'database', 'web', 'api', 'vapt', 'owasp'],
  },
  {
    slug: 'cyberchef', name: 'CyberChef', family: 'Data decoding and transformation',
    placement: 'Runs in a browser or controlled local instance and applies a visible recipe of transformations to supplied data.',
    purpose: 'Decode, encode, parse, compare and transform technical data during analysis, troubleshooting and learning.',
    capabilities: ['Encoding and decoding', 'Hashing and cryptographic utilities', 'Regular expressions and data extraction', 'Repeatable transformation recipes'],
    boundary: 'Sensitive evidence entered into a hosted browser session may create privacy or handling risk. Use an approved local instance when data cannot leave the environment and verify the meaning of every transformation.',
    officialUrl: 'https://gchq.github.io/CyberChef/', keywords: ['cyberchef', 'decode', 'encode', 'base64', 'hash', 'forensics', 'data', 'analysis'],
  },
  {
    slug: 'hashcat', name: 'hashcat', family: 'Password hash auditing',
    placement: 'Runs on an authorized analysis system against lawfully obtained password hashes, encrypted artifacts or controlled test data.',
    purpose: 'Measure whether stored password hashes resist practical guessing attacks and help validate password policy, storage and migration decisions.',
    capabilities: ['Many hash and cipher formats', 'Wordlist, mask and rule-based guessing', 'CPU and accelerator support', 'Session restore and machine-readable output'],
    boundary: 'Possession of hashes and computing power does not create authority. Use synthetic or explicitly approved evidence, protect cracked credentials, set time and resource limits, and report aggregate weakness without exposing passwords.',
    officialUrl: 'https://hashcat.net/hashcat/', keywords: ['hashcat', 'password', 'hash', 'credential', 'audit', 'vapt', 'authentication'],
  },
  {
    slug: 'john-the-ripper', name: 'John the Ripper', family: 'Password and encrypted-artifact auditing',
    placement: 'Runs on a controlled workstation against approved password databases and supported encrypted files or artifacts.',
    purpose: 'Detect weak passwords and test the practical resistance of supported password hashes and encrypted artifacts.',
    capabilities: ['Automatic hash-type handling', 'Wordlist and rule modes', 'Incremental guessing', 'Support for many password and encrypted-file formats'],
    boundary: 'Recovered secrets are highly sensitive. Define authority, evidence handling, stop conditions and reporting before use, and never test live accounts by repeatedly submitting guesses.',
    officialUrl: 'https://www.openwall.com/john/', keywords: ['john the ripper', 'jtr', 'password', 'hash', 'credential', 'audit', 'vapt'],
  },
  {
    slug: 'ophcrack', name: 'Ophcrack', family: 'Windows password-hash auditing with rainbow tables',
    placement: 'Runs on a controlled analysis system against approved Windows password-hash material and compatible rainbow tables.',
    purpose: 'Demonstrate how legacy Windows password hashes and predictable passwords can be recovered through precomputed time-memory trade-off tables.',
    capabilities: ['Rainbow-table lookup', 'Windows hash-format support', 'Graphical audit workflow', 'Table management and result reporting'],
    boundary: 'This is an offline audit tool, not a login control test. Protect copied hashes and recovered secrets, use only approved evidence, and confirm current operating-system and hash-format support before choosing it.',
    officialUrl: 'https://ophcrack.sourceforge.io/', keywords: ['ophcrack', 'password', 'windows', 'hash', 'rainbow table', 'offline', 'audit', 'authentication'],
  },
  {
    slug: 'l0phtcrack', name: 'L0phtCrack', family: 'Windows password auditing',
    placement: 'Runs as a password-auditing suite against explicitly approved Windows password material in a controlled environment.',
    purpose: 'Assess password-policy resistance and identify weak Windows passwords through offline audit methods and reporting.',
    capabilities: ['Windows password auditing', 'Wordlist and brute-force strategies', 'Password-policy analysis', 'Audit reporting'],
    boundary: 'Confirm the supported platform, format and maintenance status before use. Treat input hashes and recovered passwords as restricted evidence and do not collect production secrets when synthetic or scoped data can answer the question.',
    officialUrl: 'https://gitlab.com/l0phtcrack/l0phtcrack', keywords: ['l0phtcrack', 'l0pht crack', 'lc7', 'password', 'windows', 'hash', 'offline', 'audit'],
  },
  {
    slug: 'rainbowcrack', name: 'RainbowCrack', family: 'Rainbow-table generation and lookup',
    placement: 'Runs on a controlled analysis system to create, sort, convert and search time-memory trade-off tables for approved hash research.',
    purpose: 'Teach and test the economics of precomputed password-hash lookup and why unique salts defeat reusable rainbow tables.',
    capabilities: ['Rainbow-table generation', 'Table sorting and conversion', 'Hash lookup', 'CPU and accelerator support'],
    boundary: 'Rainbow tables are specialized and do not replace modern password auditing. Use synthetic or approved hashes, protect results, and explain that unique salts remove the table-reuse advantage.',
    officialUrl: 'https://project-rainbowcrack.com/', keywords: ['rainbowcrack', 'rainbow table', 'password', 'hash', 'offline', 'time memory tradeoff', 'audit'],
  },
  {
    slug: 'thc-hydra', name: 'THC Hydra', family: 'Online network-login testing',
    placement: 'Runs from an authorized test host and submits authentication attempts to explicitly in-scope live network services.',
    purpose: 'Validate how supported authentication services resist controlled online guessing and whether throttling, lockout, monitoring and multi-factor controls behave as intended.',
    capabilities: ['Many network authentication protocols', 'Parallel test execution', 'User and candidate-list input', 'Graphical front end through Hydra GTK'],
    boundary: 'This touches live authentication and can lock accounts, trigger response or disrupt service. Use synthetic accounts where possible, low rates, service-owner monitoring, written scope and immediate stop conditions.',
    officialUrl: 'https://github.com/vanhauser-thc/thc-hydra', keywords: ['hydra', 'thc hydra', 'password', 'online', 'login', 'authentication', 'network', 'audit', 'vapt'],
  },
  {
    slug: 'medusa', name: 'Medusa', family: 'Parallel network-login auditing',
    placement: 'Runs from an authorized assessment host and submits scoped login attempts through protocol modules to approved services.',
    purpose: 'Evaluate live-service authentication controls across supported protocols in a controlled security assessment.',
    capabilities: ['Parallel host, user and password testing', 'Modular service support', 'Flexible target input', 'Support for common remote-authentication protocols'],
    boundary: 'Do not confuse this project with mobile-security or command-and-control tools that share the name. Live attempts can cause lockout and outage, so use written authorization, synthetic identities, attempt limits, monitoring and cleanup.',
    officialUrl: 'https://github.com/jmk-foofus/medusa', keywords: ['medusa', 'foofus', 'password', 'online', 'login', 'authentication', 'network', 'audit', 'vapt'],
  },
  {
    slug: 'semgrep', name: 'Semgrep', family: 'Static application security testing',
    placement: 'Runs against source code in a developer workstation, source repository, pull request or delivery pipeline.',
    purpose: 'Find code patterns associated with security defects, quality issues and organization-specific rules before software runs.',
    capabilities: ['Pattern-based code analysis', 'Custom rules', 'Pull-request feedback', 'Supply-chain and secrets checks in commercial offerings'],
    boundary: 'A finding is a hypothesis about code, not proof of exploitability. Tune rules, review context and combine static analysis with other testing.',
    officialUrl: 'https://semgrep.dev/', keywords: ['semgrep', 'sast', 'source code', 'secure sdlc', 'devsecops', 'pipeline', 'software'],
  },
  {
    slug: 'github-codeql', name: 'GitHub CodeQL', family: 'Semantic code analysis',
    placement: 'Analyzes supported source-code repositories locally or through GitHub code-scanning workflows.',
    purpose: 'Treat code as queryable data so teams can identify complex data-flow and control-flow vulnerability patterns.',
    capabilities: ['Semantic code database', 'Data-flow queries', 'Security query packs', 'Pull-request and repository integration'],
    boundary: 'Language support and query quality determine coverage. It does not replace design review, dynamic testing or manual validation.',
    officialUrl: 'https://codeql.github.com/', keywords: ['codeql', 'sast', 'source code', 'secure sdlc', 'devsecops', 'pipeline'],
  },
  {
    slug: 'trivy', name: 'Trivy', family: 'Cloud-native and supply-chain scanning',
    placement: 'Runs on developer machines and in pipelines against repositories, container images, filesystems, Kubernetes and Infrastructure as Code.',
    purpose: 'Identify known vulnerabilities, exposed secrets and selected misconfigurations across build artifacts and cloud-native definitions.',
    capabilities: ['Container and package vulnerability scanning', 'Infrastructure as Code checks', 'Secret detection', 'Software Bill of Materials generation'],
    boundary: 'Scanner coverage depends on inventories and data sources. Prioritize with exploitability, reachability, asset importance and compensating controls.',
    officialUrl: 'https://trivy.dev/', keywords: ['trivy', 'container', 'kubernetes', 'sca', 'sbom', 'cloud', 'devsecops', 'supply chain'],
  },
  {
    slug: 'greenbone', name: 'Greenbone Community Edition', family: 'Vulnerability assessment',
    placement: 'Runs as a scanner and management service that probes authorized hosts and services from selected network locations.',
    purpose: 'Identify known vulnerabilities and configuration weaknesses across reachable systems using maintained test feeds.',
    capabilities: ['Network vulnerability scanning', 'Authenticated checks', 'Asset and result management', 'Remediation-oriented reporting'],
    boundary: 'Coverage depends on reachability, credentials, feed currency and asset inventory. Findings require ownership, validation and retesting.',
    officialUrl: 'https://greenbone.github.io/docs/latest/', keywords: ['openvas', 'greenbone', 'vulnerability', 'scanner', 'vapt', 'patch', 'host'],
  },
  {
    slug: 'tenable-nessus', name: 'Tenable Nessus', family: 'Vulnerability assessment',
    placement: 'Runs from a scanning host or managed platform against authorized networks, servers, endpoints and selected cloud assets.',
    purpose: 'Discover known vulnerabilities and configuration weaknesses, including deeper checks when approved credentials are available.',
    capabilities: ['Authenticated and unauthenticated scans', 'Vulnerability plugins', 'Configuration checks', 'Prioritization data'],
    boundary: 'A scanner score is not business risk. Account for exposure, exploit activity, asset value, control coverage and false positives.',
    officialUrl: 'https://www.tenable.com/products/nessus', keywords: ['nessus', 'tenable', 'vulnerability', 'scanner', 'vapt', 'patch', 'host'],
  },
  {
    slug: 'microsoft-defender-endpoint', name: 'Microsoft Defender for Endpoint', family: 'Endpoint Detection and Response',
    placement: 'Uses endpoint sensors plus a cloud management and analytics plane across workstations and servers.',
    purpose: 'Prevent, detect, investigate and respond to suspicious activity on managed endpoints.',
    capabilities: ['Endpoint telemetry', 'Behavioral detections', 'Investigation and hunting', 'Response actions and vulnerability insights'],
    boundary: 'Effective operation depends on coverage, tamper protection, tuned policy, skilled investigation and safe response authority.',
    officialUrl: 'https://www.microsoft.com/en-us/security/business/endpoint-security/microsoft-defender-endpoint', keywords: ['edr', 'endpoint', 'xdr', 'defender', 'soc', 'detection', 'response'],
  },
  {
    slug: 'crowdstrike-falcon', name: 'CrowdStrike Falcon', family: 'Endpoint Detection and Response',
    placement: 'Uses an endpoint sensor connected to a cloud-native security platform and operating console.',
    purpose: 'Provide endpoint prevention, telemetry, detection, investigation, hunting and response capabilities.',
    capabilities: ['Endpoint telemetry', 'Behavioral detection', 'Threat hunting', 'Host containment and response workflows'],
    boundary: 'A high-privilege sensor is also an operational dependency. Rollout, update safety, recovery and service ownership matter.',
    officialUrl: 'https://www.crowdstrike.com/en-us/platform/endpoint-security/falcon-insight-xdr/', keywords: ['edr', 'endpoint', 'xdr', 'crowdstrike', 'falcon', 'soc', 'detection'],
  },
  {
    slug: 'sentinelone-singularity', name: 'SentinelOne Singularity', family: 'Endpoint and extended detection',
    placement: 'Combines endpoint agents with centralized cloud analytics, investigation and response.',
    purpose: 'Detect and respond to malicious or anomalous endpoint activity and connect selected signals across security domains.',
    capabilities: ['Endpoint protection', 'Behavioral detections', 'Storyline investigation', 'Automated and analyst-directed response'],
    boundary: 'Automation needs explicit approval boundaries, exclusions and recovery paths to avoid disrupting legitimate operations.',
    officialUrl: 'https://www.sentinelone.com/platform/', keywords: ['edr', 'endpoint', 'xdr', 'sentinelone', 'soc', 'detection'],
  },
  {
    slug: 'cortex-xdr', name: 'Palo Alto Networks Cortex XDR', family: 'Extended Detection and Response',
    placement: 'A cloud analytics and investigation layer that combines endpoint data with selected network, identity, cloud and third-party signals.',
    purpose: 'Correlate activity across control planes so analysts can investigate a broader incident rather than isolated alerts.',
    capabilities: ['Cross-source analytics', 'Endpoint detection and response', 'Incident stitching', 'Hunting and response orchestration'],
    boundary: 'XDR is a product architecture, not automatic organizational integration. Data access, ownership and operating processes still decide value.',
    officialUrl: 'https://www.paloaltonetworks.com/cortex/cortex-xdr', keywords: ['xdr', 'edr', 'ndr', 'endpoint', 'cortex', 'soc', 'detection'],
  },
  {
    slug: 'microsoft-sentinel', name: 'Microsoft Sentinel', family: 'Security Information and Event Management',
    placement: 'A cloud security analytics service that ingests events and alerts from identities, endpoints, applications, networks and cloud services.',
    purpose: 'Centralize security evidence, correlate detections, support hunting and coordinate investigation and response workflows.',
    capabilities: ['Log ingestion and analytics', 'Detection rules', 'Incident management', 'Automation and threat hunting'],
    boundary: 'Collection cost and alert volume can grow without an evidence plan. Define priority use cases, retention and response ownership.',
    officialUrl: 'https://www.microsoft.com/en-us/security/business/siem-and-xdr/microsoft-sentinel', keywords: ['siem', 'soar', 'sentinel', 'logs', 'soc', 'detection', 'analytics'],
  },
  {
    slug: 'splunk-enterprise-security', name: 'Splunk Enterprise Security', family: 'Security Information and Event Management',
    placement: 'Runs as a security analytics application over centrally collected machine data in Splunk-managed environments.',
    purpose: 'Support detection, investigation, risk-based alerting, hunting and security operations reporting across many data sources.',
    capabilities: ['Search and correlation', 'Detection content', 'Risk-based alerting', 'Investigation workflows and dashboards'],
    boundary: 'Useful detections require normalized data, tested logic, context and an analyst process. More ingested logs do not guarantee more security.',
    officialUrl: 'https://www.splunk.com/en_us/products/enterprise-security.html', keywords: ['siem', 'splunk', 'logs', 'soc', 'detection', 'analytics'],
  },
  {
    slug: 'elastic-security', name: 'Elastic Security', family: 'Security analytics and detection',
    placement: 'Uses the Elastic Stack to collect, search and analyze endpoint, network, cloud and application security data.',
    purpose: 'Support detection engineering, hunting, investigation and selected endpoint response through a searchable analytics platform.',
    capabilities: ['Search and analytics', 'Detection rules', 'Endpoint integrations', 'Cases and investigation timelines'],
    boundary: 'Open flexibility creates design responsibility. Teams must govern schemas, detections, access, retention and operating cost.',
    officialUrl: 'https://www.elastic.co/security', keywords: ['siem', 'elastic', 'logs', 'soc', 'detection', 'analytics'],
  },
  {
    slug: 'palo-alto-ngfw', name: 'Palo Alto Networks Next-Generation Firewall', family: 'Network security gateway',
    placement: 'Runs inline at data-center, campus, branch, cloud or virtual network boundaries.',
    purpose: 'Enforce network access policy while inspecting applications, users and selected threat or content patterns.',
    capabilities: ['Stateful traffic control', 'Application-aware policy', 'Threat prevention', 'Virtual and cloud deployment options'],
    boundary: 'A firewall only sees traffic that crosses it and that it can interpret. Identity, endpoint, application and data controls remain necessary.',
    officialUrl: 'https://www.paloaltonetworks.com/network-security/next-generation-firewall', keywords: ['firewall', 'ngfw', 'network', 'segmentation', 'gateway', 'ips'],
  },
  {
    slug: 'fortigate', name: 'Fortinet FortiGate', family: 'Network security gateway',
    placement: 'Runs as physical, virtual or cloud firewall infrastructure at network boundaries and segmentation points.',
    purpose: 'Control traffic and combine selected routing, virtual private network and threat-prevention functions.',
    capabilities: ['Stateful firewalling', 'Virtual Private Network', 'Application control', 'Intrusion prevention and secure networking'],
    boundary: 'Consolidation can simplify operations but also concentrate failure and policy risk. Test changes and maintain recovery access.',
    officialUrl: 'https://www.fortinet.com/products/next-generation-firewall', keywords: ['firewall', 'fortigate', 'network', 'segmentation', 'gateway', 'ips'],
  },
  {
    slug: 'cloudflare-waf', name: 'Cloudflare Web Application Firewall', family: 'Web application and edge security',
    placement: 'Runs at an internet edge between users and web applications or Application Programming Interfaces routed through the service.',
    purpose: 'Inspect and control web requests using managed and custom rules before traffic reaches an origin service.',
    capabilities: ['Managed vulnerability rules', 'Custom request rules', 'Rate limiting integrations', 'Edge visibility and mitigation'],
    boundary: 'A Web Application Firewall cannot fix broken authorization or business logic. Route coverage and origin bypass must be controlled.',
    officialUrl: 'https://www.cloudflare.com/application-services/products/waf/', keywords: ['waf', 'web', 'api', 'firewall', 'cloudflare', 'edge', 'application security'],
  },
  {
    slug: 'wiz', name: 'Wiz', family: 'Cloud-native application protection platform',
    placement: 'Connects to cloud control planes and selected workloads, repositories and delivery systems through a cloud security platform.',
    purpose: 'Map cloud assets, configuration, vulnerabilities, identities, data and attack paths so teams can prioritize connected exposure.',
    capabilities: ['Cloud posture visibility', 'Attack-path analysis', 'Vulnerability and entitlement context', 'Data and workload risk views'],
    boundary: 'A broad graph still depends on connector coverage, permissions, asset ownership and timely remediation workflows.',
    officialUrl: 'https://www.wiz.io/platform', keywords: ['cnapp', 'cspm', 'cloud', 'wiz', 'posture', 'attack path', 'ciem'],
  },
  {
    slug: 'prisma-cloud', name: 'Palo Alto Networks Prisma Cloud', family: 'Cloud-native application protection platform',
    placement: 'Spans source, build, cloud control plane and workload runtime through connected cloud security services.',
    purpose: 'Combine selected code, posture, entitlement, workload and application security signals across cloud-native lifecycles.',
    capabilities: ['Cloud posture management', 'Workload protection', 'Infrastructure as Code checks', 'Entitlement and application context'],
    boundary: 'Platform breadth does not remove the need for clear ownership between developers, platform teams, security and cloud operations.',
    officialUrl: 'https://www.paloaltonetworks.com/prisma/cloud', keywords: ['cnapp', 'cspm', 'cloud', 'prisma', 'posture', 'container', 'ciem'],
  },
  {
    slug: 'metasploit-framework', name: 'Metasploit Framework', family: 'Authorized exploit validation',
    placement: 'Runs from a controlled assessment host against explicitly authorized targets in a lab or scoped test environment.',
    purpose: 'Validate whether a known weakness is practically exploitable and demonstrate the minimum consequence needed for a defensible finding.',
    capabilities: ['Exploit modules', 'Payload and session handling', 'Auxiliary validation modules', 'Reproducible testing workflows'],
    boundary: 'Exploit code can change data, availability and access. Written authorization, safe payloads, test accounts, stop conditions and cleanup are mandatory.',
    officialUrl: 'https://www.metasploit.com/', keywords: ['metasploit', 'exploit', 'penetration testing', 'vapt', 'validation', 'red team'],
  },
  {
    slug: 'nuclei', name: 'Nuclei', family: 'Template-based exposure validation',
    placement: 'Runs from an authorized host or delivery workflow against approved web, network and cloud targets using selected templates.',
    purpose: 'Execute repeatable checks for known exposures and misconfigurations at scale while keeping the test logic visible as templates.',
    capabilities: ['Template-based checks', 'Workflow chaining', 'Custom templates', 'Machine-readable output'],
    boundary: 'Community templates vary in quality and safety. Review templates, pin versions, control rates and validate findings before escalation.',
    officialUrl: 'https://docs.projectdiscovery.io/tools/nuclei/overview', keywords: ['nuclei', 'vulnerability', 'scanner', 'template', 'web', 'cloud', 'vapt'],
  },
  {
    slug: 'ffuf', name: 'ffuf', expansion: 'Fuzz Faster U Fool', family: 'Web content and input discovery',
    placement: 'Runs from an authorized testing host and sends wordlist-driven requests to a scoped web application or Application Programming Interface.',
    purpose: 'Discover unlinked paths, parameters, virtual hosts and input behaviors that require deeper manual review.',
    capabilities: ['Directory and file discovery', 'Parameter fuzzing', 'Virtual-host discovery', 'Response filtering'],
    boundary: 'High request volume can create disruption, logs and lockouts. Use narrow lists, rate limits, safe accounts and approved targets.',
    officialUrl: 'https://github.com/ffuf/ffuf', keywords: ['ffuf', 'fuzzing', 'web', 'api', 'content discovery', 'vapt'],
  },
  {
    slug: 'gitleaks', name: 'Gitleaks', family: 'Secret detection',
    placement: 'Scans source repositories, commits, directories and delivery workflows before exposed credentials reach production.',
    purpose: 'Detect patterns that may represent passwords, tokens, private keys or other secrets in version-controlled material.',
    capabilities: ['Repository history scanning', 'Pre-commit checks', 'Custom rules', 'Pipeline integration'],
    boundary: 'Pattern matching creates false positives and cannot prove whether a secret is valid. Confirm safely, revoke exposed credentials and investigate history.',
    officialUrl: 'https://gitleaks.io/', keywords: ['gitleaks', 'secret', 'source code', 'git', 'devsecops', 'pipeline'],
  },
  {
    slug: 'owasp-dependency-check', name: 'OWASP Dependency-Check', family: 'Software composition analysis',
    placement: 'Runs against application dependencies on a workstation or delivery pipeline and maps them to known vulnerability data.',
    purpose: 'Identify third-party components that may correspond to publicly known vulnerabilities.',
    capabilities: ['Dependency inventory', 'Known-vulnerability matching', 'Build integration', 'Reports and suppression rules'],
    boundary: 'Name and version matching can be incomplete or ambiguous. Confirm reachability, exploitability, asset context and the safety of an upgrade.',
    officialUrl: 'https://owasp.org/www-project-dependency-check/', keywords: ['dependency-check', 'sca', 'dependency', 'cve', 'software supply chain', 'sbom'],
  },
  {
    slug: 'snyk-open-source', name: 'Snyk Open Source', family: 'Software composition analysis',
    placement: 'Connects to repositories, developer tools and pipelines to analyze supported dependency manifests and graphs.',
    purpose: 'Find known vulnerable open-source packages, explain dependency paths and support remediation choices.',
    capabilities: ['Dependency graph analysis', 'Vulnerability intelligence', 'Fix guidance', 'Repository and pipeline integration'],
    boundary: 'A vendor risk score is an input, not the business decision. Validate use, reachability, upgrade impact, compensating controls and actual deployment.',
    officialUrl: 'https://snyk.io/product/open-source-security-management/', keywords: ['snyk', 'sca', 'dependency', 'cve', 'software supply chain'],
  },
  {
    slug: 'sonarqube', name: 'SonarQube', family: 'Code quality and static analysis',
    placement: 'Analyzes supported source code in a central server, developer workflow or continuous-integration pipeline.',
    purpose: 'Identify maintainability, reliability and selected security issues while enforcing agreed quality gates.',
    capabilities: ['Static code rules', 'Quality gates', 'Pull-request analysis', 'Security hotspot review'],
    boundary: 'Rule coverage and developer review determine value. A passed quality gate is not proof that the design or running application is secure.',
    officialUrl: 'https://www.sonarsource.com/products/sonarqube/', keywords: ['sonarqube', 'sast', 'code quality', 'pipeline', 'secure sdlc'],
  },
  {
    slug: 'hashicorp-vault', name: 'HashiCorp Vault', family: 'Secrets and key management',
    placement: 'Sits between authenticated workloads or operators and protected secrets, encryption services or dynamic credentials.',
    purpose: 'Centralize controlled access to secrets and support short-lived credentials, encryption services and auditable use.',
    capabilities: ['Secret storage', 'Dynamic credentials', 'Encryption as a service', 'Leases, rotation and audit devices'],
    boundary: 'Vault becomes a critical trust dependency. Authentication, policies, unseal and recovery design, audit integrity and client-side handling remain essential.',
    officialUrl: 'https://developer.hashicorp.com/vault/docs', keywords: ['vault', 'secret', 'key management', 'credential', 'pki', 'machine identity'],
  },
  {
    slug: 'cyberark-pam', name: 'CyberArk Privileged Access Manager', family: 'Privileged access management',
    placement: 'Brokers or manages high-impact human and machine access between identities and target systems.',
    purpose: 'Discover, protect, rotate, monitor and constrain privileged credentials and sessions.',
    capabilities: ['Credential vaulting', 'Password rotation', 'Session isolation and recording', 'Privileged-account discovery'],
    boundary: 'Protection applies only to onboarded accounts and paths. Emergency access, local administrators, service accounts and cloud roles need complete coverage.',
    officialUrl: 'https://www.cyberark.com/products/privileged-access-manager/', keywords: ['cyberark', 'pam', 'privileged access', 'vault', 'session', 'identity'],
  },
  {
    slug: 'suricata', name: 'Suricata', family: 'Network threat detection',
    placement: 'Analyzes packets or flows from a network tap, mirror port, inline path or capture file.',
    purpose: 'Detect selected malicious or policy-relevant network behavior using signatures, protocol inspection and flow context.',
    capabilities: ['Intrusion detection', 'Intrusion prevention modes', 'Protocol logging', 'File and flow inspection'],
    boundary: 'Encrypted traffic, asymmetric routing, packet loss and weak tuning reduce visibility. Signatures require maintenance and investigation context.',
    officialUrl: 'https://suricata.io/', keywords: ['suricata', 'ids', 'ips', 'network', 'detection', 'packet'],
  },
  {
    slug: 'snort', name: 'Snort', family: 'Network intrusion detection and prevention',
    placement: 'Inspects network traffic from an inline or monitoring sensor at selected network boundaries.',
    purpose: 'Apply rules and protocol inspection to identify or block selected network activity.',
    capabilities: ['Packet inspection', 'Rule-based detection', 'Inline prevention', 'Protocol analysis'],
    boundary: 'Sensor placement and rule quality determine coverage. Blocking rules need change control and recovery paths to avoid service disruption.',
    officialUrl: 'https://www.snort.org/', keywords: ['snort', 'ids', 'ips', 'network', 'signature', 'detection'],
  },
  {
    slug: 'osquery', name: 'osquery', family: 'Endpoint telemetry and fleet interrogation',
    placement: 'Runs an agent or command-line interface on supported endpoints and exposes operating-system state through SQL-like tables.',
    purpose: 'Query processes, users, files, packages, network state and configuration for inventory, detection and investigation.',
    capabilities: ['System-state queries', 'Scheduled telemetry', 'File-integrity monitoring', 'Fleet investigation'],
    boundary: 'A query sees the tables and cadence configured on enrolled hosts. It is not a complete prevention or response platform by itself.',
    officialUrl: 'https://www.osquery.io/', keywords: ['osquery', 'endpoint', 'telemetry', 'hunting', 'inventory', 'linux'],
  },
  {
    slug: 'sysmon', name: 'Sysmon', expansion: 'System Monitor', family: 'Windows endpoint telemetry',
    placement: 'Runs as a Windows system service and driver, writing selected process, network, file and other events to the Windows event log.',
    purpose: 'Create detailed endpoint evidence that can support detection engineering, hunting and incident investigation.',
    capabilities: ['Process creation events', 'Network connection events', 'File and registry observations', 'Configurable event filtering'],
    boundary: 'Sysmon produces telemetry, not conclusions. Configuration, collection, retention, correlation and adversary tampering affect assurance.',
    officialUrl: 'https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon', keywords: ['sysmon', 'windows', 'endpoint', 'telemetry', 'event log', 'detection'],
  },
  {
    slug: 'velociraptor', name: 'Velociraptor', family: 'Endpoint visibility and digital forensics',
    placement: 'Uses endpoint clients and a server to collect targeted artifacts and run approved hunts across a fleet.',
    purpose: 'Support rapid endpoint investigation, evidence collection and threat hunting at scale.',
    capabilities: ['Artifact collection', 'Fleet hunting', 'Forensic triage', 'Custom query language and workflows'],
    boundary: 'Remote collection is powerful and can expose sensitive data or affect endpoints. Restrict authority, scope queries and preserve chain of custody.',
    officialUrl: 'https://docs.velociraptor.app/', keywords: ['velociraptor', 'dfir', 'forensics', 'endpoint', 'hunting', 'incident response'],
  },
  {
    slug: 'volatility', name: 'Volatility 3', family: 'Memory forensics',
    placement: 'Runs on a forensic workstation against an acquired memory image from a supported operating system.',
    purpose: 'Reconstruct processes, modules, network artifacts and other volatile state that may not survive shutdown.',
    capabilities: ['Process analysis', 'Kernel and module inspection', 'Network artifact recovery', 'Plugin-based memory analysis'],
    boundary: 'Results depend on acquisition quality, operating-system support and analyst interpretation. Preserve the original image and document every transformation.',
    officialUrl: 'https://volatilityfoundation.org/', keywords: ['volatility', 'memory', 'forensics', 'dfir', 'malware', 'incident response'],
  },
  {
    slug: 'yara', name: 'YARA', family: 'Malware and artifact pattern matching',
    placement: 'Runs against files, memory or collected artifacts on analysis systems and selected security platforms.',
    purpose: 'Describe combinations of strings and binary characteristics that help identify related malware or suspicious artifacts.',
    capabilities: ['Rule-based matching', 'Text and binary patterns', 'Conditions and modules', 'Integration into analysis workflows'],
    boundary: 'A match is a lead, not automatic proof of maliciousness. Broad rules create false positives; narrow rules can miss variants.',
    officialUrl: 'https://virustotal.github.io/yara/', keywords: ['yara', 'malware', 'rule', 'signature', 'forensics', 'threat hunting'],
  },
  {
    slug: 'autopsy', name: 'Autopsy', family: 'Digital forensic analysis',
    placement: 'Runs on a forensic workstation and analyzes acquired disk images, filesystems and related evidence.',
    purpose: 'Support structured examination, timeline construction, artifact recovery and reporting for digital investigations.',
    capabilities: ['Filesystem analysis', 'Keyword and artifact search', 'Timeline analysis', 'Case management and reporting'],
    boundary: 'Acquisition and handling determine evidential integrity. Work from verified copies, document tools and methods, and respect legal authority.',
    officialUrl: 'https://www.autopsy.com/', keywords: ['autopsy', 'disk', 'forensics', 'dfir', 'evidence', 'incident response'],
  },
  {
    slug: 'ghidra', name: 'Ghidra', family: 'Software reverse engineering',
    placement: 'Runs on an isolated analysis workstation against binaries the analyst is authorized to inspect.',
    purpose: 'Disassemble, decompile and analyze compiled software to understand behavior, vulnerabilities or malicious logic.',
    capabilities: ['Disassembly', 'Decompilation', 'Cross-reference analysis', 'Scripting and processor support'],
    boundary: 'Reverse engineering may involve intellectual-property and license restrictions. Untrusted samples require isolated systems and safe handling.',
    officialUrl: 'https://ghidra-sre.org/', keywords: ['ghidra', 'reverse engineering', 'malware', 'binary', 'decompiler'],
  },
  {
    slug: 'misp', name: 'MISP', expansion: 'Malware Information Sharing Platform', family: 'Threat intelligence sharing',
    placement: 'Runs as a threat-intelligence platform that stores, relates and exchanges structured events, indicators and context.',
    purpose: 'Support controlled sharing and analysis of threat information across teams and trusted communities.',
    capabilities: ['Indicator and event management', 'Taxonomies and galaxies', 'Sharing communities', 'Application Programming Interface integration'],
    boundary: 'An indicator can be stale, benign in another context or intentionally deceptive. Apply confidence, source, time and handling labels.',
    officialUrl: 'https://www.misp-project.org/', keywords: ['misp', 'threat intelligence', 'ioc', 'sharing', 'stix', 'taxii'],
  },
  {
    slug: 'opencti', name: 'OpenCTI', expansion: 'Open Cyber Threat Intelligence', family: 'Threat intelligence knowledge platform',
    placement: 'Aggregates structured threat knowledge from sources and integrations into a connected analysis model.',
    purpose: 'Relate threat actors, campaigns, techniques, infrastructure, vulnerabilities, observables and reports for analysis and operational use.',
    capabilities: ['Structured threat knowledge', 'Relationship analysis', 'Connectors and enrichment', 'Case and report support'],
    boundary: 'A graph can amplify poor sources and ambiguous identity. Preserve provenance, confidence, timestamps and handling restrictions.',
    officialUrl: 'https://docs.opencti.io/latest/', keywords: ['opencti', 'threat intelligence', 'stix', 'knowledge graph', 'ioc'],
  },
  {
    slug: 'falco', name: 'Falco', family: 'Cloud-native runtime security',
    placement: 'Observes supported Linux and container runtime activity and evaluates events against behavioral rules.',
    purpose: 'Detect unexpected runtime behavior such as suspicious process, file, privilege or network activity in cloud-native workloads.',
    capabilities: ['Runtime event collection', 'Rule-based detection', 'Container and Kubernetes context', 'Alert integrations'],
    boundary: 'Runtime detection does not replace secure images, identity or configuration. Kernel visibility, rule quality and workload context affect coverage.',
    officialUrl: 'https://falco.org/', keywords: ['falco', 'container', 'kubernetes', 'runtime', 'detection', 'linux'],
  },
  {
    slug: 'kube-bench', name: 'kube-bench', family: 'Kubernetes configuration assessment',
    placement: 'Runs against Kubernetes nodes or environments and checks selected configuration against supported CIS Benchmark recommendations.',
    purpose: 'Identify Kubernetes configuration deviations that require validation and risk-based remediation.',
    capabilities: ['Control-plane checks', 'Node checks', 'Benchmark-aligned output', 'Automation support'],
    boundary: 'A benchmark check is not complete cluster security. Version, distribution, managed-service responsibility and workload controls matter.',
    officialUrl: 'https://github.com/aquasecurity/kube-bench', keywords: ['kube-bench', 'kubernetes', 'cis benchmark', 'hardening', 'container'],
  },
  {
    slug: 'lynis', name: 'Lynis', family: 'Linux and Unix security auditing',
    placement: 'Runs locally on a Linux or Unix-like host and inspects configuration, packages, services, files and hardening signals.',
    purpose: 'Create a structured host-hardening review and highlight areas that need administrator validation.',
    capabilities: ['Host configuration audit', 'Hardening suggestions', 'Package and service checks', 'Compliance-oriented reporting'],
    boundary: 'Recommendations are not universally correct. Validate them against system purpose, distribution, service dependencies and change safety.',
    officialUrl: 'https://cisofy.com/lynis/', keywords: ['lynis', 'linux', 'hardening', 'audit', 'configuration', 'unix'],
  },
  {
    slug: 'openscap', name: 'OpenSCAP', expansion: 'Open Security Content Automation Protocol', family: 'Configuration and compliance assessment',
    placement: 'Runs on supported Linux systems or against images using machine-readable security content and profiles.',
    purpose: 'Assess and, where appropriate, remediate system configuration against selected baselines and policy content.',
    capabilities: ['SCAP content evaluation', 'Profile-based assessment', 'Machine-readable results', 'Selected remediation generation'],
    boundary: 'A selected profile may not fit the workload. Remediation can disrupt service, so review, test, stage and retain exceptions.',
    officialUrl: 'https://www.open-scap.org/', keywords: ['openscap', 'scap', 'linux', 'compliance', 'hardening', 'configuration'],
  },
  {
    slug: 'bloodhound', name: 'BloodHound', family: 'Identity attack-path analysis',
    placement: 'Collects authorized identity and relationship data from Microsoft Active Directory or supported cloud identity environments and analyzes it as a graph.',
    purpose: 'Reveal chains of permissions, sessions, group membership and administrative relationships that could lead to privilege escalation.',
    capabilities: ['Identity relationship graphing', 'Privilege-path discovery', 'Cypher-based analysis', 'Remediation prioritization'],
    boundary: 'Collection and graph data are sensitive. Use test or explicitly authorized environments, protect the database and validate each inferred path before action.',
    officialUrl: 'https://bloodhound.specterops.io/', keywords: ['bloodhound', 'active directory', 'entra', 'identity', 'privilege escalation', 'attack path'],
  },
  {
    slug: 'impacket', name: 'Impacket', family: 'Network protocol and identity testing',
    placement: 'Runs as Python libraries and utilities from an authorized administration, assessment or investigation host against Windows-oriented network protocols.',
    purpose: 'Implement and inspect protocol behavior for controlled administration, forensic work and identity-security validation.',
    capabilities: ['SMB and MSRPC protocol support', 'Kerberos and NTLM utilities', 'Remote-service interaction', 'Packet construction and parsing'],
    boundary: 'Many utilities can create powerful remote effects. Use only with written authority, controlled accounts and a minimum-proof plan.',
    officialUrl: 'https://github.com/fortra/impacket', keywords: ['impacket', 'smb', 'kerberos', 'ntlm', 'active directory', 'windows', 'red team'],
  },
  {
    slug: 'wazuh', name: 'Wazuh', family: 'Open security monitoring platform',
    placement: 'Uses endpoint agents, a management server, indexing and dashboards to collect and analyze security and configuration data.',
    purpose: 'Combine host monitoring, file-integrity data, vulnerability information, configuration assessment and alerting in one operational platform.',
    capabilities: ['Host-based detection', 'File-integrity monitoring', 'Configuration assessment', 'Security-event analysis'],
    boundary: 'Coverage depends on agent deployment, data quality, rule tuning and response ownership. A dashboard is not evidence that every alert is handled.',
    officialUrl: 'https://documentation.wazuh.com/', keywords: ['wazuh', 'siem', 'xdr', 'endpoint', 'file integrity', 'compliance', 'detection'],
  },
  {
    slug: 'prowler', name: 'Prowler', family: 'Cloud security assessment',
    placement: 'Runs with read-oriented cloud permissions against supported cloud accounts and services to evaluate configuration and security posture.',
    purpose: 'Identify cloud configuration issues and map findings to selected security frameworks and operational checks.',
    capabilities: ['Cloud configuration checks', 'Multi-provider support', 'Framework mappings', 'Machine-readable reporting'],
    boundary: 'A check result requires ownership and context. Scope, permissions, service coverage and managed-service responsibility can create blind spots.',
    officialUrl: 'https://docs.prowler.com/', keywords: ['prowler', 'aws', 'azure', 'gcp', 'cloud', 'cspm', 'configuration'],
  },
  {
    slug: 'scoutsuite', name: 'ScoutSuite', family: 'Multi-cloud security auditing',
    placement: 'Uses authorized cloud API access to collect configuration data and generate an assessment report for supported providers.',
    purpose: 'Help reviewers understand cloud attack surface, risky configuration and account-level control gaps.',
    capabilities: ['Multi-cloud collection', 'Configuration-rule evaluation', 'Visual findings report', 'Offline report review'],
    boundary: 'Results reflect collected API data and built-in rules. Validate account coverage, exceptions, temporal change and business context.',
    officialUrl: 'https://github.com/nccgroup/ScoutSuite', keywords: ['scoutsuite', 'cloud', 'aws', 'azure', 'gcp', 'audit', 'cspm'],
  },
  {
    slug: 'syft', name: 'Syft', family: 'Software bill of materials generation',
    placement: 'Runs against source directories, container images and filesystems in developer or delivery workflows.',
    purpose: 'Identify packaged software components and produce a Software Bill of Materials in supported formats.',
    capabilities: ['Package discovery', 'Container-image analysis', 'CycloneDX and SPDX output', 'Pipeline integration'],
    boundary: 'A Software Bill of Materials can be incomplete and does not state whether a component is exploitable, maintained or approved.',
    officialUrl: 'https://github.com/anchore/syft', keywords: ['syft', 'sbom', 'software supply chain', 'container', 'dependencies', 'spdx', 'cyclonedx'],
  },
  {
    slug: 'grype', name: 'Grype', family: 'Software composition and image vulnerability scanning',
    placement: 'Runs against container images, filesystems and Software Bills of Materials in developer and delivery environments.',
    purpose: 'Match identified packages to known vulnerability data and support remediation triage.',
    capabilities: ['Package vulnerability matching', 'Container and filesystem scanning', 'Software Bill of Materials input', 'Policy-oriented output'],
    boundary: 'Matches can be affected by package detection, advisory sources and unreachable code. Combine results with exploitability, exposure and asset importance.',
    officialUrl: 'https://github.com/anchore/grype', keywords: ['grype', 'sca', 'vulnerability', 'container', 'sbom', 'software supply chain'],
  },
];

export const toolCatalog: ToolProfile[] = [...securityToolCatalog, ...platformToolCatalog];
